### ISSUE TITLE
make error: vfork: resource temporarily unavailable

### ISSUE THREAD

**Issue by timjim333** [xianyi/OpenBLAS#1348] opened 2017-11-06 06:24 UTC
Hi,

I'm trying to install OpenBLAS 0.2.20 on a node in a local directory over which I have permissions (I don't have root access). I seem to be encountering an error when attempting the build process. Trying `make` with or without any flags is resulting in a long string of errors that look like:
`make[1]: vfork: Resource temporarily unavailable`

I've posted the whole output in a text file. Could anyone give any suggestions on how to troubleshoot the problem? 
[make_error.txt](https://github.com/xianyi/OpenBLAS/files/1445213/make_error.txt)

Many thanks. Tim

EDIT: In case this is useful, here is also the output of a few server parameters.

`uname - or`
2.6.32.54-0.3-default GNU/Linux

`lsb_release -a`
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	SUSE LINUX
Description:	SUSE Linux Enterprise Server 11 (x86_64)
Release:	11
Codename:	n/a

`cat /etc/*-release`
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
SGI Accelerate 1.3, Build 705r10.sles11-1110192111
SGI Foundation Software 2.5, Build 705r10.sles11-1110192111
SGI MPI 1.3, Build 705r10.sles11-1110192111
SGI Performance Suite 1.3, Build 705r10.sles11-1110192111
SGI UPC 1.3, Build 705r10.sles11-1110192111
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 1

`lscpu`:
Architecture:          x86_64
CPU(s):                64
Thread(s) per core:    1
Core(s) per socket:    8
CPU socket(s):         8
NUMA node(s):          8
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 46
Stepping:              6
CPU MHz:               2266.424
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              24576K

**Comment by martin-frbg** [comment] 2017-11-06 07:57
Looks like you are running out of resources - be it available memory or number of concurrent processes.
Try reducing the number of subprocesses started by make - either set MAKE_NB_JOBS to a low number (it defaults to the number of cores detected, which may be inappropriate for your virtual system), or run with NO_PARALLEL_MAKE=1 (see Makefile.rule for available `make` options)

**Comment by timjim333** [comment] 2017-11-06 08:38
Thanks for the comment. I tried setting the `NO_PARALLEL_MAKE` option in `Makefile.rule` but I seem to have stumbled into another problem. I've attached the last few lines below. I'm fairly new to compiling these programs so I may have missed something obvious!

I had also set the prefix options and the gfortran thread safe options.

make[2]: Leaving directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack/trtri'
make[1]: Leaving directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack'
make[1]: Entering directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack-netlib'
( cd INSTALL; make )
make[2]: Entering directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack-netlib/INSTALL'
gfortran -openmp -fp-model precise -I/ap/vni/imsl/fnl700/lnxsg111e64/include -O2 -frecursive -Wall -m64 -fPIC -c -o lsame.o lsame.f
gfortran: precise: No such file or directory
f951: error: unrecognized command line option "-fp-model"
make[2]: *** [lsame.o] Error 1
make[2]: Leaving directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack-netlib/INSTALL'
make[1]: *** [lapack_install] Error 2
make[1]: Leaving directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack-netlib'
make: *** [netlib] Error 2

**Comment by brada4** [comment] 2017-11-06 08:49
Can you share custom "gfortran thread safe" parameters you are using?
fp-model is Intel compiler flag.

Does it finish compilation by simple 'make clean ; make MAKE_NB_JOBS=1' ?

**Comment by martin-frbg** [comment] 2017-11-06 08:49
Your fortran compiler does not understand the option "-fp-model precise" (which it probably picked up from some FLAGS variable in your environment - the option appears to be specific to the Intel compiler
while you are using gfortran)

**Comment by timjim333** [comment] 2017-11-06 09:02
Thanks for the thoughts. This was the Makefile.rule I was using.
[Makefile.rule.txt](https://github.com/xianyi/OpenBLAS/files/1445564/Makefile.rule.txt)

I will try again with 'make clean ; make MAKE_NB_JOBS=1'

**Comment by timjim333** [comment] 2017-11-06 09:20
It got a little closer! Using the above (only adding a prefix and MAKE_NB_JOBS=1), it seems that it has defaulted to using ifort, which seems to understand the '-fp-model precise' flag but has the following issue. The last few lines are posted below. Did it fail attempting to compile a fortran code?

...
ifort -openmp -fp-model precise -I/ap/vni/imsl/fnl700/lnxsg111e64/include -O2 -fPIC -c ssytrd_sb2st.F -o ssytrd_sb2st.o
ssytrd_sb2st.F(486): error #5082: Syntax error, found IDENTIFIER 'DEPEND' when expecting one of: UNTIED PRIVATE FIRSTPRIVATE SHARED IF DEFAULT <END-OF-STATEMENT> ;
!$OMP TASK DEPEND(in:WORK(MYID+SHIFT-1))
-----------^
ssytrd_sb2st.F(487): error #5082: Syntax error, found IDENTIFIER 'DEPEND' when expecting one of: ( % . = =>
!$OMP$     DEPEND(in:WORK(MYID-1))
-----------^
ssytrd_sb2st.F(488): error #5082: Syntax error, found IDENTIFIER 'DEPEND' when expecting one of: ( * ) :: , <END-OF-STATEMENT> ; + . - % (/ [ : ] /) . ' ** / ...
!$OMP$     DEPEND(out:WORK(MYID))
-----------^
ssytrd_sb2st.F(488): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: :
!$OMP$     DEPEND(out:WORK(MYID))
---------------------------------^
ssytrd_sb2st.F(497): error #5082: Syntax error, found IDENTIFIER 'DEPEND' when expecting one of: UNTIED PRIVATE FIRSTPRIVATE SHARED IF DEFAULT <END-OF-STATEMENT> ;
!$OMP TASK DEPEND(in:WORK(MYID+SHIFT-1))
-----------^
ssytrd_sb2st.F(498): error #5082: Syntax error, found IDENTIFIER 'DEPEND' when expecting one of: ( % . = =>
!$OMP$     DEPEND(out:WORK(MYID))
-----------^
ssytrd_sb2st.F(497): error #6404: This name does not have a type, and must have an explicit type.   [DEPEND]
!$OMP TASK DEPEND(in:WORK(MYID+SHIFT-1))
-----------^
ssytrd_sb2st.F(497): error #6514: A substring must be of type CHARACTER.   [DEPEND]
!$OMP TASK DEPEND(in:WORK(MYID+SHIFT-1))
-----------^
ssytrd_sb2st.F(497): error #6404: This name does not have a type, and must have an explicit type.   [IN]
!$OMP TASK DEPEND(in:WORK(MYID+SHIFT-1))
------------------^
ssytrd_sb2st.F(498): error #6514: A substring must be of type CHARACTER.   [DEPEND]
!$OMP$     DEPEND(out:WORK(MYID))
-----------^
ssytrd_sb2st.F(498): error #6404: This name does not have a type, and must have an explicit type.   [OUT]
!$OMP$     DEPEND(out:WORK(MYID))
------------------^
compilation aborted for ssytrd_sb2st.F (code 1)
make[2]: *** [ssytrd_sb2st.o] Error 1
make[2]: Leaving directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack-netlib/SRC'
make[1]: *** [lapacklib] Error 2
make[1]: Leaving directory `/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20_src/lapack-netlib'
make: *** [netlib] Error 2

**Comment by brada4** [comment] 2017-11-06 09:21
You can try recording output from compilation with "script"

**Comment by brada4** [comment] 2017-11-06 09:24
Can you run plain "make" in freshly cloned/unzipped OpenBLAS 0.2.20 or git develop branch?
You inherit some *_FLAGS from unrelated products, probably built next door. i dare not to guess what could be
`vni/imsl/fnl700/lnxsg111e64`

**Comment by martin-frbg** [comment] 2017-11-06 09:41
Which version of ifort is that ? Apparently it does not cope with some of the OPENMP directives, which would suggest a rather old version of the Intel compiler. (Having what appears to be the include file path of the IMSL library in the compiler options probably does not hurt, but is not useful either - you may want to check with whoever administers this system which compiler and options to use there)

**Comment by timjim333** [comment] 2017-11-06 10:09
Hi, I had a chat with one of the admins and they suggested switching to a more modern node - you were correct, the previous was an old one! I tried a fresh build using `make PREFIX=/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20`. (I assume adding the prefix is ok? Since I don't have permissions for the other directories).

Please see attached for the output script.
[make_output.txt](https://github.com/xianyi/OpenBLAS/files/1445752/make_output.txt)

There still seems to be some kind of issue with the compile? Thanks for the help.

If you nmeed the info, here are the new node parameters:
`uname -or`
3.0.101-108.13-default GNU/Linux

`lsb_release -a`
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	SUSE LINUX
Description:	SUSE Linux Enterprise Server 11 (x86_64)
Release:	11
Codename:	n/a

`lscpu`
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                640
On-line CPU(s) list:   0-639
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             64
NUMA node(s):          64
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               2399.982
BogoMIPS:              4802.71
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9
... and a lot of NUMA nodes here ...

**Comment by brada4** [comment] 2017-11-06 10:19
Compiler problems cannot be solved in absence of versions, and probably you need to approach intel support website if you want to interlink their modules with gcc ones.

I wonder if this is relevant?
https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages#opensusesle

Can you cut last CPU core ID from /proc/cpuinfo, it has all the sibling numbers, and most notably lets identify CPU generation you have.

**Comment by martin-frbg** [comment] 2017-11-06 10:21
The Intel fortran compiler on that node still seems unable to handle OpenMP4.0 directives. Do you want to use it anyway, or is it just picked as first choice because of something in your environment ? (You could try with `make FC=gfortran` after a `make clean`, assuming that the GNU fortran compiler is installed on that node as well)

**Comment by brada4** [comment] 2017-11-06 10:22
Actually "make clean" is absent in all build logs....

**Comment by brada4** [comment] 2017-11-06 23:58
What are compiler versions? `gcc --version ; gfortran --version`
btw LSB does not define any compiler standard interface, no need to post it at all.

**Comment by timjim333** [comment] 2017-11-07 06:56
Hi, thanks for the posts above. 

@martin-frbg I didn't have a specific requirement to use ifort as such - I'm just not aware of the difference. Does the choice of compiler actually affect the compiled program in any way? (I'm assuming performance or compatibility?) Essentially, I want to build BLAS and LAPACK for use with a CFD solver (SU2). I'll try with `make FC=gfortran` and see if that makes a difference!

@brada4 I had rm -r 'd the directory and unzipped a fresh copy before starting `script`! I'm not sure which info is relevant, so I've attached a copy of the cpuinfo file here: 
[cpuinfo.txt](https://github.com/xianyi/OpenBLAS/files/1448944/cpuinfo.txt)
Regarding versions:
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]
GNU Fortran (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]

**Comment by timjim333** [comment] 2017-11-07 07:17
Here is the output using gfortran `make PREFIX=/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20 FC=gfortran`: [make_output.txt](https://github.com/xianyi/OpenBLAS/files/1448988/make_output.txt)

It seems even is it still not recognising some of the commands. Do I have to setup the server in any other way? Thanks.

**Comment by martin-frbg** [comment] 2017-11-07 07:52
Now you are calling GNU gfortran with the options for the Intel compiler, which it does not recognize. Please try to find out where these are coming from (probably a FFLAGS setting in your shell).
Regarding the choice of compiler - both would normally be expected to work, and some may say that the Intel compiler still generates faster code. Your installation of the Intel compiler however appears to be either ancient or incomplete, making it unable to handle some statements in the code.

**Comment by timjim333** [comment] 2017-11-07 07:57
After a quick google, FFLAGS are fortran flags is that correct? I did a quick `echo $FFLAGS` and it returned the following:
-openmp -axAVX -fp-model source -I/ap/vni/imsl/fnl701/lnxsg121e64/include

I don't know if they are necessary for anything on the node, but I suppose that these are the ones causing issues? How should I remove them temporarily? Is it safe to do so?

**Comment by martin-frbg** [comment] 2017-11-07 08:12
`unset FFLAGS` should do the trick. (You will need them only when you want to build something with the Intel fortran compiler, and depending on where and when these defaults were added to your user environment they may not even be appropriate for the current compute node)

**Comment by timjim333** [comment] 2017-11-07 08:16
I see, so they could be remnants of an admin's setup? After running `unset FFLAGS`, should I try the default FC or go with gfortran again? Thanks @martin-frbg

**Comment by martin-frbg** [comment] 2017-11-07 08:29
Go with gfortran (or try to get an admin to look into why your intel compiler installation does not handle openmp4 directives - as far as I can find out, these should be supported by ifort since the 2015 version. Maybe yours is just too old - your gfortran is quite old as well)

**Comment by brada4** [comment] 2017-11-07 11:39
can you attach what "set" outputs so we can help you to tidy it up?
The problem is caused by openblas build system using all sorts of CFLAGS etc temporarily internally and not making good friends if they are set ahead of time.
btw OpenBLAS builds (or at least used to recently) on RHEL5 with even older gcc.

**Comment by timjim333** [comment] 2017-11-09 05:23
Hello, after a chat with the admins, I'll try to build the latest gfortran for this (and other builds I need) before trying again. 

I don't know if this will still be an issue, but I tried building with a slightly newer version of gcc packaged with openfoam but received an error regarding max_nodes (NUMA) is too small? I've attached the output here: [make.txt](https://github.com/xianyi/OpenBLAS/files/1456375/make.txt)

Also here is the result of `set`: [set.txt](https://github.com/xianyi/OpenBLAS/files/1456378/set.txt)

Thanks for the install support.

**Comment by brada4** [comment] 2017-11-09 06:01
You must use BIGNUMA=1 build flag for >256 CPU cores (see Makefile.rule)
For variables:
$unset FC F90 F90FLAGS 
$make clean ; make BIGNUMA=1

**Comment by timjim333** [comment] 2017-11-10 05:54
I just built gfortran 7.2.0 in my local home directory and attempted to run the make process again, specifically running:
`make clean`
`unset FC F90 F90FLAGS FFLAGS`
`make PREFIX=/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20 FC=gfortran BIGNUMA=1`

It now seems to reach the test stage before failing with `GotoBLAS : Can't open shared memory. Terminated.` The full output is attached here: [make.txt](https://github.com/xianyi/OpenBLAS/files/1460222/make.txt)
And to confirm versions: [versions.txt](https://github.com/xianyi/OpenBLAS/files/1460223/versions.txt)

**Comment by martin-frbg** [comment] 2017-11-10 08:26
Strange duplicity as I have just committed a change that will show a more detailed error message when shared memory allocation fails. The background for that was #1351 where use of SELinux apparently blocked access to shared memory segments, though in your case it happens even earlier when OpenBLAS tries to allocate a shared memory segment of size 32768. 
Perhaps this information gives your local sysadmin a clue already ? There is nothing in the manpage for shmget() that suggests we are trying something naughty, though for smaller systems without BIGNUMA=1 set the requested size is only 4096 here. Unfortunately I have no personal experience with your class of hardware.

**Comment by martin-frbg** [comment] 2017-11-10 08:44
From #1351, you should be able to get around this by setting `setenforce 0` if it happens to be SELinux-related, provided you have sufficient rights to use the setenforce command. Interventions by this kind of security-hardening software will probably also be logged somewhere on the system.

**Comment by timjim333** [comment] 2017-11-10 09:30
@martin-frbg it seems like the `setenforce` command does not exist on my distro - at least I was presented with: `bash: setenforce: command not found`. I think the supercomputer is running SUSE. Should I try to run a single core compile with NUM_THREADS=1? Or will this not help?

**Comment by martin-frbg** [comment] 2017-11-10 10:02
You would probably need to be root to use setenforce, but it can also be that SELinux is not installed.
A single core compile would certainly work but it depends on your use case if a single-threaded OpenBLAS library is suitable for you - if you want to use it from a program that already creates multiple threads for its calculations it would probably be fine even in terms of performance. 
If everything is singlethreaded, you would obviously lose most of the advantages of the multicore system, but at least you would be able to run programs that make use of BLAS or LAPACK functions (and still get some speedup compared to the netlib reference implementation).

**Comment by timjim333** [comment] 2017-11-10 10:12
Do I have many troubleshooting options left for a multi threaded install?

**Comment by martin-frbg** [comment] 2017-11-10 10:33
Should be fine as long as the trouble does not start to shoot back (though with that big supercomputer, you may be venturing where few have gone before). 
You'd need to get the current development snapshot of OpenBLAS from github to get the better error messages (use the green "Clone or Download" button to the right of the table heading on the "Code" tab here to either follow the instructions for a "git clone" call or to download a zip archive). And if possible talk to some local admin about what could cause accesses to shared memory to fail (maybe you just need to get appropriate user permissions on that supercomputer)

**Comment by timjim333** [comment] 2017-11-15 09:28
Hi, I have spoken to the admin and they said they will investigate. In the meantime, I downloaded a new copy of `develop` and attempted a fresh install. I have attached a copy of the output in the following file. It appears to finish compiling but fails on the tests with a 'Segmentation fault' - does the new install present any new information? Many thanks.
[make_output.txt](https://github.com/xianyi/OpenBLAS/files/1474042/make_output.txt)

**Comment by martin-frbg** [comment] 2017-11-15 09:48
Strange that it segfaults now without printing the cause of the shmget error, maybe I did something wrong in that recent change after all. (Could be the last error number (errno) is already undefined when I try to print it, as the shmget is retried in a loop.)

**Comment by martin-frbg** [comment] 2017-11-15 10:38
If you have the `ipcs` command available, you could run `ipcs -l` to see what if any shared memory resources are available to you.

**Comment by brada4** [comment] 2017-11-15 13:32
You can run your test program withing gdb (or admin can do)
As minimum show output of:

gdb ./testprog
gdb> run
Signal crash whatever
gdb> t a a bt
(this is the interesting thing, might be long for 1000 threads)

**Comment by martin-frbg** [comment] 2017-11-15 13:49
@brada4 I think he (still) does not get far enough to have more than one thread - the fundamental problem is still the same (unable to obtain shared memory, hence unable to set up two threads in the tests), only now there is a segfault without any error message instead of the more verbose message I had committed for this case. The only reason for this (I think) is that errno has become undefined by
the time the code reaches the perror() call and it is the perror printout itself now that is segfaulting due to this.

**Comment by brada4** [comment] 2017-11-15 14:33
There should be some grain in bt-s

**Comment by martin-frbg** [comment] 2017-11-15 14:39
Methinks driver/others/init.c should be updated to this here (rename back from .txt to .c)
[init.txt](https://github.com/xianyi/OpenBLAS/files/1475078/init.txt) but I am having trouble updating my fork for a regular PR at the moment. @timjim333 perhaps you can just replace the file and recompile to see if this brings some more useful info ?

**Comment by timjim333** [comment] 2017-11-15 16:22
I'll give the recompile a go. Meanwhile, it seems that the server has `ipcs`, here is the output:

```
FIa164@afispb07:~/programs/openblas/OpenBLAS-0.2.20_src$ ipcs -l

------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 18014398509481983
max total shared memory (kbytes) = 4611686018427386880
min seg size (bytes) = 1

------ Semaphore Limits --------
max number of arrays = 1024
max semaphores per array = 250
max semaphores system wide = 256000
max ops per semop call = 32
semaphore max value = 32767

------ Messages Limits --------
max queues system wide = 32768
max size of message (bytes) = 65536
default max size of queue (bytes) = 65536
```

**Comment by martin-frbg** [comment] 2017-11-15 17:28
Nothing obvious from that, looks similar to my laptop except perhaps for the memory size ...

**Comment by timjim333** [comment] 2017-11-16 01:21
@brada4 apologies, I'm not sure I follow regarding your post on gdb. I could start `gdb` but I'm not sure what `testprog` file to test in particular - what would be a sufficient? Is signal crash a ctrl-c? Thanks.

**Comment by timjim333** [comment] 2017-11-16 01:25
And here is the ouput from a recompile with the new init.c (I ran `make clean` before this).
[make_output.txt](https://github.com/xianyi/OpenBLAS/files/1476981/make_output.txt)

**Comment by brada4** [comment] 2017-11-16 03:48
Should be gdb ./sblat1 in tests/

**Comment by timjim333** [comment] 2017-11-16 07:27
I attempted to run the test but not a lot came out of it: [gdb_test.txt](https://github.com/xianyi/OpenBLAS/files/1477661/gdb_test.txt)

Was this the expected output?

**Comment by martin-frbg** [comment] 2017-11-16 07:34
Can you try `OPENBLAS_NUM_THREADS=2 gdb ./sblat1` please ?

**Comment by timjim333** [comment] 2017-11-16 07:51
Please see attached. Not much seems to have changed! [gdb_test2.txt](https://github.com/xianyi/OpenBLAS/files/1477716/gdb_test2.txt)

**Comment by martin-frbg** [comment] 2017-11-16 07:54
Nothing could have changed, please put that on one line

**Comment by brada4** [comment] 2017-11-16 10:00
You need to repeat "r" maybe multiple times until it crashes with same message as during build.

**Comment by timjim333** [comment] 2017-11-16 12:25
@brada4 Sorry, I'm not sure what you mean? Should I enter `r` after calling `run`?

**Comment by martin-frbg** [comment] 2017-11-16 12:36
Seems he wanted you to repeat the run (from within gdb) as it did not crash the first time. 
My suspicion is that you need to have the `OPENBLAS_NUM_THREADS=2` and `gdb ./sblat1` on the same command line to ensure the test actually runs with two threads (but that depends on the shell you use, in bash that is usually the default on SuSE your approach is fine).

**Comment by timjim333** [comment] 2017-11-16 13:32
Is this what you mean? I called `run` quite a few times but it did not crash. Should I keep calling `run`?[gdb_test3.txt](https://github.com/xianyi/OpenBLAS/files/1478667/gdb_test3.txt)

**Comment by martin-frbg** [comment] 2017-11-16 13:43
Can you try with spaces where you put the ampersands, to make sure the THREADS setting ends up in the same environment  that sblat1 sees ?
`OPENBLAS_NUM_THREADS=2 gdb ./sblat1`

**Comment by brada4** [comment] 2017-11-16 18:21
Something is different between when the test runs and under GDB but I dont understand what.

**Comment by martin-frbg** [comment] 2017-11-16 19:02
Maybe there is a memory problem somewhere in the BIGNUMA code, but at the very least I would expect it to get as far as previous runs, i.e. to the point where the code printed the "cannot open shared memory" message and should be printing a more detailed message including a reason now. So my bet is still on the OPENBLAS_NUM_THREADS setting not getting seen by the code.

**Comment by timjim333** [comment] 2017-11-17 04:35
That did the trick and triggered the seg fault. [gdb_test4.txt](https://github.com/xianyi/OpenBLAS/files/1481037/gdb_test4.txt)

**Comment by timjim333** [comment] 2017-11-17 06:52
I seem to have had a successful compile - under the suggestion of the admin, I added the `NO_AFFINITY` flag in the make call: `make PREFIX=/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20 FC=gfortran BIGNUMA=1 NO_AFFINITY=1`. The output can be seen here: [make_output.txt](https://github.com/xianyi/OpenBLAS/files/1481291/make_output.txt)
This is still with the replaced `init.c` that you sent earlier. Has this produced the expected result and will installing this build produce a working copy of OpenBLAS?

**Comment by brada4** [comment] 2017-11-17 09:18
Yes, you have usable OpenBLAS, and you pointed to issue that BIGNUMA=1+NO_AFFINITY=0 causes failure initialising thread affinity.

**Comment by martin-frbg** [comment] 2017-11-17 09:20
Yes, looks like this produced a usable build (though performance may be decreased by threads getting rescheduled to a different processor occasionally). I will need to look at the code path leading to the shared memory allocation again, seems the informational message I added to the latest init.c may be wrong and the code will just lose cpu affinity but not multithreading when the shmget fails.
Unfortunately the gdb backtrace does not show the failing call, OpenBLAS would need to be build with 
DEBUG=1 to add the necessary symbols for the debugger. (Apologies for not mentioning this earlier).
So far all that can be learned is that it segfaults in the routine that initiates the previously failing calls
to shmget/shmat - maybe now that these failures are handled, it staggers on a bit beyond them.

**Comment by timjim333** [comment] 2017-11-17 09:34
I see, so in the meantime I can link to this build then. Meanwhile, I'm
happy to rebuild with a debug flag if that helps get to the root of the
problem.

**Comment by brada4** [comment] 2017-11-17 10:26
... and once permanent code fix is in place ... just replace library file with new one...
i.e dont close the issue, your help with big system testing will be handy.

**Comment by timjim333** [comment] 2017-11-17 13:40
Right, so I will rebuild with `make PREFIX=/home/FIa/FIa164/programs/openblas/OpenBLAS-0.2.20 FC=gfortran BIGNUMA=1 DEBUG=1` and attempt torun the gdb tet again.

**Comment by timjim333** [comment] 2017-11-21 07:55
I built a a debug build using the following and ran the `gdb` test. I've attached the results below - I hope it helps.
```
unset FC F90 F90FLAGS FFLAGS
make PREFIX=/home/FIa/FIa164/programs/openblas/TEST_OpenBLAS-0.2.20 FC=gfortran BIGNUMA=1 DEBUG=1
```
[make_debug.txt](https://github.com/xianyi/OpenBLAS/files/1490449/make_debug.txt)
[debug_out.txt](https://github.com/xianyi/OpenBLAS/files/1490450/debug_out.txt)

**Comment by martin-frbg** [comment] 2017-11-21 09:40
Not sure yet what to make of this - the node_info array is declared to hold MAX_NODES (128) and MAX_BITMASK_LEN members so I would not expect it to overflow in this initialization loop (unless the calculation of MAX_BITMASK_LEN went wrong much earlier - this is the number of cpus as returned by the CPU_SETSIZE macro divided by 64).
Can you do
```
print j
print  node
print MAX_BITMASK_LEN
```
where you currently have the `t a a bt` please ?

**Comment by timjim333** [comment] 2017-11-21 10:09
Here is the output. There was no `MAX_BITMASK_LEN`: [debug_out2.txt](https://github.com/xianyi/OpenBLAS/files/1490871/debug_out2.txt)

**Comment by martin-frbg** [comment] 2017-11-21 11:32
Hmm. Seems one would need to build with a higher debug level flag to get access to #defined constants.
But checking on my system, CPU_SETSIZE appears to be 4096 (although the manpage claims 1024) on all Linux platforms at the moment, and 8*sizeof(unsigned long) should be either 32 or 64 so the loop should still do fine on element 59 of 64. 
Guess you could try replacing the single occurence of CPU_SETSIZE near the top of driver/others/init.c by some number that is only somewhat bigger than your actual 640 cpus, say 896 just to see if
this changes anything. On the other hand I think it should be possible to trick a BIGNUMA build into running into the problematic code on my small system so maybe I can track this down myself.

**Comment by martin-frbg** [comment] 2017-11-21 12:13
Well, replacing the CPU_SETSIZE by 896 works for me here, while with CPU_SETSIZE it happens to fail at j=59 (though different nodes number) as well. My current thinking is that the struct just gets too big to fit on the stack.

**Comment by martin-frbg** [comment] 2017-11-21 14:24
Turns out there appears to be (or have been) some disagreement between glibc maintainers, in particular from SuSE about raising the value (as set in /usr/include/bits/sched.h) for CPU_SETSIZE from 1024 to 4096. (As far as I understood the discussion threads, this was to reflect increased capability of the Linux kernel when built with "maximum NUMA nodes" option, but the criticism was that it broke the API). The last discussion appears to have taken place here, which contains some hints for correct usage of sched_getaffinity() on big systems that may be relevant for OpenBLAS: 
 https://sourceware.org/ml/libc-alpha/2016-03/msg00043.html
At the very least it is conceivable that wernsaar's (experimental) code for BIGNUMA support was never tested, nor expected to work beyond the "traditional" value of 1024. In my absolutely unscientifc tests,
2048 appeared to still work (although I currently do not own a laptop capable of traversing all affected code paths  :-) ) so my suggestion is to replace the current use of CPU_SETSIZE with a constant 2048 or 1024 as a quick fix.

**Comment by martin-frbg** [comment] 2017-11-21 21:16
3232 appears to be about the limit that still survives the compile tests for me, 3264 is already crashing.

**Comment by timjim333** [comment] 2017-11-22 05:58
@martin-frbg in `init.c`, can I confirm, you mean that I should try replacing the below block:

```
#if defined(BIGNUMA)
// max number of nodes as defined in numa.h
// max cpus as defined in sched.h
#define MAX_NODES	128
#define MAX_CPUS	CPU_SETSIZE
#else
#define MAX_NODES	16
#define MAX_CPUS	256
#endif
```

with:

```
#if defined(BIGNUMA)
// max number of nodes as defined in numa.h
// max cpus as defined in sched.h
#define MAX_NODES	128
#define MAX_CPUS	1024
#else
#define MAX_NODES	16
#define MAX_CPUS	256
#endif
```

then `make clean`, recompile and run the gdb test, is that correct?

**Comment by martin-frbg** [comment] 2017-11-22 06:58
Yes, exactly. If it works, you should already see the build pass all tests.

**Comment by timjim333** [comment] 2017-11-22 08:09
@martin-frbg Is there an alternative debug level I should set, or should I go with `make PREFIX=/home/FIa/FIa164/programs/openblas/TEST_OpenBLAS-0.2.20 FC=gfortran BIGNUMA=1 DEBUG=1` again?

**Comment by brada4** [comment] 2017-11-22 11:42
You can add NO_LAPACK=1 NO_CBLAS=1 , it will not make complete library usable for you, but just bare minimum to get fastest to the test that fails. Sure 'make clean' between tries.

**Comment by martin-frbg** [comment] 2017-11-22 12:43
I'd just do a normal build, assuming that with such a big system build time should not be an issue.

**Comment by timjim333** [comment] 2017-11-22 13:10
Alright, so sticking with `DEBUG=1` then.

**Comment by brada4** [comment] 2017-11-22 17:50
In principle there is 'ar' invoked after blaS, then cblas, then lapack, then lapacke. In principle rebuilding last 3 is not necessary for rapid repeater.

**Comment by martin-frbg** [comment] 2017-12-02 16:30
@timjim333 , did you get around to testing this ?

**Comment by timjim333** [comment] 2017-12-05 08:25
Yes, sorry for the delay. It appears to build without errors: [debug_out3.txt](https://github.com/xianyi/OpenBLAS/files/1530228/debug_out3.txt)

**Comment by martin-frbg** [comment] 2017-12-05 09:48
Great, thanks for testing. I'll prepare the corresponding PR to fix this in the develop branch later.

**Closed as completed** 2017-12-05 18:52 UTC
