### ISSUE TITLE
Cannot compile OpenBLAS: USE_OPENMP=1 issue

### ISSUE THREAD

**Issue by PrajitR** [xianyi/OpenBLAS#517] opened 2015-03-16 14:17 UTC
I'm trying to compile OpenBLAS for Torch. I'm using Ubuntu 14.04 LTS Virtual Machine running on top of Windows 8. The compile flags are `NO_AFFINITY=1 USE_OPENMP=1`. I get this error:

```
Makefile.system:370: *** OpenBLAS: Cannot set both USE_OPENMP=1 and USE_THREAD=0. The USE_THREAD=0 is only for building single thread version..  Stop.
```

It compiles with just `NO_AFFINITY=1`, but does not compile with the `USE_OPENMP=1` flag.

**Comment by xianyi** [comment] 2015-03-16 16:14
How many cpu cores on your virtual machine? Is it only one CPU core?

**Comment by PrajitR** [comment] 2015-03-21 15:04
You were right. I only had one CPU core. I changed it to have 3 CPU cores. Now I have another problem using the flags `NO_AFFINITY=1 USE_OPENMP=1`:

```
../libopenblas_nehalemp-r0.2.13.a(openblas_set_num_threads.o):openblas_set_num_threads.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_nehalemp-r0.2.13.so] Error 1
make[1]: Leaving directory `/home/prajit/OpenBLAS/exports'
make: *** [shared] Error 2
```

It passes all of the computational and error-exits tests.

**Comment by xianyi** [comment] 2015-03-21 18:38
@PrajitR ， I cannot reproduce this error on my Ubuntu machine.
Could you try `make USE_OPENMP=1`?

**Comment by JAaron9311** [comment] 2015-04-20 13:58
@PrajitR I met the same issue as you did. But it fixed when I changed it to have 4 CPU cores.

**Comment by JAaron9311** [comment] 2015-04-20 14:04
@PrajitR I met the exact same problem as you did. Have you fixed it?

**Comment by xianyi** [comment] 2015-04-23 18:04
@JAaron9311 , what's error?  Did you meet the error with`make NO_AFFINITY=1 USE_OPENMP=1`?

**Comment by ccccdd** [comment] 2015-10-20 06:54
@PrajitR   I met the exact same problem as you did. Have you fixed it?

**Comment by ccccdd** [comment] 2015-10-20 12:34
@xianyi  I changed it to have 4 CPU cores. Now I have another problem using the flags NO_AFFINITY=1 USE_OPENMP=1:
![qq 20151020213250](https://cloud.githubusercontent.com/assets/15207024/10607125/5b8da17c-7772-11e5-94eb-bdf4f9f84a7b.png)

**Comment by martin-frbg** [comment] 2015-10-20 14:42
"Permission denied" is a local access policy problem - you probably did the previous build in that directory as a different user (as root by running "su").  It might make sense to open your own bug thread if your problem develops into something different. Also best run "make clean" before "make"
when you change the configuration to avoid creating an inconsistent mixture of code from different setups (which may well have been the original cause)

**Comment by ccccdd** [comment] 2015-10-20 15:27
I'm fix that  .when i put the virtual machine into a 4 nucleus from a nuclear.then use the make clean and make command .

发自我的 iPhone

**Comment by ccccdd** [comment] 2015-10-20 15:38
Thanks ,but when I use the other command  there has been a new problem 
sudo apt-get install git g++ python imagemagick cmake 
I'm sorry .now that the computer is not near.
It's too late .
send mail to you tomorrow 


发自我的 iPhone

**Comment by ccccdd** [comment] 2015-10-21 11:34
@martin-frbg  hi ,Thanks ,I'm trying to run the other command  there has been a new problem.
sudo apt-get install python imagemagick libopencv-core2.3 libopencv-highgui2.3
![qq 20151021203230](https://cloud.githubusercontent.com/assets/15207024/10635338/de6ffc1e-7832-11e5-977f-e5a2c7d1284e.png)
how to fix it?

**Comment by martin-frbg** [comment] 2015-10-21 12:27
Not sure what installation documentation you are trying to follow here, but at least it has nothing to do with openblas. Perhaps that list is older, and there is now a newer version of opencv on the ubuntu servers - I guess you could try if it finds "libopencv-core libopencv-highgui" without the version numbers.

**Comment by ccccdd** [comment] 2015-10-21 12:57
@martin-frbg  yes,i am Tried  sudo apt-get install python imagemagick libopencv-core libopencv-highgui                   without the version numbers
But still failed
![qq 20151021215722](https://cloud.githubusercontent.com/assets/15207024/10637117/b2b4772e-783e-11e5-8dde-9d8e60b2678b.png)
I do not know how to do it...

**Comment by martin-frbg** [comment] 2015-10-21 13:09
Try with version number 2.4 then, ask on some ubuntu or opencv forum if that does not work either ?

**Comment by ccccdd** [comment] 2015-10-21 13:43
ok，thanks .i will try…

发自我的 iPhone

**Comment by ccccdd** [comment] 2015-10-22 08:31
@martin-frbg   Tried with version number 2.4，it“s ok,thanks!
![qq 20151022173109](https://cloud.githubusercontent.com/assets/15207024/10660544/ac7dc6b8-78e2-11e5-9344-b770246ec6ee.png)

**Comment by martin-frbg** [comment] 2015-10-22 10:36
Great. And if I understand correctly, your original problem with building OpenBLAS is fixed as well (by using more than one core, and doing "make clean" before the "make") ? It seems all the others who had this problem never confirmed that it worked for them, so that this old bug report here could never be closed...

**Comment by xianyi** [comment] 2015-10-22 15:53
Could I close this issue?

**Closed** 2015-10-23 17:05 UTC
Labels: Support
