### ISSUE TITLE
build openblas with CMAKE GUI and MSVC 2019

### ISSUE THREAD

**Issue by jbensabat** [xianyi/OpenBLAS#3977] opened 2023-03-29 05:37 UTC
Hello 
I tried to build Openbals using CMAKE and MSVC for X64 
The configuration with CMAKE goes fine but when I try to build the library I get a number of errors 
(missing functions).
I know i can build the library under miniconda and CMAKE - i just wonder if someone has managed to build openblas under MSVC
best
jac

**Comment by martin-frbg** [comment] 2023-03-29 10:40
#2825 may be related, but in any case a pure MSVC build will be inferior due to using generic, relatively poorly optimized C sources instead of the cpu-specific assembly routines available to other compilers

**Comment by jbensabat** [comment] 2023-03-30 09:34
Hi 
I think that I managed to build  openblas with MSVC 
I want to run the test program utest but there is no documentation about the arguments that are to be fed (argc , argv)
could you provide an example just to see what I get when I run utest 
best

jac

**Comment by martin-frbg** [comment] 2023-03-30 09:45
openblas_utest is run without command line arguments, its output should look like
```
TEST 1/38 max:smax_zero [OK]
TEST 2/38 max:dmax_positive [OK]
...
TEST 37/38 fork:safety [OK]
TEST 38/38 fork:safety_after_fork_in_parent [OK]
```
not all these regression tests are executed in all configurations, so you will probably see a smaller total than 38, the important point is that what is there should not report anything other than "OK".

**Comment by jbensabat** [comment] 2023-03-30 09:52
hi 
I just ran as you suggested and indeed there were 34 tests which all reported "OK". so i guess the lib is ready to use 
thanks
jac

**Comment by martin-frbg** [comment] 2023-03-30 10:00
Ok, there are some more in-depth BLAS tests in the test and ctest folders (the BLAS1 tests with "1" in their name need no arguments, the others require the correspondingly named (first character for input type, number for BLAS rank) input files to be fed as STDIN. (Note also that if you just built 0.3.22, it is now known to have a serious bug in LAPACK function GETF2)

**Comment by jbensabat** [comment] 2023-03-30 12:14
OK thanks

**Comment by jbensabat** [comment] 2023-03-30 12:26
Hi I checked th ctest directory 
these projects (Example xccblat1) have mixed code (fortran and c) and they are not likely to compile as is 
there is a need to compile c and fortran in different work-spaces.
best
jac

**Comment by martin-frbg** [comment] 2023-03-30 12:38
Oh, right - lack of a Fortran compiler would be another argument against a pure MSVC build. (On the other hand, if you did not see C equivalents for the Fortran files there, chances are you are looking at an older release and thus not affected by the current problem(s?) with the latest. )

**Comment by jbensabat** [comment] 2023-03-30 12:49
hi 
this is not what I meant. I have a fortran compiler. But under MSVC you can't not mix within the same workspace fortran and c code. you can compile fortran separately and c separately and they combine binaries. 
in the ctest directory the project xccblat1 has two files: 
c_cblas1.c and c_cblat1.f 
the code in c_cblas1.c has interfaces for calling c functions from fortran. 
the fortran code has a main program.
so it seems that ctest has fortran programs calling c routines 
I have downloaded the last version of openblas (for sourceforge and github
best 
jac

**Comment by martin-frbg** [comment] 2023-03-30 13:06
In versions since 0.3.21, xccblat1 has an alternate source file c_cblat1c.c that replaces c_cblat1.f when building without a Fortran compiler, so at least in theory it should build.

**Comment by jbensabat** [comment] 2023-03-30 13:10
Hi 
I have seen that
the c programs have been translated from fortran to c using  f2c translator, which usually requires the f2c.lib file.
is it the case here too ?
best
jac

**Comment by jbensabat** [comment] 2023-03-30 13:34
with regard to ctest 
I replaced the file c_cblat1.f with c_cblat1.c just to check 
there are a number of missing functions for example ICAMAXTEST_ (both in the fortran and c versions)
I looked for a file containing such a function in the whole directory and I have not found it 
best 
jac

**Comment by martin-frbg** [comment] 2023-03-30 16:27
The CMakeLists.txt there is supposed to do that automatically , or is this not picked up by the gui ? The ...TEST_  functions are mapped by the header file cblas_test.h to the corresponding F77_... functions that are defined in the (original) C files.
(And yes, the Fortran files were translated with f2c, but using a special header and wrapper script so that the usual f2c support library is not needed)

**Closed as completed** 2023-05-14 09:29 UTC
Labels: Support
