### ISSUE TITLE
Test failure on MIPS

### ISSUE THREAD

**Issue by rekado** [xianyi/OpenBLAS#570] opened 2015-05-15 09:03 UTC
On mips64el OpenBLAS 0.2.13 fails its tests.

```
 Complex BLAS Test Program Results


 Test of subprogram number  1            ZDOTC 
                                    ----- PASS -----

 Test of subprogram number  2            ZDOTU 
                                    ----- PASS -----

 Test of subprogram number  3            ZAXPY 
                                    ----- PASS -----

 Test of subprogram number  4            ZCOPY 
                                    ----- PASS -----

 Test of subprogram number  5            ZSWAP 
                                    ----- PASS -----

 Test of subprogram number  6            DZNRM2
                                    ----- PASS -----

 Test of subprogram number  7            DZASUM
                                    ----- PASS -----

 Test of subprogram number  8            ZSCAL 
                                    ----- PASS -----

 Test of subprogram number  9            ZDSCAL
                                    ----- PASS -----

 Test of subprogram number 10            IZAMAX
                                    ----- PASS -----
rm -f ?BLAT2.SUMM
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat2 < ./sblat2.dat
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./dblat2 < ./dblat2.dat
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./cblat2 < ./cblat2.dat

Program received signal SIGILL: Illegal instruction.

Backtrace for this error:
#0  0x7732046F
bash: line 1:  5509 Illegal instruction     OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./cblat2 < ./cblat2.dat
Makefile:26: recipe for target 'level2' failed
make[1]: *** [level2] Error 132
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/nix-build-openblas-0.2.13.drv-0/xianyi-OpenBLAS-aceee4e/test'
Makefile:115: recipe for target 'tests' failed
make: *** [tests] Error 2
```

The full build logs can be found here: http://hydra.gnu.org/build/339144/nixlog/1/raw

**Comment by martin-frbg** [comment] 2015-05-15 11:07
Is there a reason why you did the test with 0.2.13, or could you rerun it with the current 0.2.14 (or even better, the current snapshot of the "develop" branch that will become 0.2.15) ? While I see nothing in the commit log specifically targetting the *blat2 functions, many changes went in since 0.2.13 was released five months ago and the core developers may not have continous access to every supported platform.

**Comment by xianyi** [comment] 2015-05-15 19:28
@rekado  , I cannot access a mips64 machine so far. I am not sure I can debug this error.

**Comment by rekado** [comment] 2015-05-16 06:48
> Is there a reason why you did the test with 0.2.13, or could you rerun it with the current 0.2.14

I don't have a mips64 machine, so I have to rely on what the build slave on hydra tells me.  I just updated the package recipe to version 0.2.14.  Unfortunately, the build fails when attempting to link stuff for the tests target.

Here's the full output:
http://hydra.gnu.org/build/459416/nixlog/1/raw

**Comment by jeromerobert** [comment] 2015-05-16 07:58
Unless I missed something (in dynamic.c) DYNAMIC_ARCH is not supported on this architecture. Did you set DYNAMIC_ARCH or was it automatically set by OpenBLAS ? Anyway I would try to unset it.

**Comment by rekado** [comment] 2015-05-19 13:52
Yes, I built it with `DYNAMIC_ARCH`.

If I disable it OpenBLAS will tune itself to the host, would it not?  I shall try this again.

**Comment by jeromerobert** [comment] 2015-05-19 15:24
From getarch.c and cpuid_mips.c I would say it will select the best available on the current computer, among SCICORTEX, LOONGSON3A and LONGSON3B, and build only for this one architecture. If it build for LONGSON3B I guess that your binary will not work for SCICORTEX.

**Comment by xianyi** [comment] 2015-05-19 19:18
Hi,

Only x86/x86_64 supports DYNAMIC_ARCH. We used some special loongson extended instructions for LOONGSON3A and LOONGSON3B targets. Thus, these binary cannot be run on standard MIPS 64.

**Comment by rekado** [comment] 2015-05-21 09:50
Even when I do not set DYNAMIC_ARCH on MIPS I get the test failure above.  Here's the tail of the latest failed build on MIPS: http://hydra.gnu.org/build/471777/nixlog/1/tail-reload

**Comment by martin-frbg** [comment] 2015-05-21 10:31
From the naming of your library in that log snippet it appears that your build was for the LOONGSON3A target now - which xianyi commented just above your post would try to use some instructions not available on MIPS64. I suspect you would have to try "make TARGET=SCICORTEX" if the choice is actually limited to the three mips targets jeromerobert listed (no idea if this target even makes sense on your machine) - else OpenBLAS would need another mips target like loongson without the loongson-specific extensions.

**Comment by rekado** [comment] 2015-07-23 09:48
When TARGET is set the test are not run by default.  Is this intentional?

**Comment by xianyi** [comment] 2015-07-24 23:27
@rekado , yes, it is by default.

**Comment by martin-frbg** [comment] 2018-03-20 14:00
Reviving this old issue, I find that the strmm and dtrmm tests fail (with the "less than half accurate" message) for mips64el SCICORTEX target at least with an emulated cpu (qemu). Can anybody confirm this ?

**Comment by martin-frbg** [comment] 2018-07-07 12:41
Replying to myself, this must have been the same problem as #1563, caused by a commit that has since been reverted. Closing now as #1672 has the log of a successful run of the blas and lapack tests on mips64el.

**Closed by martin-frbg** 2018-07-07 12:41 UTC
