### ISSUE TITLE
gbmv! segfaults for large matrices

### ISSUE THREAD

**Issue by dlfivefifty** [xianyi/OpenBLAS#1698] opened 2018-07-25 12:35 UTC
I'm getting the following issue calling `gbmv!` in Julia, that is only present when compiled with OpenBLAS:
```julia
julia> n = 100_000_000; A = randn(3,n); x = randn(n); y = similar(x); BLAS.gbmv!('N', n, 1, 1, 1.0, A, x, 0.0, y);
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] gbmv!(::Char, ::Int64, ::Int64, ::Int64, ::Float64, ::Array{Float64,2}, ::Array{Float64,1}, ::Float64, ::Array{Float64,1}) at /Users/solver/Projects/julia7/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/blas.jl:652
 [2] top-level scope at none:0

julia> n = 100_000_000; A = randn(3,n); x = randn(n); y = similar(x); BLAS.gbmv!('N', n, 1, 1, 1.0, A, x, 0.0, y);
Segmentation fault: 11
```
When compiled with Apple's system BLAS, the above examples work fine.

**Comment by martin-frbg** [comment] 2018-07-25 12:54
Which version of OpenBLAS is this ?

**Comment by dlfivefifty** [comment] 2018-07-25 12:56
According to `openblas.version` file in Julia v0.7-beta, it's 
```
OPENBLAS_BRANCH=v0.3.0
OPENBLAS_SHA1=939452ea9dcb57abdcc3f1278c6db668a4690465
```

**Comment by martin-frbg** [comment] 2018-07-25 13:24
Possibly PR #1389 (original issue #1089) was not sufficient. How many cores does your hardware have ?

**Comment by dlfivefifty** [comment] 2018-07-25 13:48
4 cores I think. It's a MacBook Pro 2017.

**Comment by martin-frbg** [comment] 2018-07-25 19:51
reproduced with a git clone of julia. gdb claims the action happens in dscal_kernel_8_zero called from dscal_k_HASWELL. (So pretty much the same signature as #1089 indeed).

**Comment by brada4** [comment] 2018-07-26 06:33
seems like osx now adds mprotect-ed guard pages around allocations to catch over/under flows.

I suspect https://github.com/xianyi/OpenBLAS/blob/25f2d25cfecf6cf850aa5b989f279e5023b6234b/driver/level2/gbmv_thread.c#L98 where I removed buffer, the padding-looking adjustment should actually go to x, (?) and code was wrong before and after (?)

**Comment by martin-frbg** [comment] 2018-07-26 08:29
Unlikely as that line is inside an `#ifdef TRANSA` that does not apply here. I suspect this is a different but related failure mode with range_n rather than range_m going out of bounds on the last thread of the set.

**Comment by brada4** [comment] 2018-07-26 20:55
Is L246 writing past end of queue? , same rationale as https://github.com/xianyi/OpenBLAS/commit/529bfc36ec444223ba7b49717ef2d7fa12445159 (but not 1:1 refecting to files there)
@dlfivefifty can you quickly check if adding 1 to queue size in https://github.com/xianyi/OpenBLAS/blob/25f2d25cfecf6cf850aa5b989f279e5023b6234b/driver/level2/gbmv_thread.c#L179 solves the issue?

**Comment by martin-frbg** [comment] 2018-07-26 22:45
Nope, does not help. (And interestingly it appears to be a random thread from the middle of the queue array that experiences the segfault. Valgrind is no use because of https://github.com/JuliaLang/julia/issues/27131 )

**Comment by brada4** [comment] 2018-07-27 08:21
work divider behaves somewhat counter-intuitive, in particular case 25(0) 25(0)1 25(0) 24(9)
I will try to plant same call in other scriptable BLAS consumer

**Comment by brada4** [comment] 2018-07-27 18:01
...Does not crash with single thread where crashes with multiple

**Comment by martin-frbg** [comment] 2018-07-27 18:24
Do you have a reproducer that does not need julia ?

**Comment by brada4** [comment] 2018-07-27 18:52
@martin-frbg should be identical to scipy dgbmv , but that is via cblas by preference. R exports it via R_ext.h, but no standard or popular module wraps it into scriptable resource.

**Comment by martin-frbg** [comment] 2018-07-29 14:58
Unfortunately building with -fsanitize=address appears to make the bug go away. (it reappears when running julia  from gdb, but address sanitizer does not provide any additional information in that context)

**Comment by martin-frbg** [comment] 2018-07-30 11:45
Hmm. Perhaps BUFFER_SIZE  as defined in common_x86_64.h _is_ actually too small here ?

**Comment by brada4** [comment] 2018-07-30 18:58
It points to threading threshold in interface/scal.c
Once that is exceeded there is a jump to unmapped area from place I could not find in assemblies.
```
   0x00007fffe528ecb9 <+201>:   mov    %rcx,%rdi
   0x00007fffe528ecbc <+204>:   lea    0x8(%rsp),%rsi
   0x00007fffe528ecc1 <+209>:   jp     0x7fffe528ed98 <dscal_k_PILEDRIVER+424>
   0x00007fffe528ecc7 <+215>:   jne    0x7fffe528ed98 <dscal_k_PILEDRIVER+424>
   0x00007fffe528eccd <+221>:   callq  0x7fffe528ead0 <- call to unmapped
   0x00007fffe528ecd2 <+226>:   movsd  0x8(%rsp),%xmm0 <- crash eip
   0x00007fffe528ecd8 <+232>:   movsd  (%rsp),%xmm1
   0x00007fffe528ecdd <+237>:   ucomisd %xmm1,%xmm0
```
I dont know if that is thread safety issue (in principle threading at this level should be single thread dscal?)

**Comment by martin-frbg** [comment] 2018-07-30 19:10
Not sure I understand your find - when scal is called _from gbmv_thread_, it gets passed an invalid buffer pointer ("y") already. (All the setup code in gbmv_thread.c seems to be concerned with partitioning a buffer that is apparently assumed to always be big enough. That is why I now suspect that setting BUFFER_SIZE to 64<<20 or 128<<20 (as seen in the ppc and ia64headers respectively) might help. I will not be able to test this before the next weekend unfortunately.

**Comment by martin-frbg** [comment] 2018-08-04 18:18
Increasing BUFFER_SIZE does not help. (Increasing the stack size limit does, same as in #1089)

**Comment by martin-frbg** [comment] 2018-09-01 17:06
~~Revisiting this with 0.3.3, for some weird reason I cannot reproduce this issue in a shell started from an X session, but it is still there when logged in without X (but with same ulimits set). Could this be another (non)alignment problem ? (Actually it is something about the (size of the) environment - works fine as a regular user or after a plain "su" from there, crashes with a login shell of the root user.
Ulimits appear to be the same in both settings, and there is no obvious difference in the paths or the
environment variables except that the regular user has more of both.)~~
Rebuilt julia for the generic target to get around the valgrind issue but still not wiser.

**Comment by martin-frbg** [comment] 2018-09-03 11:12
Some of the valgrind traces look as if Julia's garbage collector moved the work array while the OpenBLAS threads were trying to access it, but I cannot really make sense of it yet. What seems clear however is that this condition already existed with 0.2.13 (and probably much earlier, but trying older versions gets tedious as they lacked the symbol suffixes for interface64 builds.)

**Comment by martin-frbg** [comment] 2018-09-30 22:47
Revisiting this, it now looks to me as if this is a fundamental issue rather than a coding bug - each thread needs to allocate a memory range big enough to hold the entire matrix from within the "buffer" region that is defined by the BUFFER_SIZE constant in `common_<platform>.h`. It seems one would need to increase the default `32 << 20` in common_x86_64.h all the way to `1024UL << 20` to accomodate just 4 threads with the n=100_000_000 workload. (Perhaps there needs to be an upper limit on parallelization in at least some of the interface routines as well, where some already have lower bounds now ?)

**Comment by martin-frbg** [comment] 2018-12-30 19:22
Moving to next milestone as this is still unclear to me, could be similar in concept to bug #173

**Comment by martin-frbg** [comment] 2020-02-11 12:08
Made configurable in the build system for now to avoid having to hack common_x86_64.h.

**Comment by martin-frbg** [comment] 2020-12-11 22:13
closing as the original issue is fixed by increasing the default size and making it configurable - the requirement for this big buffer as such is a fundamental design "feature" that will need revisiting at some point

**Closed as completed by martin-frbg** 2020-12-11 22:13 UTC

**Comment by dlfivefifty** [comment] 2020-12-12 09:11
Segfaulting by design seems like a weird choice...

**Comment by martin-frbg** [comment] 2020-12-12 09:23
...from something like 20 years ago when computer memory was scarce and where it would have been the norm that users would configure the innards of the library for their particular workloads.

**Comment by dlfivefifty** [comment] 2020-12-12 09:33
An error saying “increase the default size” seems much more sensible

**Comment by martin-frbg** [comment] 2020-12-12 16:28
assuming an appropriate single location for such a check can be found (that does not cost performance during regular operation). Increasing the default to accomodate your case (and match what the various internal parameters would have required in the first place) has already led to certain misgivings in the python camp, so a more fundamental long-term resolution would certainly be desirable.
