### ISSUE TITLE
"fatal error: stdio.h: No such file or directory" when building for Android

### ISSUE THREAD

**Issue by tanayz** [xianyi/OpenBLAS#953] opened 2016-08-30 05:30 UTC
Mine is a Ubuntu 14.04 system.I've downloaded ndk r12b and unzipped it and also cloned the latest OpenBLAS.
Then I created following entries in my ~/.bashrc file

```
export NDK_ROOT=/home/tanay/src/android-ndk-r12b
export ANDROID_NDK_ROOT=/home/tanay/src/android-ndk-r12b
export PATH=/home/tanay/src/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
export CC=arm-linux-androideabi-gcc
export CXX=arm-linux-androideabi-g++
export TOOLCHAIN=/home/tanay/src/android-ndk-r12b/toolchains
export ANDROID_TOOL_CHAIN=/home/tanay/src/android-ndk-r12b/toolchains
```

After than I ran `python make_standalone_toolchain.py --arch arm64` with success

Then I ran following command inside OpenBLAS directory 
`make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 
`I got the below error after that
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
make[1]: Entering directory /home/tanay/src/OpenBLAS/interface' arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE -UCOMPLEX -c axpy.c -o saxpy.o arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=sswap -DASMFNAME=sswap_ -DNAME=sswap_ -DCNAME=sswap -DCHAR_NAME=\"sswap_\" -DCHAR_CNAME=\"sswap\" -DNO_AFFINITY -I.. -I. -UDOUBLE -UCOMPLEX -c swap.c -o sswap.o arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=scopy -DASMFNAME=scopy_ -DNAME=scopy_ -DCNAME=scopy -DCHAR_NAME=\"scopy_\" -DCHAR_CNAME=\"scopy\" -DNO_AFFINITY -I.. -I. -UDOUBLE -UCOMPLEX -c copy.c -o scopy.o arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=sscal -DASMFNAME=sscal_ -DNAME=sscal_ -DCNAME=sscal -DCHAR_NAME=\"sscal_\" -DCHAR_CNAME=\"sscal\" -DNO_AFFINITY -I.. -I. -UDOUBLE -UCOMPLEX -c scal.c -o sscal.o axpy.c:39:19: fatal error: stdio.h: No such file or directory #include <stdio.h> ^ compilation terminated. make[1]: **\* [saxpy.o] Error 1 make[1]: **\* Waiting for unfinished jobs.... copy.c:39:19: fatal error: stdio.h: No such file or directory #include <stdio.h> ^ compilation terminated. make[1]: **\* [scopy.o] Error 1 swap.c:39:19: fatal error: stdio.h: No such file or directory #include <stdio.h> ^ compilation terminated. scal.c:39:19: fatal error: stdio.h: No such file or directory #include <stdio.h> ^ compilation terminated. make[1]: **\* [sswap.o] Error 1 make[1]: **\* [sscal.o] Error 1 make[1]: Leaving directory/home/tanay/src/OpenBLAS/interface'
make: **\* [libs] Error 1

Any suggestion will be appreciated.

**Comment by martin-frbg** [comment] 2016-08-30 20:54
Seems to be the same (unresolved) issue as #928 - do you see a stdio.h anywhere in your toolchain ?
(This Q&A on stackoverflow could be related, although it was for an older version of the ndk:
http://stackoverflow.com/questions/14307611/problems-compiling-object-using-arm-linux-androideabi-gcc
 perhaps you just are missing some symbolic links due to the way you extracted the ndk: see last entry on that page)

**Comment by martin-frbg** [comment] 2016-08-30 21:14
Only just noticed that this appears to be a duplicate of your #952 and you already resolved the issue ?
(In that case, could you please close this one here as well ?)

**Comment by tanayz** [comment] 2016-08-31 13:58
I closed #952 wrongly as the issue remain unsolved even after making the toolchain using that command.The link you have given suggest me the same commands I've attempted,i.e
```
export PATH=/home/tanay/src/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1
```
yet I got that stdio.h error.

**Comment by martin-frbg** [comment] 2016-08-31 19:22
I see. Now do you have the file stdio.h anywhere under your toolchain path ? (And as I read it, the last entry in the stackoverflow link suggested that it could be a problem with how you unpacked the ndk - if you used the default file manager (whatever that is on Ubuntu) apparently that one does not create links while tar does)

**Comment by vpatilvasu** [comment] 2016-10-06 20:23
I am facing same issue. Is there any solution?

I downloaded android-ndk-r13-linux-x86_64.zip and unzipped on Ubuntu using "unzip -a android-ndk-r13-linux-x86_64.zip" command and I still get same error, i.e. "stdio.h: No such file or directory"

**Comment by martin-frbg** [comment] 2016-10-06 20:49
A script file for building OpenBLAS for various Android platforms was recently posted in issue #963 (judging from #919, the exact problem in your case could be an invalid or missing sysroot specification in your CFLAGS ?)

**Comment by vpatilvasu** [comment] 2016-10-06 21:50
Thanks. I eventually stumbled upon that script and it works. Thanks.

**Comment by martin-frbg** [comment] 2016-10-13 09:04
@tanayz does the compile script from #963 fix your problem as well (so that this issue can be closed) ?

**Closed** 2016-12-23 11:43 UTC

**Comment by phiresky** [comment] 2017-10-25 15:47
I had the same problem. For me, the solution was to add `CFLAGS=--sysroot=$NDK/platforms/android-16/arch-arm` to the make arguments from the [Wiki article](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android), as mentioned in [the script](https://github.com/xianyi/OpenBLAS/issues/963#issuecomment-247643410) @martin-frbg mentioned.

Example: `make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 CFLAGS=--sysroot=$NDK/platforms/android-16/arch-arm libs`


This information should probably be added to the Wiki article.

(I came here via google)

Edit: Actually, I just saw it is already in the wiki, under the `clang` section. Then maybe the clang section should be moved to the top as the gcc compiler is gone/deprecated now.

**Comment by quickwritereader** [comment] 2017-10-25 15:55
that script comment is a bit outdated. Actually I was using android-9 abi for armv7 but that was for old. Afaik someone forked from my script and has script which consider softfp too. You could give a try using clang. Check my git for that script and PR your own fixed one if it worked. Thanks

**Comment by goodzhangbobo** [comment] 2021-07-18 12:58
Mine is ok, like this:

# Set path to ndk-bundle
export NDK_BUNDLE_DIR=/home/user/soft/android-ndk-r21/

# Export PATH to contain directories of clang and aarch64-linux-android-* utilities
export PATH=${NDK_BUNDLE_DIR}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/:${NDK_BUNDLE_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

# Setup LDFLAGS so that loader can find libgcc and pass -lm for sqrt
export LDFLAGS="-L${NDK_BUNDLE_DIR}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x -lm"

# Setup the clang cross compile options
export CLANG_FLAGS="-target aarch64-linux-android --sysroot ${NDK_BUNDLE_DIR}/platforms/android-29/arch-arm64 -gcc-toolchain ${NDK_BUNDLE_DIR}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/ -I/home/user/soft/android-ndk-r21/sysroot/usr/include  -I/home/user/soft/android-ndk-r21/sysroot/usr/include/aarch64-linux-android"

# Compile
make TARGET=ARMV8 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc -j4
