### ISSUE TITLE
[cmake] The obtained core name is not uppercase

### ISSUE THREAD

**Issue by JackBoosY** [xianyi/OpenBLAS#3372] opened 2021-09-09 06:16 UTC
Hi, I'm vcpkg maintainer.
Today we received an issue about building openblas on Linux https://github.com/microsoft/vcpkg/issues/20030.
When configuring cmake, the core name obtained by calling `getarch` is `sandybridge` instead of `SANDYBRIDGE`, which leads to the failure of querying the corresponding file `KERNEL.sandybridge` in Linux (the file name does not match).
After digging into the code, I still don’t know why the core is not uppercase.

Any ideas?

**Comment by martin-frbg** [comment] 2021-09-09 20:56
Sure that this is a pure Linux setup, and not e.g something that would mangle line endings from `\n` to `\r\n` or vice versa ? I notice that the LIBCORE entry (used for naming the library) is empty as well. Where normally it should have read `CORE=SANDYBRIDGE LIBCORE=sandybridge` you have `CORE=sandybridge LIBCORE=(NULL)` and getarch is not able to return _that_, so most likely something threw off the reading frame in ParseGetArchVars  (cmake/utils.cmake)

**Comment by martin-frbg** [comment] 2021-09-12 17:32
Another curious aspect of that build log is that AVX512VL capability was detected, which does not really make sense with Sandybridge. Is this some kind of VM setup ?

**Comment by martin-frbg** [comment] 2021-09-12 18:02
Hmm - in an earlier ticket by the same person elsewhere, the(?) hardware was identified as a ThinkPad X1Gen9,which features a Tiger Lake cpu.
There was a copy-paste bug affecting Tiger Lake identification by getarch which only got fixed on July 10 through #3299 (released with 0.3.16).
So if the vcpkg package in question is/was based on 0.3.15 this might explain the problem.

**Comment by martin-frbg** [comment] 2021-09-12 18:04
duplicate of #3298

**Comment by JackBoosY** [comment] 2021-09-13 03:11
I will take a look at that.

**Closed as completed** 2021-09-19 19:00 UTC
