### ISSUE TITLE
Testsuite failures on PowerPC and System Z

### ISSUE THREAD

**Issue by svillemot** [xianyi/OpenBLAS#4633] opened 2024-04-13 09:14 UTC
I uploaded version 0.3.27 to Debian and I get test failures:
– on PowerPC (ppc64): https://buildd.debian.org/status/fetch.php?pkg=openblas&arch=ppc64&ver=0.3.27%2Bds-1&stamp=1712940290&raw=0
– on System Z (s390x): https://buildd.debian.org/status/fetch.php?pkg=openblas&arch=s390x&ver=0.3.27%2Bds-1&stamp=1712939311&raw=0

Note that these two architectures are big endian (while the testsuite passes on all little endian architectures), so this could be an endianness issue.

**Comment by martin-frbg** [comment] 2024-04-13 09:23
yes this looks like an endianness issue with some of the new tests for the BLAS extensions

**Comment by martin-frbg** [comment] 2024-04-14 21:54
haven't had time to look into this, but the failures appear to be all of the "wrong or no error raised" type, and the corresponding code is all in the respective interfaces ( and fairly trivial C comparisons, unlikely to be affected by endianness)

**Comment by martin-frbg** [comment] 2024-04-18 08:23
Not reproduced on AIX, and I cannot figure out from your logs what configurations are failing for you. I do note that all reported failures are in argument validity checks that require a special version of the XERBLA routine to overload the regular one. Also not seen in CI (Z14/s390x, OSUOSL).

**Comment by martin-frbg** [comment] 2024-04-22 16:00
Not reproduced in QEMU emulating POWER9 with the current Adelie Linux live image for ppc64 (which comes with gcc8)

**Comment by martin-frbg** [comment] 2024-04-24 14:05
Also not reproduced in the same QEMU setup with the current Debian 12 for ppc64 (gcc 13.2). Unfortunately I do not have any real ppc64 hardware running Linux available for testing (AFAIK). 
I'm inclined to close this as a transient build problem in your environment - in any case it seems extremely unlikely to be an actual bug in the library (for the reasons mentioned above).

**Comment by svillemot** [comment] 2024-04-28 14:14
I realize that the problem only manifests with 64-bit indexing, i.e. with `INTERFACE64=1`. Did you try such a build?

More precisely, the full list of build options that trigger the failure on `s390x` is:
```
NO_LAPACKE=1 NO_AFFINITY=1 NO_WARMUP=1 CFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/home/sebastien/openblas-0.3.27+ds=. -fstack-protector-strong -Wformat -Werror=format-security" FFLAGS="-g -O2 -ffile-prefix-map=/home/sebastien/openblas-0.3.27+ds=. -fstack-protector-strong" COMMON_OPT= MAKE_NB_JOBS=2 NUM_THREADS=128 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 TARGET=GENERIC USE_THREAD=1 USE_OPENMP=0 INTERFACE64=1 LIBPREFIX=libopenblas64 FCOMMON_OPT='-frecursive -fdefault-integer-8'```

**Comment by martin-frbg** [comment] 2024-04-29 14:42
Ah indeed, thanks. Reproduced and traced to a simple argument casting error in the replacement xerbla used by that new testsuite.

**Closed as completed** 2024-04-29 15:23 UTC

**Comment by svillemot** [comment] 2024-04-29 20:31
Thanks for the fix! I applied it to the Debian package and it now compiles on s390x and ppc64 archs.
