### ISSUE TITLE
Segmentation fault on aarch64

### ISSUE THREAD

**Issue by albap** [xianyi/OpenBLAS#956] opened 2016-09-05 15:36 UTC
Alpine had to disable this library on aarch64 because of segfault.
http://git.alpinelinux.org/cgit/aports/commit/?id=aa080bf0e54b0974069abe9b8acb4151a3c72a80
cc @clandmeter

**Comment by brada4** [comment] 2016-09-08 18:22
Error 139 means compiler crashed (probably with coredump).
You can repeat last command (gfortran) to no good under gdb, valgrind and whatever debugger you imagine.

**Comment by martin-frbg** [comment] 2016-09-08 19:28
Giving this the benefit of doubt - _if_ a single line is missing from the log it could also mean that the automatic post-build test of sblat2 failed. In any case I guess much more context will be needed - what version of gcc, what kind of system was it run on (is it actual aarch64 hardware or just an emulator ?), what if any build options were set... I know nothing of alpine linux, but I trust a serious distribution will not blindly run "make" on random projects and drop any that  do not survive the process ?

**Comment by albap** [comment] 2016-09-09 11:32
I just started using alpine recently, so I'm not sure about everything.
For once, alpine uses musl instead of glibc.
I will cc @ncopa to help with better answers. Also @jirutka because he has packages that depend on openblas so he should be interested in helping.

> what version of gcc

gcc version 6.2.0

> is it actual aarch64 hardware or just an emulator

I think it's an R120-P30, but I'm not sure.

> what if any build options were set

I think so.
http://git.alpinelinux.org/cgit/aports/tree/community/openblas/APKBUILD

> I know nothing of alpine linux, but I trust a serious distribution will not blindly run "make" on random projects and drop any that do not survive the process

I agree.
This was a sad decision.

**Comment by martin-frbg** [comment] 2016-09-09 12:02
So from the APKBUILD it appears that the build is done with 
make TARGET=ARMV8 DYNAMIC_ARCH=0 USE_OPENMP=0 NO_LAPACK=0 MAJOR_VERSION=3 NO_AFFINITY=1 (not sure if the reason for USE_OPENMP=0 is still valid - citing an old gcc bug report
that apparently has not been acted upon, whereas much discussion and patching went on in #294, seemingly resulting in fixed behaviour. There is unconfirmed #455 but the reporter stopped responding)

Primarily I think what is needed now is clarification if the segfault happened during the gfortran compile of test case zblat2 (in which case it would not be a flaw in OpenBLAS, but rather an internal compiler error for the GCC folks to look at, and alpine should consider using a different GCC release). This is what the part of the compile log in your original link is strongly suggesting.
Only if there was an inadvertent deletion of a line between the gfortran call and the "Program received signal SIGSEGV" line, the problem might possibly be with OpenBLAS  (or complex number support in musl)...

**Comment by clandmeter** [comment] 2016-09-09 13:04
This issue happens when openblas with ILP64 is running test:

OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat1

This seems to be a regression in the latest version of openblas. I have reverted to previous version and it builds just fine.

**Comment by martin-frbg** [comment] 2016-09-09 13:43
Thanks for following up. If 0.2.18 works for you perhaps try undoing the changes to kernel/arm64/copy.S from 7878248 (part of PR924 by @ashwinyes, merged as 84952ee on July 14) - but this is just a really wild guess based on my limited understanding of what sblat1 tests. 
Could you run gdb on the failing sblat1 to get an indication of where it crashes ?

**Comment by clandmeter** [comment] 2016-09-09 16:02
that doesnt seem to fix it.
I tried gdb, but im probably missing debug symbols of some of the deps. 
Maybe I can generate a trace later this week/nextweek.

**Comment by brada4** [comment] 2016-09-09 17:39
No need for GDB yet
make --debug=j (assuming GNU make if that is available)
And tel which command crashes first.

**Comment by ashwinyes** [comment] 2016-09-09 18:06
kernel/arm64/copy.S  changes are done for target CORTEXA57. 

The issue here seems to be seen when building for ARMV8 which still uses the generic C implementations. 

@clandmeter I see that the compiler used is GCC 6.2.0 which is very recently released. Is it possible to try with an older version of GCC ?

I tried the OpenBLAS develop branch tip with GCC 4.8.4 and everything works fine.

**Comment by clandmeter** [comment] 2016-09-10 09:49
@ashwinyes did you build it on native aarch64 hardware?

Our x86* builders build openblas just fine with gcc 6.2

**Comment by clandmeter** [comment] 2016-09-10 09:58
make debug last 1k lines http://sprunge.us/fEfA

if you need the full log ill have to upload it somwhere because of filesize.

**Comment by brada4** [comment] 2016-09-10 16:35
Please do a serialized build (i.e 1 compiler running at a time) only logging commands that make is running. It is necessary to drill down issue to either gfortran or openblas test failing.
$ make --debug=j MAKE_BB_JOBS=1 <your flags here>
And find the +/- 100 lines from 'Error 139', it did not get in your output somehow.

**Comment by clandmeter** [comment] 2016-09-10 21:49
http://sprunge.us/bAMg

**Comment by ashwinyes** [comment] 2016-09-11 03:27
@clandmeter Thanks for the logs.

I tried on native aarch64 hardware. I tried with GCC 6.2 and GCC 5.4 as well on Ubuntu 16.04. I couldn't reproduce the above issue.

You mentioned that "This issue happens when openblas with ILP64 is running test:" . I have limited understanding of ILP64 and I am not familiar with ILP64 for aarch64. Could you please let me know how you are enabling ILP64 for the aarch64 build?? 

Thanks

**Comment by ashwinyes** [comment] 2016-09-11 03:56
Update:

I missed the "INTERFACE64=1 SYMBOLSUFFIX=64_" options previously. With these options I am able to reproduce the issue with GCC 6.2 and GCC 5.4.

The build is failing at the blas tests. All blas tests are failing with the segfault. Let me go through the failure. I will  give an update on the issue.

**Comment by ashwinyes** [comment] 2016-09-11 04:58
Looks like OpenBLAS never supported ILP64 on Aarch64 (Not sure whether Aarch64 even supports ILP64). The tests are failing in OpenBLAS versions v0.2.18 and v0.2.19.

The reason that the build failure arises between v0.2.18 and v0.2.19 is because the build and run of tests is enabled in the Makefile by commit 3d50ccdc0de9b0756d4bdc63e196403332d68570 by @rndfax . 

For now, the best thing to do would be to **disable the build of OpenBLAS with ILP64 enabled in the Alpine Linux Build System**.

Thanks

**Comment by rndfax** [comment] 2016-09-13 10:19
11.09.2016, 07:58, "Ashwin Sekhar T K" <notifications@github.com>:  because the build and run of tests is enabled in the Makefile by commit 3d50ccd by @rndfax . But commit message says: allow building tests when CROSS compiling but don't run themThis commit only enables building tests but not running IF someone is doing cross compiling.

**Comment by martin-frbg** [comment] 2016-09-13 10:41
Seems to me that your commit also dropped an #ifndef TARGET condition from the Makefile which would have inhibited the tests in this specific case ? (And I guess ashwinyes did not mean this as criticism but as an explanation why the ILP64 incompatibility was not uncovered earlier - I guess if the tests crash, the associated library functions would not fare better in real life code ?)

**Comment by ashwinyes** [comment] 2016-09-13 10:55
@rndfax It was not meant as criticism but as an explanation for the issue :)

And your commit affect native builds also when TARGET is given explicitly. As in the current case, the tests starts running for native builds with TARGET=ARMV8. But i dont think any change is required in your commit. 

@clandmeter. I think we can close this issue. GCC also says that only LP64 and ILP32 are supported in AArch64

**Comment by clandmeter** [comment] 2016-09-13 12:51
please close, thx.

**Closed** 2016-09-14 16:57 UTC
