### ISSUE TITLE
RFC: remove support for Russian Elbrus processor

### ISSUE THREAD

**Issue by rubicon1042** [xianyi/OpenBLAS#3551] opened 2022-03-02 01:32 UTC
Support for Russian Elbrus E2000 family was very recently added in https://github.com/xianyi/OpenBLAS/pull/3518.

Due to Russian military aggression against Ukraine, both Intel and AMD have suspended processor sales to Russia: https://www.tomshardware.com/news/intel-amd-nvidia-tsmc-russia-stop-chip-sales-ukraine-sanction

The Elbrus processor is a so-called homegrown processor, with the primary use case of circumventing sanctions such as above. The processor is / will be used in Russian military equipment, intelligence service, and other branches of the Russian government.

Linear algebra operations provided by OpenBLAS can be and are used within weapons (eg: machine learning, pattern recognition, computer vision), such as those used by the Russian military, either now or in the future.

Continued support for the Elbrus processor within OpenBLAS is tantamount to supporting the Putin regime and its military aggression.

CC: @ArturFormella @BushidoUK @cert-orangecyberdefense @gakowalski @AndrewStetsenko

**Comment by martin-frbg** [comment] 2022-03-02 06:57
I have been thinking about that myself, but it would be nothing but an empty political gesture - the Elbrus "support" as added by #3518 before the Russian invasion of Ukraine is equivalent to building with TARGET=GENERIC, and already existed as a patch for the ALTLinux distribution.

**Comment by conradsnicta** [comment] 2022-03-02 14:34
I support this. No matter what the underlying technical details are, removing this code would contribute to the overall message that actions have consequences; military aggression is definitely not okay. It also sends a signal of support to Ukrainians.

Short of a military intervention by NATO (or a suitably beefy military coalition), the only way to remove the Russian psycho from power is for the Russian people to remove him [1]. To do that, they must know the pain that comes with having him as their ruler and not just believing the fantasies that their state TV propaganda blares out [2]. Removing support for Elbrus from OpenBLAS is a small but useful step towards that.

[1] NY Times has a short but potent opinion piece on 3 possible outcomes of the war: https://www.nytimes.com/2022/03/01/opinion/ukraine-russia-putin.html  
[2] BBC has a story on how the war is "reported" on Russian TV:  https://www.bbc.com/news/world-europe-60571737

**Comment by zoq** [comment] 2022-03-03 03:21
I agree with @conradsnicta removing the code has probably no huge effect but sends a signal of support.

**Comment by zhangn1985** [comment] 2022-03-03 14:13
show your real name @rubicon1042 .

**Comment by FCLC** [comment] 2022-03-03 15:25
### Personal pinion re: support 

> Continued support for the Elbrus processor within OpenBLAS is tantamount to supporting the Putin regime and its military aggression.

As @martin-frbg stated, this doesn't truly achieve anything outside of a superfluous gesture that politicize a tool used by academia and hobbyists the world over. 

#3553 Achieves what you're requesting, but the code base already has a version that has support with the patch included. 

Said version could be forked if someone wanted to be able to use TARGET="foo". 

Otherwise, the patch itself could be applied to an upstream release without significant work. 

Whilst I agree that sending a message is important, FOSS (in my opinion) has always been about free and open collaboration.  Extinguishing the contribution of developers simply because of where they're from goes against this ethos. 

There's also the license:https://github.com/xianyi/OpenBLAS/blob/develop/LICENSE

Whilst I appreciate the want to deny any chance of a library/codebase being used to perpetuate a conflict, limiting and cheery picking which architecture gets support based on political boundaries seems like a poor approach to take. There's also the reality that every codebase that is FOSS and has ever been published can be used by those with nefarious intent. 

I don't want to construct some sort of fallacy based on taking things to the extreme, but would you also be asking the kernel, HYPRE, PETSC, GLIBC, GCC, LLVM, etc. to remove support as soon as their is a political conflict? 

This specific code base is supported by developers in mainland China, Nato member nations and Russia amongst developers from other countries in the world. 

Repeating myself from above but in a different context, forking the code base whenever a political dispute arises between those groups sounds like a poor approach to take.  

I'm personally not in favor of removing support. It achieves nothing, goes against the ethos of FOSS and sets the stage for problematic precedent down the line.  


### Personal opinion re: conflict

My personal take on the matter is that what's going on right now is beyond moronic and being caused by an autocrat who took a gamble on a way to hold on to power, desperately trying to shore up domestic support, and it backfiring miserably. Choosing to support a side of a conflict is a deeply personal choice. 

I'm personally supporting Ukraine in the ways that I can from the other side of the planet. But separating the personal contribution and the long term health of the project seems of greater importance to me.

**Comment by martin-frbg** [comment] 2022-03-03 16:56
> This specific code base is supported by developers in mainland China, Nato member nations and Russia amongst developers from other countries in the world.

are you referring to OpenBLAS here, or does Elbrus have a significant user/developer base outside Russia ? (Note this is about the specific, purportedly military hardware, not about the nationality of the persons involved) 

I have looked for possible precedents but have found none - looks like everything Elbrus-specific is still maintained as separate
patchsets or forks. (Actually the only merged patch I found was in the google benchmark library, tangentially related to an as-yet unreviewed LLVM PR).

**Comment by JPenuchot** [comment] 2022-03-03 16:57
I'm sorry but FOSS ethos don't mean anything if the authors aren't free to remove support for hardware that's used exclusively by an army that targets civilians with cluster ammo (in my opinion 🙃).

**Comment by JPenuchot** [comment] 2022-03-03 17:03
Rallying against Nvidia for being unsupportive towards OSS doesn't sound as hard as taking side against war criminals apparently.

**Comment by craigbarnes** [comment] 2022-03-03 17:43
Roll up, roll up, come and voice your political opinions on a software issue tracker (self awareness optional).

**Comment by JPenuchot** [comment] 2022-03-03 17:43
Roll up roll up, just pretend software isn't political at all.

**Comment by aphorise** [comment] 2022-03-03 19:10
> ... processor is / will be used in Russian military equipment, intelligence service, and other branches of the Russian government.

By this logic - we'd do well to self exclude all other processors as well then since there are few architectures that are not actually used for the these purposes or in these domains by any of the evil doers of all regimes globally.

There was also something I read once about "the ends don't justify the means" - and so inversely "any means" as opposition to some evil events can be equally as unjust and sweeping in generalisation.

**Comment by JPenuchot** [comment] 2022-03-03 19:17
> By this logic - we'd do well to self exclude all other processors as well then since there are few architectures that are not actually used for the these purposes or in these domains by any of the evil doers of all regimes globally.

Except Elbrus chips aren't used by anyone else than the Russian military, as opposed to any other processor.

**Comment by aphorise** [comment] 2022-03-03 19:23
@JPenuchot how can you be so absolute in that statement? on what proof? - is Russian accedmia co-equal to Military? What about commerce?

Also is malicious technology with some civil befits an acceptable and tolerable evil? - that's the moral scale here?

**Comment by FCLC** [comment] 2022-03-03 19:31
> are you referring to OpenBLAS here, or does Elbrus have a significant user/developer base outside Russia ? (Note this is about the specific, purportedly military hardware, not about the nationality of the persons involved)

I'm referring to OpenBLAS as a whole.

As far as I'm aware, its main purpose has been to remove and replace the cryptographic engine from American vendors to replace them with their own, especially after the whole elyptic curve backdoor/mess a few years back. Similar in concept to some x86 chips from Hygon in their Dhyana series of Zen based chips or the Zhaoxin KaiXian series chips for the Chinese mainland market. 

As for Elbrus, per the original poster it will be used as a home grown alternative to intel/amd x86_64 processors,  only some of which will end up in military hardware. 

Regardless of the ongoing conflict, we would have seen a diversification of x86 over time IMO. 


Addressing some other comments:

Unless the plan is to somehow engineer a process (excuse the pun, it isn't intended) to make the usage of these libraries in offensive contexts impossible, I don't exactly how this actually achieves anything. 

The chips with x86 compatibility themselves have been around since 2008 from what I could find with a few minutes of googling/searching with DuckDuckGo. It seems to me that support itself in other systems have been around for a while, it just so happens that a specific alias for Elberus didn't exist. 


@JPenuchot for the FOSS ethos, please don't change my words. The choice absolutely *does* belong to the developers. Were it solely my choice, I'd say removing support for hardware used in commercial, academic, personal, government and yes, armed forces, is counter productive. But it isn't only my choice (heck, my patch series for fp16 hasn't been pushed yet because of other commitments)

Tempers/angst etc. are running high, but that shouldn't be an excuse to not stop and think through. 

If you chose to make personal contributions that so happens to gate around certain flags, I'd find that distasteful, but that would be your choice as a developer and contributor. If such a PR would be accepted is another matter...

**Comment by FCLC** [comment] 2022-03-03 19:32
Apologies for some of the above being long winded. "If I had more time I would have written a shorter letter"

**Comment by craigbarnes** [comment] 2022-03-03 19:52
> Apologies for some of the above being long winded.

No worries. I didn't read it anyway.

**Comment by evert-mouw** [comment] 2022-03-03 22:05
Lots of comments on Phoronix on this issue. Also a small survey:
https://twitter.com/phoronix/status/1499385557956366341

Seems like most folks don't want to mix open source development with politics and virtue signaling.

**Comment by orbea** [comment] 2022-03-03 22:48
> Seems like most folks don't want to mix open source development with politics and virtue signaling.

Its insulting, regardless who is right or wrong striking out at random Russians is not going to make it better.

**Comment by craigbarnes** [comment] 2022-03-03 22:56
> ... striking out at random Russians is not going to make it better.

@orbea The account that created this issue is 2 days old and has no other activity. That should be all anyone needs to know.

> ... just pretend software isn't political at all.

@JPenuchot That's not an argument. Eating breakfast can be made political if you reach far enough.

**Comment by lilyanatia** [comment] 2022-03-03 22:58
> Its insulting, regardless who is right or wrong striking out at random Russians is not going to make it better.

I've actually looked into trying to get a system with one of those CPUs before, and the only way I could find to do it was buying Russian _military_ hardware. there doesn't seem to be any non-military Elbrus hardware available, at least outside of Russia. this isn't about random Russians, it's about the Russian _military_.

explicitly supporting _military_ hardware that has _no legitimate civilian use_ is a political statement.

**Comment by aphorise** [comment] 2022-03-03 23:44
There's a lot of random speculations and emotions without any substance or meaningful reference beyond hear-say; also fallacies such as: "*I haven't seen this CPU but I know it's military use only.*" :confused: 

No [mention or understanding of MCST](https://en.wikipedia.org/wiki/MCST) and a [simple search of academic journals](https://link.springer.com/chapter/10.1007/978-3-030-05807-4_46) clearly demonstrates that Elbrus has never been just in military applications within Russia.

**Comment by pasichnichenko** [comment] 2022-03-04 00:08
I was curious quite long time about to work with Elbrus, to get some real experiense, and I can contribute real expririence. Before this I had already developed embeded systems with Linux and LynxOS, build SBC with ARM at91rm9200  CPU, hacked a lot of desktop and server systems, i.e. I am not novice. And then I wanted to try something with Elbrus....

My strong opinion: support for Elbrus must be removed and never integrated until Elbrus/Baikal will become really accessible for everyone, not just militaries.

I made my own researches recently and years ago, when I was trying few times to get prices and to purchase any Elbrus or Baikal board or complete desktop systems in russia. This is impossible, totally. Absolutely. Out of stock or seller is not working with private persons. All my attempts to ask people involved in the project where I could buy this always lead to PR bullshit or redirects to a sites where I have checked already and where it is impossible to buy. I never saw/met/heard of any real private person owning Elbrus board.

NO ONE PRIVATE PHYSICAL PERSON CAN BUY ELBRUS.

Elbrus is completely military and closed project despite it's recent PRs. Documentation is incomplete in many places and attempts to get more detailed docs leads to requirement to sign an NDA and/or pay money.
Elbrus is available only for companies and only ater signing NDA with russian authorities (military one). No other possibillities.
Elbrus is produced in negligible volumes and doesn't play any real role in anything.
Elbrus It is just a matter of PR for satisfying the personal ambitions of a small group of people.
If you will check whole history of this project over the whole it's life no one real system was ever made/produced/designed/released for public society. PR bullshit or few experimental laboratory samples.

**Elbrus support MUST BE REMOVED.**

And all above mentioned  is not yet accounting war caused by russia in Ukraine.

Afer war that happenned any Elbrus support must be removed unconditionally.

**Comment by Doomsdayrs** [comment] 2022-03-04 00:10
Maintainers, Please close this issue.

This seems to be some work done by a troll attempting to create controversy. It even appeared on Phoronix as news. 

Disclaimer, I do not hold any political opinion on this matter, and do not associate with the war on any side. Do not affiliate me with any political stances, slander is unlawful.

**Comment by Doomsdayrs** [comment] 2022-03-04 00:13
I picked out two random accounts from this thread, and it is clear they are inactive accounts that have no real dealing with FOSS.

**Comment by Doomsdayrs** [comment] 2022-03-04 00:14
As I will state, this conversation is not between developers but by third parties trying to defend their side and / or vent their frustrations.

**Comment by craigbarnes** [comment] 2022-03-04 00:20
> I've actually looked into trying to get a system with one of those CPUs before, and the only way I could find to do it was buying Russian military hardware

Totally believable story... :rofl: :laughing:

**Comment by pasichnichenko** [comment] 2022-03-04 00:25
I was trying even before war started, tried one year ago and two years ago, called by phone and talking with seller and no result. It is impossible to get any real system. I was even ready to sign NDA, but they simply do not sell to private persons. Why support something you will never get??

**Comment by Doomsdayrs** [comment] 2022-03-04 00:26
@martin-frbg 

I hope you can see my stance on this matter and close this issue. And possibly lock this too.

This is going to become a toxic fight pool very soon with how third parties are going to jump on soon.

**Comment by pasichnichenko** [comment] 2022-03-04 00:34
> 
> This is going to become a toxic fight pool very soon with how third parties are going to jump on soon.

You can close this issue, it's ok, But I just added my feedback about real practical experience with this russian bullshit.

**Comment by Adi1200** [comment] 2022-03-04 00:35
I was here

**Comment by xianyi** [comment] 2022-03-04 00:48
I am going to close this issue. Please discuss the technical problems.

**Closed as completed by xianyi** 2022-03-04 00:48 UTC

**Comment by Meandering-Breviger** [comment] 2022-03-04 00:55
Just an fyi but there is a tomshardware [article](https://www.tomshardware.com/news/open-source-community-ponders-removing-code-optimizations-for-russian-processors)  on you guys (just came from there).

**Comment by FCLC** [comment] 2022-03-04 01:01
@xianyi @martin-frbg  I have a feeling we may be about to see an influx of comments due to both the Toms hardware and Phoronix article. It may be wise to lock this RFC and open a new one that explicitly deals with technical aspects, such as maintenance of an esoteric architecture, difficulty of integration testing etc.
