### ISSUE TITLE
Building in Nix fails

### ISSUE THREAD

**Issue by leon-thomm** [xianyi/OpenBLAS#4683] opened 2024-05-08 10:04 UTC
I am trying to build this project in Nix, with the dependencies stated in the README. After invoking

```
nix-shell --pure -p gnumake gcc_multi gfortran
```

which creates a pure shell with make, gcc and gfortran available, running `make` fails with the following output:

```
[nix-shell:~/projects/libopenblas/OpenBLAS]$ make
/nix/store/01bi48ga8vzbz4zgh7g3bsl620cj27kj-binutils-2.40/bin/ld: warning: /run/user/1000/cctf8fnU.o: missing .note.GNU-stack section implies executable stack
/nix/store/01bi48ga8vzbz4zgh7g3bsl620cj27kj-binutils-2.40/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/interface'
ar  -ru ../libopenblas_haswellp-r0.3.27.dev.a saxpy.o sswap.o scopy.o sscal.o <snip...>
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/interface'
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/driver/level2'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a sgbmv_n.o sgbmv_t.o ssbmv_U.o <snip...>
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/driver/level2'
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/driver/level3'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a sgemm_nn.o sgemm_nt.o <snip...>
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/driver/level3'
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/driver/others'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a memory.o xerbla.o c_abs.o z_abs.o openblas_set_num_threads.o openblas_get_num_threads.o openblas_get_num_procs.o openblas_get_config.o openblas_get_parallel.o openblas_error_handle.o openblas_env.o blas_server.o divtable.o blasL1thread.o blas_server_callback.o parameter.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/driver/others'
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/kernel'
ar  -ru ../libopenblas_haswellp-r0.3.27.dev.a samax_k.o samin_k.o smax_k.o smin_k.o <snip...>
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/kernel'
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/getrf'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a sgetrf_single.o sgetrf_parallel.o dgetrf_single.o dgetrf_parallel.o cgetrf_single.o cgetrf_parallel.o zgetrf_single.o zgetrf_parallel.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/getrf'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/getf2'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a sgetf2_k.o dgetf2_k.o cgetf2_k.o zgetf2_k.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/getf2'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp'
cd x86_64 && make ../slaswp_plus.o
cd x86_64 && make ../slaswp_minus.o
cd x86_64 && make ../dlaswp_plus.o
cd x86_64 && make ../dlaswp_minus.o
cd x86_64 && make ../claswp_plus.o
cd x86_64 && make ../claswp_minus.o
cd x86_64 && make ../zlaswp_plus.o
cd x86_64 && make ../zlaswp_minus.o
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../slaswp_plus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../slaswp_minus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../claswp_minus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../claswp_plus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../dlaswp_minus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../dlaswp_plus.o' is up to date.
make[3]: '../zlaswp_plus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
make[3]: '../zlaswp_minus.o' is up to date.
make[3]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp/x86_64'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a slaswp_plus.o slaswp_minus.o dlaswp_plus.o dlaswp_minus.o claswp_plus.o claswp_minus.o zlaswp_plus.o zlaswp_minus.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/laswp'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/getrs'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a sgetrs_N_single.o sgetrs_T_single.o sgetrs_N_parallel.o sgetrs_T_parallel.o dgetrs_N_single.o dgetrs_T_single.o dgetrs_N_parallel.o dgetrs_T_parallel.o cgetrs_N_single.o cgetrs_T_single.o cgetrs_R_single.o cgetrs_C_single.o cgetrs_N_parallel.o cgetrs_T_parallel.o cgetrs_R_parallel.o cgetrs_C_parallel.o zgetrs_N_single.o zgetrs_T_single.o zgetrs_R_single.o zgetrs_C_single.o zgetrs_N_parallel.o zgetrs_T_parallel.o zgetrs_R_parallel.o zgetrs_C_parallel.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/getrs'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/potrf'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a spotrf_U_single.o spotrf_L_single.o spotrf_U_parallel.o spotrf_L_parallel.o dpotrf_U_single.o dpotrf_L_single.o dpotrf_U_parallel.o dpotrf_L_parallel.o cpotrf_U_single.o cpotrf_L_single.o cpotrf_U_parallel.o cpotrf_L_parallel.o zpotrf_U_single.o zpotrf_L_single.o zpotrf_U_parallel.o zpotrf_L_parallel.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/potrf'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/potf2'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a spotf2_U.o spotf2_L.o dpotf2_U.o dpotf2_L.o cpotf2_U.o cpotf2_L.o zpotf2_U.o zpotf2_L.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/potf2'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/lauu2'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a slauu2_U.o slauu2_L.o dlauu2_U.o dlauu2_L.o clauu2_U.o clauu2_L.o zlauu2_U.o zlauu2_L.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/lauu2'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/lauum'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a slauum_U_single.o slauum_L_single.o slauum_U_parallel.o slauum_L_parallel.o dlauum_U_single.o dlauum_L_single.o dlauum_U_parallel.o dlauum_L_parallel.o clauum_U_single.o clauum_L_single.o clauum_U_parallel.o clauum_L_parallel.o zlauum_U_single.o zlauum_L_single.o zlauum_U_parallel.o zlauum_L_parallel.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/lauum'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/trti2'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a strti2_UU.o strti2_UN.o strti2_LU.o strti2_LN.o dtrti2_UU.o dtrti2_UN.o dtrti2_LU.o dtrti2_LN.o ctrti2_UU.o ctrti2_UN.o ctrti2_LU.o ctrti2_LN.o ztrti2_UU.o ztrti2_UN.o ztrti2_LU.o ztrti2_LN.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/trti2'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/trtri'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a strtri_UU_single.o strtri_UN_single.o strtri_LU_single.o strtri_LN_single.o strtri_UU_parallel.o strtri_UN_parallel.o strtri_LU_parallel.o strtri_LN_parallel.o dtrtri_UU_single.o dtrtri_UN_single.o dtrtri_LU_single.o dtrtri_LN_single.o dtrtri_UU_parallel.o dtrtri_UN_parallel.o dtrtri_LU_parallel.o dtrtri_LN_parallel.o ctrtri_UU_single.o ctrtri_UN_single.o ctrtri_LU_single.o ctrtri_LN_single.o ctrtri_UU_parallel.o ctrtri_UN_parallel.o ctrtri_LU_parallel.o ctrtri_LN_parallel.o ztrtri_UU_single.o ztrtri_UN_single.o ztrtri_LU_single.o ztrtri_LN_single.o ztrtri_UU_parallel.o ztrtri_UN_parallel.o ztrtri_LU_parallel.o ztrtri_LN_parallel.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/trtri'
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/trtrs'
ar  -ru ../../libopenblas_haswellp-r0.3.27.dev.a strtrs_UNU_single.o strtrs_UNN_single.o strtrs_UTU_single.o strtrs_UTN_single.o strtrs_LNU_single.o strtrs_LNN_single.o strtrs_LTU_single.o strtrs_LTN_single.o strtrs_UNU_parallel.o strtrs_UNN_parallel.o strtrs_UTU_parallel.o strtrs_UTN_parallel.o strtrs_LNU_parallel.o strtrs_LNN_parallel.o strtrs_LTU_parallel.o strtrs_LTN_parallel.o dtrtrs_UNU_single.o dtrtrs_UNN_single.o dtrtrs_UTU_single.o dtrtrs_UTN_single.o dtrtrs_LNU_single.o dtrtrs_LNN_single.o dtrtrs_LTU_single.o dtrtrs_LTN_single.o dtrtrs_UNU_parallel.o dtrtrs_UNN_parallel.o dtrtrs_UTU_parallel.o dtrtrs_UTN_parallel.o dtrtrs_LNU_parallel.o dtrtrs_LNN_parallel.o dtrtrs_LTU_parallel.o dtrtrs_LTN_parallel.o ctrtrs_UNU_single.o ctrtrs_UNN_single.o ctrtrs_UTU_single.o ctrtrs_UTN_single.o ctrtrs_URU_single.o ctrtrs_URN_single.o ctrtrs_UCU_single.o ctrtrs_UCN_single.o ctrtrs_LNU_single.o ctrtrs_LNN_single.o ctrtrs_LTU_single.o ctrtrs_LTN_single.o ctrtrs_LRU_single.o ctrtrs_LRN_single.o ctrtrs_LCU_single.o ctrtrs_LCN_single.o ctrtrs_UNU_parallel.o ctrtrs_UNN_parallel.o ctrtrs_UTU_parallel.o ctrtrs_UTN_parallel.o ctrtrs_URU_parallel.o ctrtrs_URN_parallel.o ctrtrs_UCU_parallel.o ctrtrs_UCN_parallel.o ctrtrs_LNU_parallel.o ctrtrs_LNN_parallel.o ctrtrs_LTU_parallel.o ctrtrs_LTN_parallel.o ctrtrs_LRU_parallel.o ctrtrs_LRN_parallel.o ctrtrs_LCU_parallel.o ctrtrs_LCN_parallel.o ztrtrs_UNU_single.o ztrtrs_UNN_single.o ztrtrs_UTU_single.o ztrtrs_UTN_single.o ztrtrs_URU_single.o ztrtrs_URN_single.o ztrtrs_UCU_single.o ztrtrs_UCN_single.o ztrtrs_LNU_single.o ztrtrs_LNN_single.o ztrtrs_LTU_single.o ztrtrs_LTN_single.o ztrtrs_LRU_single.o ztrtrs_LRN_single.o ztrtrs_LCU_single.o ztrtrs_LCN_single.o ztrtrs_UNU_parallel.o ztrtrs_UNN_parallel.o ztrtrs_UTU_parallel.o ztrtrs_UTN_parallel.o ztrtrs_URU_parallel.o ztrtrs_URN_parallel.o ztrtrs_UCU_parallel.o ztrtrs_UCN_parallel.o ztrtrs_LNU_parallel.o ztrtrs_LNN_parallel.o ztrtrs_LTU_parallel.o ztrtrs_LTN_parallel.o ztrtrs_LRU_parallel.o ztrtrs_LRN_parallel.o ztrtrs_LCU_parallel.o ztrtrs_LCN_parallel.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack/trtrs'
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack'
make[1]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack-netlib'
make -C SRC
make[2]: Entering directory '/home/leon/projects/libopenblas/OpenBLAS/lapack-netlib/SRC'
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o sgedmd.o sgedmd.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o sgedmdq.o sgedmdq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o dsytrd_sb2st.o dsytrd_sb2st.F
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o dgedmd.o dgedmd.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o dgedmdq.o dgedmdq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o clartg.o clartg.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o classq.o classq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o chetrd_hb2st.o chetrd_hb2st.F
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o cgedmd.o cgedmd.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o cgedmdq.o cgedmdq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o zlartg.o zlartg.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o zlassq.o zlassq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o zhetrd_hb2st.o zhetrd_hb2st.F
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o zgedmd.o zgedmd.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o zgedmdq.o zgedmdq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o slartg.o slartg.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o slassq.o slassq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o dlartg.o dlartg.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o dlassq.o dlassq.f90
gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -c -o iparam2stage.o iparam2stage.F
classq.f90:127:8:

  127 |    use LA_XISNAN
      |        1
Fatal Error: Cannot open module file 'la_xisnan.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [Makefile:70: classq.o] Error 1
make[2]: *** Waiting for unfinished jobs....
dlassq.f90:127:8:

  127 |    use LA_XISNAN
      |        1
Fatal Error: Cannot open module file 'la_xisnan.mod' for reading at (1): No such file or directory
compilation terminated.
zlassq.f90:127:8:

  127 |    use LA_XISNAN
      |        1
Fatal Error: Cannot open module file 'la_xisnan.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [Makefile:70: dlassq.o] Error 1
slassq.f90:127:8:

  127 |    use LA_XISNAN
      |        1
Fatal Error: Cannot open module file 'la_xisnan.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [Makefile:70: zlassq.o] Error 1
make[2]: *** [Makefile:70: slassq.o] Error 1
make[2]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack-netlib/SRC'
make[1]: *** [Makefile:27: lapacklib] Error 2
make[1]: Leaving directory '/home/leon/projects/libopenblas/OpenBLAS/lapack-netlib'
make: *** [Makefile:287: netlib] Error 2
```

**Comment by martin-frbg** [comment] 2024-05-08 10:21
Strange - la_xisnan.mod is declared as a dependency of all .f90 files and should have been compiled (from la_xisnan.F90) before the dlassq.f90 that needs it. Is there anything special about the version of `make` used in Nix ?

**Comment by leon-thomm** [comment] 2024-05-08 11:06
I don't think so; `make --version`:
```
GNU Make 4.4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
I believe the package is built from this: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/tools/build-managers/gnumake/default.nix

**Comment by martin-frbg** [comment] 2024-05-08 12:10
There have been a few issues in the past with the new make 4.4 not heeding dependencies like it used to, but never something like this. Try building with `make MAKE_NB_JOBS=1` instead of the automatic parallel build - but perhaps just
rerunning `make` will make it pick up the la_xisnan dependency

**Comment by martin-frbg** [comment] 2024-05-08 17:37
Hmm - can you try adding "la_xisnan.o" to the SCLAUX and DZLAUX lines in lapack-netlib/SRC/Makefile where you already see 'la_constants.o` please ? Could be that this is an oversight in Reference-LAPACK and just happens to work correctly "most of the time"...

**Comment by martin-frbg** [comment] 2024-05-08 18:03
That is a bit of a gray area - for historical reasons, ZSPMV is in LAPACK although conceptionally it belongs in BLAS. As you specified NO_LAPACK=1, this function gets omitted since 0.3.20 to allow combining the BLAS-only build with an external LAPACK

**Comment by martin-frbg** [comment] 2024-05-09 22:02
BTW I could not reproduce your problem with the current NixOS install/live image so far (but I was only using a VM with up to 5 cores)

**Comment by martin-frbg** [comment] 2024-05-10 12:27
What kind of hardware are you running the build on ? (Especially how many cores ?)

**Comment by martin-frbg** [comment] 2024-05-16 12:14
Also not reproduced in a non-VM installation of Nix (6 cores/12 threads) and in a non-root installation of Nix (based on https://zameermanji.com/blog/2023/3/26/using-nix-without-root/) on a 64-core system.

Closing as not reproducible - will reopen if the problem persists for you and new information becomes available.

**Closed as completed by martin-frbg** 2024-05-16 12:14 UTC

**Comment by leon-thomm** [comment] 2024-05-23 14:40
In a fresh clone, I am not encountering this exact issue either anymore, but I'm running into lots of other compile errors, though I am starting to doubt these are actually issues in OpenBLAS. Did you succeed to build OpenBLAS using Nix?

**Comment by martin-frbg** [comment] 2024-05-23 16:29
My builds ran as far as the final link, where libgfortran could not be found - I did not investigate further but assume this was either a missing environment variable or some related Nix setting.

**Comment by leon-thomm** [comment] 2024-05-23 16:46
Alright, I saw this one too, then for now I will assume it is not OpenBLAS. If I manage to compile it on nix I will update.
