### ISSUE TITLE
problem of big matrix calculation under multithread run 

### ISSUE THREAD

**Issue by Jialeen** [xianyi/OpenBLAS#1401] opened 2017-12-22 07:49 UTC
I tested big matrix calculation， and I found a problem. The detail is as follows:
      I generated big matrices to simulate multi-channel image convolution, and then called the function "cblas_sgemm" in multithread environment. The input for all threads was the same, but the results were different. When only one thread, the results were consistent. 
    **The code is as follows:**

#define THREAD_NUM 5
float* weights, * mat;

void* ThreadProc(void* threadParam)
{
	float* ret = (float*)calloc(128*128*128,sizeof(float));
	
	printf("goto sgemm...===--\n");
	{
		cblas_sgemm(CblasColMajor, CblasNoTrans, CblasNoTrans,128,128 * 128,128 * 9,1,weights, 128, mat,128*9,0,ret,128);
	}
	
	printf("%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f\n", ret[685423], ret[123546], ret[98542], ret[120354], ret[8546], ret[9654], ret[41238], ret[95461], ret[493521]);
	
	free(ret);
	ret = NULL;
	return 0;
}

int main(int argc, char* argv[])
{
	if(argc < 2)
	{
		printf("Please set the number of threads\n");
		return -1;
	}
	int i = 0;
	weights = (float*)calloc(128 * 128 * 9 , sizeof(float));
	for(i = 0; i < 128 * 128 * 9; i++)
	{
		weights[i] = i % 7 + 0.26;
	}
	mat = (float*)calloc(128 * 128 * 128 * 9 , sizeof(float));
	for(i = 0; i < 128 * 128 * 128 * 9; i++)
	{
		mat[i] = i % 6 + 0.31;
	}
	

	int numThreads = atoi(argv[1]);
	pthread_t threadId[THREAD_NUM] = {0};
	for(i = 0; i < numThreads; i++)
	{
		if (pthread_create(&threadId[i], NULL, ThreadProc, NULL) != 0)
    	{
			printf("%s:%d create pthread error!\n", __FILE__, __LINE__);
        	return -1;
    	}
	}
	
	for (i = 0;i < numThreads;i++) {
		pthread_join(threadId[i],NULL);
	}

	printf("Threads over\n");
	
	return 0;
}

The result is as follows:
1. 4 threads
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 4
goto sgemm...===--
goto sgemm...===--
goto sgemm...===--
goto sgemm...===--
10538.33, 10560.71, 10548.09, 10543.95, 10568.40, 10578.26, 10527.09, _10564.95_, 10569.19
10543.95, 10560.71, 10543.16, 10543.95, 10579.64, 10573.33, 10527.09, _10539.02_, 10578.26
10588.81, 10560.71, 10538.23, 10543.95, 10590.88, 10555.78, 10527.09, 10513.09, 10567.71
10563.57, 10560.71, 10543.16, 10543.95, 10579.64, 10555.78, 10527.09, 10539.02, 10557.16
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 4
goto sgemm...===--
goto sgemm...===--
goto sgemm...===--
goto sgemm...===--
10518.71, 10560.71, 10565.64, 10543.95, 10555.78, 10560.71, 10527.09, _10573.33_, 10569.19
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, _10547.40_, 10558.64
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10573.33, 10527.09, 10547.40, 10567.71
10569.19, 10560.71, 10555.78, 10543.95, 10578.26, 10538.23, 10527.09, 10521.47, 10557.16
Threads over

2. 1 thread
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over
yujialin@ntr-Force-F:~/project/openBlas$ ./openBlasDemo 1
goto sgemm...===--
10543.95, 10560.71, 10560.71, 10543.95, 10567.02, 10560.71, 10527.09, 10547.40, 10558.64
Threads over

Could you please check it and tell me how to resolve it?
Thank you very much.

**Comment by martin-frbg** [comment] 2017-12-22 07:55
Can you please retry the OpenBLAS build with USE_SIMPLE_THREADED_LEVEL3=1 set ? It may also help to know what hardware and operating system you are using (and which version of OpenBLAS - some multithreading bugs have been fixed in recent months, but there may be some more remaining)

**Comment by Jialeen** [comment] 2017-12-22 08:56
@martin-frbg Thank you very much, and that set solves my problem.

**Comment by brada4** [comment] 2017-12-23 09:59
@martin-frbg should we change default in M.rule to make defaults live to less confusion?

**Comment by martin-frbg** [comment] 2017-12-23 16:36
Probably makes sense at least for non-OPENMP builds, unless this can be fixed soon.

**Comment by martin-frbg** [comment] 2017-12-24 14:43
Jialeen, could you please add which version of OpenBLAS you are using, and on what hardware and operating system ? While I do see a number of warnings from the "helgrind" thread debugger, I cannot reproduce the wrong results you were seeing with that test case on either Haswell or Kaby Lake under Linux.

**Comment by Jialeen** [comment] 2017-12-28 10:45
@martin-frbg The OpenBLAS version is 0.2.20. The CPU is Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, and the OS is Ubuntu 16.04.2 LTS. Thank you very much.

**Comment by brada4** [comment] 2017-12-28 14:04
@Jialeen  you have to update CPU microcode. Usually it boils down to BIOS upgrade after https://lists.debian.org/debian-devel/2017/06/msg00308.html
If that does not help try microcode_ctl on running system - usually if microcode package was installed this happens within initrd.
If neither helps - disable hyperthreading (no performance loss in this action)
Please re-run the tests once any of fixes is applied.

**Comment by Jialeen** [comment] 2018-01-08 11:13
@brada4  I'm sorry for so late testing. It works after updating the CPU microcode. Thank you very much.

**Closed as completed** 2018-01-08 11:17 UTC

**Comment by Jialeen** [comment] 2018-01-12 03:36
@brada4 The problem comes up again. And I found another phenomenon.
When I employed openMP to generate multi threads, the results were the same. But if the threads were created by "pthread_create", the results were different.

The code and results are as follows:
code: 
#define THREAD_NUM 5


float* weights, * mat;
float* A, *B;
int outRows = 128, outCols = 16384;
int midParam = 576;

void* ThreadProc(void* threadParam)
{
	float* ret = (float*)calloc(outRows * outCols, sizeof(float));
	
	printf("create thread by pthread_create\n");
	{
		cblas_sgemm(CblasColMajor, CblasNoTrans, CblasNoTrans,outRows, outCols, midParam,1,weights, outRows, mat, midParam,0,ret,outRows);
	}
	
	printf("%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f\n", ret[685423], ret[123546], ret[65], ret[12035], ret[8546], ret[9654], ret[41238], ret[95461], ret[493521]);
	
	free(ret);
	ret = NULL;
	return 0;
}

int main()
{
	weights = (float*)calloc(outRows * midParam , sizeof(float));
	for(int i = 0; i < outRows * midParam; i++)
	{
		weights[i] = i % 7 + 0.26;
	}
	mat = (float*)calloc(midParam * outCols , sizeof(float));
	for(int i = 0; i < midParam * outCols; i++)
	{
		mat[i] = i % 6 + 0.31;
	}
	
#ifdef OPENMP_TEST
	#pragma omp parallel for num_threads(5)
	for(int i = 0; i < 5; i++)
	{
		printf("create thread by openMP\n");
		float* ret = (float*)calloc(outRows * outCols, sizeof(float));
		cblas_sgemm(CblasColMajor, CblasNoTrans, CblasNoTrans,outRows, outCols, midParam,1,weights, outRows, mat, midParam,0,ret,outRows);
		printf("i = %d: %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f\n", i, ret[685423], ret[123546], ret[65], ret[12035], ret[8546], ret[9654], ret[41238], ret[95461], ret[493521]);
	}
#endif
	
#ifdef CREATE_THREAD
	pthread_t threadId[THREAD_NUM] = {0};
	for(int i = 0; i < THREAD_NUM; i++)
	{
		if (pthread_create(&threadId[i], NULL, ThreadProc, NULL) != 0)
    	{
			printf("%s:%d create pthread error!\n", __FILE__, __LINE__);
        	return -1;
    	}
	}
	
	for (int i = 0;i < THREAD_NUM;i++) {
		pthread_join(threadId[i],NULL);
	}
#endif
	return 0;
}

results:
1、
create thread by pthread_create
create thread by pthread_create
create thread by pthread_create
create thread by pthread_create
create thread by pthread_create
5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
5251.27, 5263.20, 5303.13, 5275.13, 5291.89, 5263.20, 5263.89, 5273.75, 5286.37
5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
5251.27, 5263.20, 5303.13, 5275.13, 5291.89, 5263.20, 5263.89, 5273.75, 5286.37

2、
create thread by openMP
create thread by openMP
create thread by openMP
create thread by openMP
create thread by openMP
i = 3: 5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
i = 0: 5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
i = 2: 5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
i = 4: 5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75
i = 1: 5268.82, 5263.20, 5297.51, 5275.13, 5272.27, 5263.20, 5263.89, 5275.13, 5294.75

I am confused, and could you please check it. Thank you very much.

**Comment by brada4** [comment] 2018-01-12 04:57
pthreads version of openblas is not thread-safe, nothing to do with your microcode

**Comment by martin-frbg** [comment] 2018-01-12 06:57
I still can not reproduce the diverging results, @brada4 can you ?

**Comment by Jialeen** [comment] 2018-01-12 08:21
@martin-frbg 
I built the library as follow:
make NUM_THREADS=64 BINARY=64 USE_OPENMP=1 USE_THREAD=1

**Comment by brada4** [comment] 2018-01-12 10:20
Not on CentOS7, debian 16lts with high-end Ivy Bridge and Broadwell
Results are consistent with OMP, pthread and single thread, with included openblas and with devel build
@Jialeen can you try preceding failing program with variables to utilize one thread in eventual pthread code under OMP?
`OPENBLAS_NUM_THREADS=1 ./a.out`
?
