### ISSUE TITLE
Cannot compile with thread affinity enabled, undefined reference to `sched_getcpu'

### ISSUE THREAD

**Issue by Diazonium** [xianyi/OpenBLAS#1210] opened 2017-06-21 13:05 UTC
I have tried to compile both the latest release and the latest git code, but both fail to compile if I enable thread affinity.
I am pretty sure I really need to have thread affinity working, because on a 4 socket Barcelona cluster (4*12=48 cores per node) I am getting absolutely abysmal scaling on DGELSY, sometimes even heavy negative scaling. I am fairly sure this is due to having 4 NUMA regions, and thread affinity could help resolve it. But I cannot get openblas to compile with thread affinity on this cluster.
The cluster is using GCC 4.7.2.

Here is the part where failures happen:

> gfortran -O2 -Wall -m64   -o dblat1 dblat1.o ../libopenblas_barcelonap-r0.2.20.dev.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran
> sblat2.f: In function ‘schk1’:
> sblat2.f:646:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> dblat2.f: In function ‘dchk1’:
> dblat2.f:646:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> ../libopenblas_barcelonap-r0.2.20.dev.a(init.o): In function 'gotoblas_affinity_init':
> init.c:(.text+0xd07): undefined reference to 'sched_getcpu'
> collect2: error: ld returned 1 exit status
> make[1]: *** [sblat1] Error 1
> make[1]: *** Waiting for unfinished jobs....

**Comment by martin-frbg** [comment] 2017-06-21 13:19
What is your glibc version please ? (From the sched_getcpu manpage on my systems this function should be available since glibc 2.6, the page goes on to note that it can be emulated by a Linux/x86 specific system call to getcpu() which was introduced in kernel 2.6.19)

**Comment by Diazonium** [comment] 2017-06-21 13:34
If I am reading this output correctly, glibc is at version 2.5.

> *************** ~ (0)$ /lib/libc.so.6
> GNU C Library stable release version 2.5, by Roland McGrath et al.
> Copyright (C) 2006 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
> Compiled by GNU CC version 4.1.2 20080704 (Red Hat 4.1.2-50).
> Compiled on a Linux 2.6.9 system on 2010-12-14.
> Available extensions:
>         The C stubs add-on version 2.1.2.
>         crypt add-on version 2.1 by Michael Glad and others
>         GNU Libidn by Simon Josefsson
>         GNU libio by Per Bothner
>         NIS(YP)/NIS+ NSS modules 0.19 by Thorsten Kukuk
>         Native POSIX Threads Library by Ulrich Drepper et al
>         BIND-8.2.3-T5B
>         RT using linux kernel aio
> Thread-local storage support included.

**Comment by Diazonium** [comment] 2017-06-21 13:36
Also the current kernel version actually running is 2.6.18-238.el5

**Comment by martin-frbg** [comment] 2017-06-21 13:45
Too bad, that combination would seem to exclude rolling your own implementation based on the getcpu
syscall as suggested e.g. here: https://lists.lttng.org/pipermail/lttng-dev/2010-May/013865.html unless you can update at least the kernel.

**Comment by Diazonium** [comment] 2017-06-21 14:02
Yeah, it looks like there is no solution for this. Updating the kernel is probably out of the question, if I asked the admins to do it, they would probably say something along the lines of "sry, not possible, deal with it"

**Comment by martin-frbg** [comment] 2017-06-21 14:17
Searching for "getcpu 2.6.18" yielded this thread with a possible (if somewhat roundabout) solution at the end: http://www.linuxforums.org/forum/kernel/192140-getcpu-system-call-kernel-2-6-18-a.html

**Comment by Diazonium** [comment] 2017-06-21 14:35
Wow, thanks for finding that. If and when I have a lot of time on my hands, I might implement that, but right now I was just looking for a quick fix. 
I have access to another system, that does not suffer from this issue, and I am getting decent performance out of it, so while getting this to work would be nice, I am not desperate. Thanks anyways.

**Comment by martin-frbg** [comment] 2017-06-21 17:36
Shouldn't be that hard to add that function somewhere in driver/others/init.c with an `#ifdef` to ensure it is only used when the real thing is not available. A rather elegant solution for this can be found in https://www.spinics.net/lists/linux-perf-users/msg02228.html (Though the actual implementation of sched_getcpu in that patch is unhelpful and would need to be replaced with something more like the link I posted earlier. I do hope there will be a more lightweight solution than having a shell invoke awk to process data from the /proc pseudofilesystem...). 
At first glance all the other cpuset-specific functions used in that file have been in glibc since 2.3.3 so should not pose a problem for old RHEL5 installations such as yours.

**Comment by brada4** [comment] 2017-06-22 05:41
Since your RHEL5 system just went into retro state, here are the latest packages:
https://archives.fedoraproject.org/pub/archive/epel/5/x86_64/
(search 'openblas' and install all packages matching - -lopenblas will be single-threaded -lopenblasp - pthread and -lopenblaso - OpenMP)
Not that affinity ever worked on RHEL5, but you are first to try and just few months late.

**Comment by martin-frbg** [comment] 2017-06-22 10:41
@brada4 what makes you expect that the sched_getcpu call would work with those fedora packages when the issue is lack of implementation on the system side ? (And that is even assuming that those were built with the non-default setting to enable affinity support at all ?)

**Comment by brada4** [comment] 2017-06-22 11:33
Thos are fedora EPEL  for RHEL5 archived packages, used to work last time I checked years ago.
e.g they set NO_AVX(2) as the system compiler never supported those etc.
Affinity support is not present in default kernel, you need (expensive, no longer sold) MRG version of kernel.
(plus one needs to scatter headers and add extra library on top of -lc to instrument those)
I'd say CentOS 7 upgrade highly recommended instead of deep dive into history of Linux....

**Comment by martin-frbg** [comment] 2017-06-22 12:28
OP had no problems compiling current develop tree without affinity support it seems, so going back to 0.2.18 would only bring back bugs probably. **IF** the stock RHEL5 kernels actually lack the relevant capability then perhaps the best option is to close this issue rather than bother with partial workarounds for such old installations.

**Comment by brada4** [comment] 2017-06-22 18:42
Seen in my man page on suse....
```
VERSIONS
       getcpu() was added in kernel 2.6.19 for x86_64 and i386.
```

**Comment by loveshack** [comment] 2017-06-27 12:48
@brada4 The RHEL 5 kernel supports affinity fine on x86_64 (with sched_{s,g}et_affinity), as you can tell by running hwloc-ps under hwloc-bind, for instance.  I did extensive work on it.

**Comment by brada4** [comment] 2017-06-27 17:20
OpenBLAS uses newer and simpler interface.
Maybe it is supported at EUS/AUS pricing.... I dont think new function can be added to libc even bursting in tears in front of support....

**Comment by martin-frbg** [comment] 2017-06-28 17:35
This seems to work in principle, but I do not have a NUMA machine with RHEL5 for testing.
There are probably more elegant ways of skipping everything before entry 39 of the stat output,
and you will certainly want to omit the printfs after your initial test.
```
--- a/driver/others/init.c
+++ b/driver/others/init.c
@@ -354,6 +354,26 @@ static int numa_check(void) {
   return common -> num_nodes;
 }
 
+#if defined(__GLIBC_PREREQ)
+#if !__GLIBC_PREREQ(2, 6)
+int sched_getcpu(void)
+{
+int cpu;
+FILE *fp = NULL;
+fprintf(stderr,"selfstat..\n");
+if ( (fp = fopen("/proc/self/stat", "r")) == NULL)
+   return -1;
+if ( fscanf( fp, "%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%d", &cpu) != 1) {
+  fclose (fp);
+  return -1;
+  }
+  fclose (fp);
+fprintf(stderr,"running on cpu %d\n",cpu);
+  return(cpu);
+}
+#endif
+#endif
+
 static void numa_mapping(void) {
 
   int node, cpu, core;

**Closed** 2017-07-09 11:16 UTC
