### ISSUE TITLE
Aarch64 fails to build with GCC < 9 due to missing arm_sve.h

### ISSUE THREAD

**Issue by StefanBruens** [xianyi/OpenBLAS#3874] opened 2022-12-25 00:19 UTC
The `NEOVERSEN2` target requires the `arm_sve.h` header file:

[ 1017s] gcc -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g  -fno-strict-aliasing -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=256 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -march=armv8.2-a -mtune=cortex-a72 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sbgemm_kernel_NEOVERSEN2 -DASMFNAME=sbgemm_kernel_NEOVERSEN2_ -DNAME=sbgemm_kernel_NEOVERSEN2_ -DCNAME=sbgemm_kernel_NEOVERSEN2 -DCHAR_NAME=\"sbgemm_kernel_NEOVERSEN2_\" -DCHAR_CNAME=\"sbgemm_kernel_NEOVERSEN2\" -DNO_AFFINITY -DTS=_NEOVERSEN2 -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_NEOVERSEN2 -DBFLOAT16 -UDOUBLE  -UCOMPLEX -c -DBFLOAT16 -UDOUBLE -UCOMPLEX ../kernel/arm64/sbgemm_kernel_8x4_neoversen2.c -o sbgemm_kernel_NEOVERSEN2.o
[ 1018s] ../kernel/arm64/sbgemm_kernel_8x4_neoversen2.c:29:10: fatal error: arm_sve.h: No such file or directory
[ 1018s]  #include <arm_sve.h>
[ 1018s]           ^~~~~~~~~~~
[ 1018s] compilation terminated.

**Comment by StefanBruens** [comment] 2022-12-25 01:34
As a workaround, `DYNAMIC_LIST` can be used to specify all wanted targets and omit NEOVERSEN2, e.g. `DYNAMIC_LIST='ARMV8 CORTEXA53 CORTEXA72 THUNDERX NEOVERSEN1'`

**Comment by martin-frbg** [comment] 2022-12-25 08:21
Probable duplicate of #3805 but I am realizing now that the gcc version guard in Makefile.arm64 does not prevent the problem as intended, there needs to be another check in the DYNAMIC_LIST setup of Makefile.system. I'll see if I can find time to prepare a PR later today

**Comment by martin-frbg** [comment] 2022-12-25 11:06
Also the actual issue is likely not the version of the compiler, but that of binutils (which is why our CI jobs completes successfully even with gcc-8). This needs more work, probably having c_check test for the presence of arm_sve.h and exporting something like NO_SVE=1 to the build system if not.

**Closed as completed** 2022-12-31 11:07 UTC
