### ISSUE TITLE
Clean the register on ARM VFP kernels

### ISSUE THREAD

**Issue by xianyi** [xianyi/OpenBLAS#740] opened 2016-01-12 22:35 UTC
@yuyichao , I just reverted your #733 patch because of bus errors on our ARM machines.

It looks like `vldr` (pseudo-instruction) causes the bus error.

And I tried the following for sdot kernel. It works.
* `vldr`: manually create the constant. This is used when the pseudo instruction doesn't work.

Is it possible to use neon instead of vfp3? I mean, change `-mfpu=vfp3` to `-mfpu=neon` for ARMV7 target.

@wernsaar  ,any ideas?

**Comment by yuyichao** [comment] 2016-01-12 22:55
I don't think neon is required on ARMv7. (The scaleway server, for example, is a Cortex-A9 that doesn't have neon....).

**Comment by yuyichao** [comment] 2016-01-12 22:57
Also what is the command line and the assembly emitted? Sounds like a bug to me if the compiler emit neon instructions without `-mfpu=neon`.

**Comment by martin-frbg** [comment] 2016-01-13 09:07
I have neither the assembler knowledge nor the hardware to check it, but do you know if the reported bus errors are "all over the place", or all from one of the several places changed ? E.g. the changes to ctrmm_kernel_2x2_vfpv3.S not only introduced vldr, but also moved that line of initialization outside the macro - and the only reason I see is that the new code uses a new constant set to "word 0x00000000" instead of "=0" in some cases but not others although all are superficially "the same" vldr.f32 s16,... - if just one of them is a copy+paste that should have been edited afterwards to use the correct flavor of zero...

**Comment by yuyichao** [comment] 2016-01-15 19:01
Ping @wernsaar @xianyi . Do you have a backtrace for the bus error?

It would also have been much better if the commit is not just simply reverted but to identify the actual issue first. Different part of the commit are independent so it should have been really easy to bisect on the commit (by reverting certain files) even if it is somehow hard to get a backtrace.

**Comment by yuyichao** [comment] 2016-01-15 19:04
@martin-frbg 

> E.g. the changes to ctrmm_kernel_2x2_vfpv3.S not only introduced vldr, but also moved that line of initialization outside the macro - and the only reason I see is that the new code uses a new constant set to "word 0x00000000" instead of "=0" in some cases but not others although all are superficially "the same" vldr.f32 s16,... - if just one of them is a copy+paste that should have been edited afterwards to use the correct flavor of zero...

See my detailed comment in the pull request and also in the code that use this pattern. The issue is that the assembler cannot always handle the pseudoinstruction in all cases.

**Comment by yuyichao** [comment] 2016-01-15 19:06
And the reason of moving the register clearing out of the init blocks is that which zero constant to use depends on where the code is in the function (i.e. where the macro is used) and not where the macro is defined.

**Comment by martin-frbg** [comment] 2016-01-15 19:41
Thx. I did not intend to criticize, it was just that to me the nature of the changes in this one file appeared to have the most potential for an oversight (such as missing one caller of the macro, or omitting to adjust the type of zero constant in one instant).

**Comment by martin-frbg** [comment] 2016-01-15 19:54
Please bear with me for one more comment - anything useful to be found re arm/neon vldr alignment issues in the comments of https://github.com/mapbox/protozero/issues/33 ?

**Comment by xianyi** [comment] 2016-01-15 20:09
@yuyichao , I debugged the sdot bus error.

The error comes from the following line at sdot_vfp.S.
```
vldr.f32                s0 , =0
```

Then, I fixed it as following.

```
sdot_f32zero:
        .word 0x00000000
vldr.f32                s0 , sdot_f32zero
```
It works for fixing sdot bus error.

Meanwhile, I found the computational error for gemm after applying your patch.


I can give you the ssh access of our ARM dev box.

**Comment by yuyichao** [comment] 2016-01-15 20:14
Hmmm, interesting, I would not have guessed since the assembler should have done the right thing. Do you remember what's the asm generated?

**Comment by xianyi** [comment] 2016-01-15 20:24
@yuyichao , I didn't objdump the instructions. I just found that our ARM box is offline. I will try it when it comes back.

**Comment by yuyichao** [comment] 2016-01-15 20:36
Thx, I didn't try harder to run the test after the pr is merged. I can try that again, and also possibility on a real 32bit chip rather than a 64bit one...

**Comment by wernsaar** [comment] 2016-01-17 14:49
Please see dgemm_kernel_4x4_vfpv3.S.
The solution is really simple:
Store some zeros on the stack and read the zeros.
Sorry, that I had not this idea two years ago.

Werner

**Comment by xianyi** [comment] 2016-01-20 17:43
@wernsaar , thank you for the solution.


@yuyichao , I disassembly the code.

```
          vldr.f32                s0 , =0
          vldr.f32                s1 , =0
```
to
```
  1c:   ed900a00        vldr    s0, [r0]
  20:   edd00a00        vldr    s1, [r0]
```

Bus error. r0 is the input n.

**Closed** 2016-01-27 20:13 UTC

**Comment by yuyichao** [comment] 2016-01-27 20:20
Thanks for the correct fix.
