### ISSUE TITLE
DGEMM: illegal instruction on old x86 processor built with DYNAMIC_ARCH

### ISSUE THREAD

**Issue by sethrj** [xianyi/OpenBLAS#3139] opened 2021-03-11 11:35 UTC
This is a really old system (AMD K10, from 2007), but with the release of 0.3.13, OpenBLAS with the `DYNAMIC_ARCH=1` (built on a newer CPU) is now failing inside OpenBLAS DGEMV:
```
Program received signal SIGILL, Illegal instruction.
0x00002aaaab42040f in dgemv_ ()
   from /projects/spack/var/spack/environments/scale/.spack-env/view/lib/libopenblas.so.0
```

This was built using GCC 8.3 using binutils 2.35.1 on RHEL6. I confirmed that 0.3.12 works in the same setup.

**Comment by martin-frbg** [comment] 2021-03-11 12:55
Hm, if anything I would expect 0.3.13 to be more careful when applying cpu-specific compiler optimizations in DYNAMIC_ARCH builds. (With 0.3.12, these tended to carry over from previously processed cpu entries, accumulating capabilities that might not be available in individual cpus). Which TARGET did you specify for the common code of the DYNAMIC_ARCH build ? (If not given, it would default to the capabilities of the build host, which could make the compiler use AVX2 and the like)

**Comment by sethrj** [comment] 2021-03-11 13:55
Thanks for the quick response @martin-frbg . I didn't specify a TARGET but did specify an ARCH. The exact configuration I used is:
```
'make' '-j16' 'CC=/projects/spack/lib/spack/env/gcc/gcc' 'FC=/projects/spack/lib/spack/env/gcc/gfortran' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'DYNAMIC_ARCH=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'
```

It does indeed like the newer build is targeting the host processor rather than the generic one. In the older (working) 0.3.12 build, the make line is:
```
/projects/spack/lib/spack/env/gcc/gcc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -   DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.12\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=dgemv -DASMFNAME=dgemv_ -DNAME=dgemv_ -DCNAME=dgemv -DCHAR_NAME=\"dgemv_\" -DCHAR_CNAME=\"dgemv\" -DNO_AFFINITY -I.. -I. -DDOUBLE  -UCOMPLEX -o dgemv.o gemv.c
```
but the newer version uses "native" flags.
```
/projects/spack/lib/spack/env/gcc/gcc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.13\" -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mfma -mavx2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=dgemv -DASMFNAME=dgemv_ -DNAME=dgemv_ -DCNAME=dgemv -DCHAR_NAME=\"dgemv_\" -      DCHAR_CNAME=\"dgemv\" -DNO_AFFINITY -I.. -I. -DDOUBLE  -UCOMPLEX -o dgemv.o gemv.c
```

I would think that if you specify a `DYNAMIC_ARCH` build, the library as a whole should work with the oldest supported `DYNAMIC` target, and just support accelerated kernels on the newer targets.

**Comment by martin-frbg** [comment] 2021-03-11 14:17
Right, this mostly used to work "by accident" but the problem has been aggravated by the recent introduction of "universal intrinsics" into cpu-specific BLAS kernels, which require the respective compiler flags to "unlock" the functionality in the gcc headers.  
Your suggestion does have some merit, given how many got bitten by this (although it has been mentioned in the readme for some time, and the minimum required target for the library also gets printed at the end of the build process - btw is there a specific reason why you are cherrypicking individual subtargets of `make` instead of running a complete build ?)

**Comment by sethrj** [comment] 2021-03-11 14:27
I see; I don't recall  the TARGET option from I when I last took a deep look at DYNAMIC_ARCH (I set it up for Spack, see https://github.com/spack/spack/issues/14380 ), which was OpenBLAS 0.3.7. Thanks for the heads up.

Grepping for `target` in the build output for 0.3.13 doesn't produce any hits -- where should I have expected to see that output line?

Regarding subtargets -- I built using the typical whole-package make; I  just chose the single `gemv` make line as an example of the actual flags being passed to `$CC`.

**Comment by martin-frbg** [comment] 2021-03-11 14:42
Final lines of `make` output should be something like
```
  Library Name     ... libopenblasp-r0.3.13.dev.a (Multi-threading; Max num-threads is 4)
  Supporting multiple x86_64 cpu models with minimum requirement for the common code being CORE2

To install the library, you can run "make PREFIX=/path/to/your/installation install".
```

**Comment by sethrj** [comment] 2021-03-11 14:59
Weird, I'm not seeing that at all -- the last thing in the build stage is when it builds `linktest` and echos `OK`. After installing, it writes `Install OK!` I see nothing about common code.

**Comment by sethrj** [comment] 2021-03-11 15:04
So, to be clear: to prevent gcc from adding any architecture-specific flags, while supporting optimized kernels for newer CPUs, the correct set of flags is `DYNAMIC_ARCH=1` `DYNAMIC_OLDER=1` `TARGET=GENERIC`?

**Comment by martin-frbg** [comment] 2021-03-11 15:13
Yes, that should work. (Not sure why you were not seeing the output - both the compiler version info and the "minimum required cpu" were added in March 2020 for the 0.3.10 release.)

**Comment by sethrj** [comment] 2021-03-11 15:15
Super, thanks a bunch. Maybe the due to some streaming issue -- the log file I'm looking at is filtered through spack.

**Comment by brada4** [comment] 2021-03-12 16:53
Can you get `/proc/cpuinfo` just to check it is well identified as early athlon, namely whether it has sse3 ISA or not.

**Comment by sethrj** [comment] 2021-03-12 20:16
@brada4 There are 8 identical cores ; here is one:
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 4
model name	: Quad-Core AMD Opteron(tm) Processor 2378
stepping	: 2
cpu MHz		: 2412.392
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt npt lbrv svm_lock nrip_save
bogomips	: 4824.78
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
```

The Spack-derived [archspec project](https://github.com/archspec/archspec-json) identifies the processor as k10: https://github.com/archspec/archspec-json/blob/c32454478a4901add84d9e784e7a005dbba65a7e/cpu/microarchitectures.json

**Comment by sethrj** [comment] 2021-03-13 02:17
@martin-frbg I've updated the "generic" targets in Spack (see the linked PR above) so that it correctly requests `TARGET=GENERIC` and allows older target optimizations. Thanks for the pointers, and I think this issue can be closed if you think the current behavior is as expected.

**Comment by brada4** [comment] 2021-03-13 09:18
OpenBLAS detection would be TARGET=BARCELONA

GCC would accept either spelling

>      'amdfam10'
>      'barcelona'
>           CPUs based on AMD Family 10h cores with x86-64 instruction set
>           support.  (This supersets MMX, SSE, SSE2, SSE3, SSE4A, 3DNow!,
>           enhanced 3DNow!, ABM and 64-bit instruction set extensions.)
>

**Comment by sethrj** [comment] 2021-03-13 12:16
> OpenBLAS detection would be TARGET=BARCELONA

The cpuinfo I provided was from one of our  older nodes that we use for CI.  The host system I compiled  on was much newer -- haswell I think. I didn't know *a priori* how old of a system was going to need the library, which is apparently why I need the GENERIC target and DYNAMIC_OLDER.

My confusion was in part because I assumed "dynamic" would allow running on older  systems while supporting newer ones, not that it would allow running *newer* systems while optimizing for the host build.  Most scientific libraries don't include `-march=native -mtarget=native`  by default -- they assume generic systems unless you or your build toolchain specify  architecture flags.

**Comment by brada4** [comment] 2021-03-13 19:35
Decades ago build systems were unpatched nearly decommissioned hosts, so assumption of using build host as the generic one worked just fine. It should be one-liner to clamp shared code to generic, but thinking about upcoming glibc hwcaps it will soon need sub-setting of compute kernels, not sure if that should be left downstream or polished here.

**Comment by martin-frbg** [comment] 2021-03-13 19:47
Not sure I understand that comment about future glibc changes... not sure either if defaulting to the build host in dynamic_arch was ever a conscious decision, just one that people used to live with (and that did not have as grave consequences until fairly recently).
In any case not really something I want to change before the overdue 0.3.14 release.

**Comment by brada4** [comment] 2021-03-13 22:09
I fear it grows bigger than an one-liner, certainly not to push before release.

**Comment by brada4** [comment] 2021-03-13 22:13
Other is something like to take HWCAP as granted, build common stuff (not sure how) with hwcap-generic `-mwhatever` and only build subset of kernels from hwcap level and above, thats quite a change.

**Comment by p-e-w** [comment] 2021-04-03 05:19
FWIW, I encountered this issue on an `Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz`, which was released in September 2015 (details at https://github.com/daanzu/kaldi-active-grammar/issues/50). So the problem is by no means limited to "ancient" CPUs.

Switching the OpenBLAS build to `TARGET=GENERIC` fixed it, but it's clear that this shouldn't be happening in the first place.

**Closed as completed** 2022-03-06 10:46 UTC
