### ISSUE TITLE
The possible bug of the complex in-place matrix transposition function "cblas_cimatcopy"

### ISSUE THREAD

**Issue by FlyHighInSky** [xianyi/OpenBLAS#899] opened 2016-05-31 11:37 UTC
The OpenBLAS project is wonderful, and thanks for the team's hardworking.
**project version:** r0.2.17.dev
**host:**Ubuntu 14.04 LTS
**target:**ArmV7
**compile command:** make CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=ARMV7 CROSS=1 NO_LAPACKE=1 NO_SHARED=1 BINARY=32 USE_OPENMP=1

If the **column** and **row** of the  input matrix are **not equal**, the function "cblas_cimatcopy" got wrong result; but, the function "cblas_comatcopy" got the correct result. 

I do not know it is a bug or not, thanks.

**Comment by brada4** [comment] 2016-05-31 17:42
Can you get some code sample to compare against MKL?

**Comment by FlyHighInSky** [comment] 2016-06-01 08:22
@brada4 I have checked the corresponding MKL **"mkl_cimatcopy"**, and it got the right result.

The MKL code sample:
`#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include "mkl.h"
#include "mkl_trans.h"

#define M (3)
#define N (2)

int main(void)
{
	int i, j;
	int	lda = N,// A col
		ldb = M;// B col
	MKL_Complex8 alpha = { 1, 0 };
	MKL_Complex8 in1[M*N] = { 0 }, in2[M*N] = { 0 }, out[M*N] = { 0 };

	// Input complex matrix
	printf("The input complex matrix:\n");
	for (i = 0; i < M; i++)
	{
		for (j = 0; j < N; j++)
		{
			in1[i * N + j].real = i + 1.0f;
			in1[i * N + j].imag = 2*j + 3.0f;
			printf("%4.1f+%4.1fI ", in1[i * N + j].real, in1[i * N + j].imag);
		}
		printf("\n");
	}

	memcpy(in2, in1, M*N*sizeof(MKL_Complex8));

	// transposition using cblas_comatcopy
	mkl_comatcopy('R', 'T',
		M, N, alpha, in2, lda, out, ldb);

	printf("\nThe output complex matrix using mkl_comatcopy:\n");
	for (i = 0; i < N; i++)
	{
		for (j = 0; j < M; j++)
			printf("%4.1f+%4.1fI ", out[i * M + j].real, out[i * M + j].imag);
		printf("\n");
	}
	printf("\n");

	// transposition using cblas_cimatcopy
	mkl_cimatcopy('R', 'T',
		M, N, alpha, in1, lda, ldb);

	printf("\nThe output complex matrix using mkl_cimatcopy:\n");
	for (i = 0; i < N; i++)
	{
		for (j = 0; j < M; j++)
			printf("%4.1f+%4.1fI ", in1[i * M + j].real, in1[i * M + j].imag);
		printf("\n");
	}
	system("pause");
}`
![1](https://cloud.githubusercontent.com/assets/19662080/15701870/5b90d56a-280f-11e6-8fd3-7049526d740e.PNG)

The OpenBLAS code sample:
`#define M (3)
#define N (2)

int main(void)
{
	int i,j;
	int	lda=N,// A的列,
		ldb=M;// B的列,
	float alpha = 1;
	float in[M*N*2]={0}, in1[M*N*2]={0}, out[M*N*2]={0};

	// Input complex matrix
	printf("The input complex matrix:\n");
	for (i=0; i<M; i++)
	{
		for (j=0; j<N; j++)
		{
			in[i*2*N+2*j] = i+1.0f+3.0f*j;
			in[i*2*N+2*j+1] = 10+i*2+j;
			printf("%4.1f+%4.1fI ", in[i*2*N+2*j], in[i*2*N+2*j+1]);
		}
		printf("\n");
	}
	memcpy(in1, in, M*N*2*sizeof(float));

	// transposition using cblas_comatcopy
	cblas_comatcopy(CblasRowMajor, CblasTrans,
		M, N, &alpha, in1, lda, out, ldb);

	printf("\nThe output complex matrix using cblas_comatcopy:\n");
	for (i = 0; i < N; i++)
	{
		for (j = 0; j < M; j++)
			printf("%4.1f+%4.1fI ", out[i * 2 * M + 2 * j], 	out[i * 2 * M + 2 * j + 1]);
		printf("\n");
	}
	printf("\n");

	// transposition using cblas_cimatcopy
	cblas_cimatcopy(CblasRowMajor, CblasTrans,
		M, N, &alpha, in, lda, ldb);

	printf("\nThe output complex matrix using cblas_cimatcopy:\n");
	for (i = 0; i < N; i++)
	{
		for (j = 0; j < M; j++)
			printf("%4.1f+%4.1fI ", in[i * 2 * M + 2 * j],	in[i * 2 * M + 2 * j + 1]);
		printf("\n");
	}
}`
![2](https://cloud.githubusercontent.com/assets/19662080/15702887/04e40da8-2815-11e6-8566-fa5258de2007.png)

**Comment by FlyHighInSky** [comment] 2016-06-01 08:31
The MKL fucntion **mkl_comatcopy** and **mkl_cimatcopy**, and OpenBLAS function **cblas_comatcopy** get correct results, but the **cblas_cimatcopy** fails.

**Comment by FlyHighInSky** [comment] 2016-06-16 03:57
@brada4 Er, I'll take time to check the algorithm and code, and poster the results.

**Comment by brada4** [comment] 2016-06-16 06:36
it is actually 2x omatcopy... I wonder why it could fail

**Comment by MigMuc** [comment] 2016-10-03 15:42
I can reproduce the results from above with cblas_cimatcopy. The kernel calls an out-of-place routine.
The first call copies the values to an array b then it copies the values back into a. Here is where I think its not working. Here is what I have done:

`240    OMATCOPY_K_RT(*rows, *cols, alpha[0], alpha[1], a, *lda, b, *ldb );
 241    //OMATCOPY_K_RN(*rows, *cols, (FLOAT) 1.0, (FLOAT) 0.0 , b, *ldb, a, *ldb );
 242      OMATCOPY_K_RN(*cols, *rows, (FLOAT) 1.0, (FLOAT) 0.0 , b, *ldb, a, *ldb );
 243    free(b);`

I changed the order of the rows and columns in the call to OMATCOPY_K_RN.
Now it works. Probably there are other places which have to be changed accordingly.

**Comment by martin-frbg** [comment] 2016-10-05 09:22
I notice that @wernsaar lamented a lack of test cases when he set out to implement the XXmatcopy extensions in #51

**Comment by martin-frbg** [comment] 2017-07-19 12:24
Sadly the fix suggested above does not appear to be a complete or general solution. In particular when only a submatrix of the input is to be transposed (as is done in the test case that comes with MKL) the current implementation appears to affect unrelated matrix elements as well.

**Comment by martin-frbg** [comment] 2017-07-19 20:28
Actually I now think the problem is twofold - (1) the OMATCOPY_K_RN calls need to get their rows and cols parameters interchanged as suggested above (and for all four cases involving "Trans") and (2) the  "NEW_IMATCOPY" optimization that was added later to allow in-place operation when source and destination LDA are the same does not cope with operations on submatrices.

**Comment by martin-frbg** [comment] 2017-07-19 20:46
@grisuthedragon I think the NEW_IMATCOPY was your work - wonder if you could check if my assumption above makes sense ?

**Comment by grisuthedragon** [comment] 2017-07-31 09:21
Sorry for my delay but I was away for the last two weaks. I took a look in your fix and run a few examples with it and it works for my. And you are right with the assumptions that the NEW_IMATCOPY only works if rows == cols and lda == ldb. It is still not the fastest  implementation as also mentioned by #1243 but I do not have time to port my more efficient implementation to a OpenBLAS style routine.

**Comment by martin-frbg** [comment] 2017-07-31 15:41
Thanks for the feedback. I will close this issue then as the immediate problem appears to be resolved. I hope to find time to explore the suggestions from #1243 in the near future.

**Closed** 2017-08-01 12:25 UTC
