### ISSUE TITLE
GCC 9 doesn't support SVE2

### ISSUE THREAD

**Issue by giordano** [xianyi/OpenBLAS#3809] opened 2022-11-08 23:26 UTC
Judging by release notes of [GCC 9.4](https://www.gnu.org/software/gcc/gcc-9/changes.html) and [GCC 10](https://www.gnu.org/software/gcc/gcc-10/changes.html) it looks like support for SVE2 was introduced in the latter series, but https://github.com/xianyi/OpenBLAS/blob/934a0e5397f04e215573d8288a9f575bd7040e82/Makefile.arm64#L125-L128 assumes SVE2 is already available in GCC 9.4.  Someone reported having troubles building OpenBLAS with Spack using GCC 9.5, running into the
```
invalid feature modifier 'sve2' in '-march=armv8.5-a+sve+sve2+bf16'
```
error, which confirms the hypothesis that GCC 9 never supported SVE2.

**Comment by martin-frbg** [comment] 2022-11-09 06:35
duplicate of #3805

**Closed as completed by martin-frbg** 2022-11-09 06:35 UTC
