### ISSUE TITLE
OpenBLAS 0.3.8 causes R regression test to fail on arm64

### ISSUE THREAD

**Issue by Thra11** [xianyi/OpenBLAS#2496] opened 2020-03-07 14:59 UTC
When building R 3.6.2 on aarch64/arm64 with OpenBLAS 0.3.7, all tests pass (with one exception believed to be an R bug: it is unlikely to be related to this issue). With OpenBLAS 0.3.8 (and 0.3.9), there is a test failure in the R test `tests/reg-examples2.R` (full output of failed test attached):
```
prcomp> pZ <- prcomp(Z, tol = 0.1)
Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x'
Calls: example ... withVisible -> eval -> eval -> prcomp -> prcomp.default -> svd
Execution halted
```
I am assuming that this could be an OpenBLAS bug, simply because it appeared when upgrading OpenBLAS. However, it's always possible that changes in OpenBLAS have actually revealed a bug in R.

I tried to git bisect the commits to OpenBLAS between 0.3.7 and 0.3.8. The results weren't conclusive, as some commits caused other R test failures, which may or may not be related, and I haven't had time to try again only running the test I'm interested in (R does not continue to run other tests after a test failure). However, it looks like it may have been [this commit](https://github.com/xianyi/OpenBLAS/commit/aeef942c4f2a17099d82307d482abdec53bd3fbd) which caused the test to break.

### System
RK3399 (2 x Cortex-A72 + 4 x Cortex-A53) SoC running NixOS Linux.

To avoid the R bug mentioned above, you can either apply [this patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/math/R/0001-Disable-test-pending-upstream-fix.patch) to comment it out, or only run `tests/reg-examples2.R`

**Comment by Thra11** [comment] 2020-03-07 15:02
[reg-examples2.Rout.fail.txt](https://github.com/xianyi/OpenBLAS/files/4301977/reg-examples2.Rout.fail.txt)

**Comment by martin-frbg** [comment] 2020-03-07 15:48
Thanks, building R-3.6.3 on my raspi now. I take it reverting that patch (i.e. going back to the generic C implementation of gemm-beta in KERNEL.ARMV8) fixed the problem for you ?

**Comment by brada4** [comment] 2020-03-07 19:24
Is it R bug that repeats with their included netlib BLAS or aomething that gets introduced adding OpenBLAS to R setup?

**Comment by martin-frbg** [comment] 2020-03-07 19:32
Can't tell yet - my first build attempt ended with an assertion in test 1.d (i.e., in a different, earlier test) irrespective of what libRblas linked to but I may have done something wrong.

**Comment by Thra11** [comment] 2020-03-07 21:08
@martin-frbg A failure in `tests/reg-tests-1d.R` is probably the separate R bug I referred to ([reported upstream](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17718)). I don't think it's related to OpenBLAS, but it causes R to stop before getting to the test we're interested in.

I tried reverting just the single gemm-beta commit, but it still fails, so either it's more involved than that, or that was a red herring.

**Comment by martin-frbg** [comment] 2020-03-07 21:35
Ah yes, that is exactly the same symptom, should have looked at your earlier links. Unfortunately my raspi appears to have dropped from the network now (probably overheated and crashed) and I will be away from it until monday.

**Comment by Thra11** [comment] 2020-03-07 22:29
> I tried reverting just the single gemm-beta commit, but it still fails, so either it's more involved than that, or that was a red herring.

After the failure, I reran it because I'd forgotten to tell it to keep the failed build output. It then succeeded, so I reran it twice more; both failed. So there may be some some non-determinism there somewhere.

**Comment by martin-frbg** [comment] 2020-03-07 22:41
Well, there was that one issue with a misplaced memory barrier in the level3 blas code that could cause intermittent failure through a race condition, but that was (believed to have been) fixed immediately before the 0.3.9 release.

**Comment by brada4** [comment] 2020-03-08 07:30
Exact R code from `? prcomp`
```
#!/usr/bin/Rscript
# options(matprod="internal")
# options(matprod="blas")
# options(matprod="default.simd")

C <- chol(S <- toeplitz(.9 ^ (0:31))) # Cov.matrix and its root
all.equal(S, crossprod(C))
set.seed(17)
X <- matrix(rnorm(32000), 1000, 32)
Z <- X %*% C  ## ==>  cov(Z) ~=  C'C = S
all.equal(cov(Z), S, tol = 0.08)
pZ <- prcomp(Z, tol = 0.1)
summary(pZ) # only ~14 PCs (out of 32)
## or choose only 3 PCs more directly:
pz3 <- prcomp(Z, rank. = 3)
summary(pz3) # same numbers as the first 3 above
stopifnot(ncol(pZ$rotation) == 14, ncol(pz3$rotation) == 3,
          all.equal(pz3$sdev, pZ$sdev, tol = 1e-15)) # exactly equal typically
```
As it says in `? svd`
>     The main functions used are the LAPACK routines ‘DGESDD’ and ‘ZGESDD’.

There is no value validity test in DGESDD
But ther is GEMM in crossprod which may produce broke input.

@Thra11 could you test with various `options(matpord=****)` values ?

Also if "stable" R-3.5.3 does change anything.

**Comment by Thra11** [comment] 2020-03-08 14:29
[reg-examples2.internal.Rout.txt](https://github.com/xianyi/OpenBLAS/files/4303311/reg-examples2.internal.Rout.txt)
[reg-examples2.blas.Rout.txt](https://github.com/xianyi/OpenBLAS/files/4303312/reg-examples2.blas.Rout.txt)
[reg-examples2.default.simd.Rout.txt](https://github.com/xianyi/OpenBLAS/files/4303313/reg-examples2.default.simd.Rout.txt)
(Succeeds with matprod=internal. Both matprod=blas and matprod=default.simd fail.) This is R 3.6.2 with OpenBLAS 0.3.9.

**Comment by Thra11** [comment] 2020-03-08 15:14
R-3.5.3 with OpenBLAS 0.3.9 exhibits the same failure.

**Comment by brada4** [comment] 2020-03-08 17:02
We take out R-3.5.3 as the problem appears on fixed version of R flipping OpenBLAS from 0.3.7 to 0.3.8.

Deeper explanation - R's own code path has no problems, something goes amiss when we get to BLAS calls.

Could you check setting internal at the beginning and then blas or default right before prcomp call? EDIT2 - and vice versa?

If it is not too much burden - could you check R with their builtin reference BLAS. I am pretty sure no problem with it, but anyway.

**Comment by Thra11** [comment] 2020-03-08 17:56
I seem to get different results depending whether I use the example function:
```
example(prcomp, run.donttest = FALSE)
```
versus running the code from the prcomp example directly (As quoted by @brada4 above). Is `example` running the code in a slightly different environment which causes it to show the failure?

**Comment by Thra11** [comment] 2020-03-08 18:10
Also,
```
options(matprod="blas")
example(prcomp, run.donttest = FALSE)
```
isn't deterministic. Running it 20 times produced 4 successes. (Having discovered this, I ran it 20 times with matprod="internal" and matprod="default.simd", just in case it was a fluke that it succeeded: internal: 20/20 successes, default.simd: 10/20 successes)

**Comment by martin-frbg** [comment] 2020-03-08 18:14
What build options did you use on 0.3.7 and 0.3.8/9 ? Non-deterministic results would seem to suggest a race condition.

**Comment by Thra11** [comment] 2020-03-08 18:36
The Nix expression which configures openblas is [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/science/math/openblas/default.nix) (Not sure how useful that is if you're not familiar with NixOS)

This results in the following:
```
build flags: SHELL=/nix/store/j214228g34l2fdwajnfyd890akk537i5-bash-4.4-p23/bin/bash BINARY=64 CC=cc CROSS=0 DYNAMIC_ARCH=1 FC=gfortran HOSTCC=cc INTERFACE64=0 NO_BINARY_MODE=0 NO_SHARED=0 NO_STATIC=1 NUM_THREADS=64 PREFIX=/nix/store/qv3dv1q8hq1kp7y67wix1pcl8m56865m-openblas-0.3.9 TARGET=ARMV8 USE_OPENMP=1
```

**Comment by Thra11** [comment] 2020-03-08 19:03
Besides a race condition, I also wondered whether the heterogeneous cores could be another source of non-determinism (i.e. whether a certain piece of code gets run on the Cortex-A72 cores or the Cortex-A53 cores).

**Comment by martin-frbg** [comment] 2020-03-08 19:16
That is another possibilty, although the two relevant KERNEL files (ARMV8 and CORTEXA57) are a lot more similar than a diff suggests. On the other hand, the grand reassignment of ARM64 core identities happened in 0.3.5, so predates both the "working" and "non-working" versions.

**Comment by Thra11** [comment] 2020-03-08 19:44
I just tried using `taskset --cpu-list` to restrict the test to a single core. Testing each core in turn, it looks like it consistently fails on cpu's 0-3 (A53), and consistently succeeds on cpus 4-5 (A72).

**Comment by martin-frbg** [comment] 2020-03-08 20:58
Strange. From param.h, both A53 and A72 have same GEMM_UNROLL parameters so should use same kernels. (A53 will use special tcopy routines, but only for SGEMM - and R should certainly be DGEMM). Only other difference would appear to be the respective `-mtune=cortexa??` from Makefile.arm64

**Comment by brada4** [comment] 2020-03-09 14:09
Sometimes non-deterministic resulta are about uninitialized variables and preceding polluted heap.

* Does it work setting `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 Rscript whatever`

**Comment by martin-frbg** [comment] 2020-03-09 20:50
~~It looks as if removing the -mtune=cortexa53 in Makefile.arm64 is sufficient to remove the failure. Of course this in itself does not tell us if this is a gcc bug (gcc 8.3.0 in my test) or a sign of disregard for some A53 peculiarity in any of the kernels used across several ARMV8 platforms.~~
Well, scratch that.. I probably left out the TARGET=CORTEXA53 on that particular build.

**Comment by brada4** [comment] 2020-03-10 01:09
@Thra11 I think for the package you can undo the "KERNEL" part of the commit you identified and since it is visible try again at 0.3.10 without patch....

**Comment by martin-frbg** [comment] 2020-03-10 06:51
@brada4 he already wrote that reverting the gemm_beta commit did not help...

**Comment by brada4** [comment] 2020-03-10 08:39
@martin-frbg still no idea if 1-thr version succeeds in general or depending on bigsmall core type involved.

**Comment by martin-frbg** [comment] 2020-03-10 21:47
Starting to look as if it is the new DGEMM_BETA from @Zeyiii 's #2340 after all - at least I get reproducible successes and no failures in the R check with DGEMM_BETA commented out in KERNEL.ARMV8 and a TARGET=CORTEXA53 build (on a 4x A72 board). Haven't spotted where in the code it could go wrong though...

**Comment by martin-frbg** [comment] 2020-03-30 08:21
Weird. I can find nothing wrong with the dgemm_beta code, and putting back the generic C implementation shows nothing special in the way it is called from R, just small values of m and n and a beta of zero. Plugging the same into the DGEMM case of BLAS-Tester invariably passes the test.

**Comment by martin-frbg** [comment] 2020-03-30 22:24
Actually rewriting the code that sets the vector registers to zero seems to fix it, suggesting that something was feeding us NaNs.

**Closed as completed** 2020-03-31 18:53 UTC
