### ISSUE TITLE
problem building OpenBlas with CMAke GUI and MS Visual studion 2017

### ISSUE THREAD

**Issue by jbensabat** [xianyi/OpenBLAS#2472] opened 2020-03-01 10:11 UTC
Hello
I have used CMAKE 3.14.x GUI to configure and build OpenBlas with MS Visual Studio 2017
It generates a workspace and then I can compile all of the libraries 
when building the openblas_utest project I get two linking errors

2>test_potrs.obj : error LNK2019: unresolved external symbol zpotrs_ referenced in function __ctest_potrf_bug_695_run
2>openblas.lib(lapacke_dgesvd_work.obj) : error LNK2019: unresolved external symbol dgesvd_ referenced in function LAPACKE_dgesvd_work
2>C:\software\openblas\build\utest\openblas_utest.exe : fatal error LNK1120: 2 unresolved externals
2>Done building project "openblas_utest.vcxproj" -- FAILED.

Digging a little bit into it I see that the workspace does not build the fortran files , even if intel fortran is installed in my computer.

Any help is welcome 
best
jac

**Comment by martin-frbg** [comment] 2020-03-01 11:17
Did you specify any options in the cmake configure step ? (I must admit I am not familiar with the windows cmake gui. There are some instructions floating around that suggest -DNOFORTRAN=1 which obviously would not be what you want, but if you cut&pasted from somewhere they could have slipped in). Perhaps try setting CMAKE_Fortran_COMPILER to ifc instead of letting cmake autodetect compilers.

**Comment by martin-frbg** [comment] 2020-03-01 15:36
>  Perhaps try setting CMAKE_Fortran_COMPILER to ifc

Actually a poor suggestion, should have written **ifort** - "ifc" on Windows appears to be an unrelated component of VS on Windows (while on Linux it used to be a synonym for ifort). As far as I can tell https://gitlab.kitware.com/cmake/cmake/issues/17752  was fixed in cmake 3.12 though

**Comment by jbensabat** [comment] 2020-03-01 16:33
Hi
this resolved the problem. The CMakelists does not include the path to the fortran compiler nor it includes a function to detect it. 
I just put the following entry 

CMAKE_fortran_Compiler=C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/bin/intel64/ifort.exe

which is the path to the fortran compiler in my computer 
best
jac

**Comment by martin-frbg** [comment] 2020-03-01 16:47
Thanks for the feedback. In theory, CMAKE_Fortran_Compiler should have been figured out by cmake itself, possibly this is not done right. (cmake/f_check.cmake has enable_language(Fortran) but maybe there should be an explicit check_language(Fortran) before it and the current code only works "by accident" when FC happens to be predefined or something...)

**Comment by brada4** [comment] 2020-03-02 06:22
Is it cmake-gui.exe ?
Could you show options you selected?

**Comment by martin-frbg** [comment] 2020-03-03 16:36
As far as I can tell, cmake relies on predefined environment variables to select the compilers. Hardcoding a path in CMakelists.txt clearly makes no sense when it may vary from one installation to another, but the CMake GUI should be offering you an option to specify the system compilers (on the second screen, after hitting _Configure_ )

**Comment by jbensabat** [comment] 2020-03-08 08:01
Hello
I have now another issue. CMAKE generates a number of workspaces. One of them is openblas, which includes a mix of fortran and c files. MSVC does not allow this mixing and therefore does not compile the fortran files. Then during linking the lapack files are missing (as they are in fortran).
In order to resolve the problem, there is a need to extract the fortran files and compile them into a separate lib, and we must provide the way to enable calling the routines from c. 
another way would be to use the clapack the c version of lapack. 
any idea and or suggestion ?
thanks 
jac

**Comment by brada4** [comment] 2020-03-08 08:15
You need a fortran compiler to compile LAPACK. You can find outdated binaries around the web if compiler does not serve you.

**Comment by jbensabat** [comment] 2020-03-08 08:41
I have the intel visual fortran and it is recognized and tested by cmake 
but still during the build of the openblas lib the fortran files are not compiled 
jac

**Comment by martin-frbg** [comment] 2020-03-08 09:15
I have not tested this combination yet. Maybe something in this thread helps:
https://discourse.cmake.org/t/how-to-set-up-compilation-with-intel-fortran-compiler-on-windows-correctly/532/8

**Comment by martin-frbg** [comment] 2020-03-19 14:15
Reproduced the problem now (with the Ninja setup described in the Wiki), though I do see the fortran files getting compiled with ifort, it is "only" at link time that the symbols cannot be found. Strangely, dumpbin appears to confirm they are present as External in the library, possibly there is something wrong with f_check.cmake setting BUNDERSCORE to expect one trailing underscore on the symbol name.
Update: compiler detection in fc.cmake is wrong, should match on IFORT not INTEL. Also ifort seems to default to uppercase symbol names while clang-cl apparently uses lowercase. And somewhere in this mess, MSVC gets set although not building with VS as such, which prevents
test and ctest from getting built. Will try to unravel that tomorrow.

**Comment by jbensabat** [comment] 2020-04-06 09:09
hello 
back to this thanks
will try now

**Comment by jbensabat** [comment] 2020-04-16 06:10
Hello 
I tried and failed. The lapack fortran is not compiled and therefore the lib is not complete.
I tried building with conda3 and while the process is obscure it worked.
I was able to create a static library in debug and release but not a dll 
is it possible to create a dll this way ?
thanks 
jac

**Comment by martin-frbg** [comment] 2020-04-16 07:09
It should be possible to create a dll by setting -DBUILD_SHARED_LIBS=ON in cmake.

**Comment by jbensabat** [comment] 2020-04-16 07:23
Hi
I tried that but I got an error claiming that the script was not build for dll

**Comment by brada4** [comment] 2020-04-16 07:32
Could you elaborate with accurate error text/messagebox ?

**Comment by jbensabat** [comment] 2020-04-16 07:33
Hi
I shall try rebuilding again and fetch the error message

**Comment by brada4** [comment] 2020-04-16 12:59
You can rerun last build command that produces the error, no need to go through full build.

**Comment by jbensabat** [comment] 2020-04-17 06:19
Hello
tried to build the dll and I got the following error message

ninja: error: '/FORCE:MULTIPLE', needed by 'lib/openblas.dll', missing and no known rule to make it

**Comment by martin-frbg** [comment] 2020-04-17 07:46
Are you trying to build with ReLAPACK included ? This is the only case I can think of where we use `target_link_libraries(${OpenBLAS_LIBNAME} "/FORCE:MULTIPLE")` as ReLAPACK overloads some generic LAPACK functions.
Possibly this line (in the toplevel CMakeLists.txt) needs to be `append_property_string(TARGET $(OpenBLAS_LIBNAME)  LINK_FLAGS "/force:multiple")` - at least this seems to be how others are passing this option.

**Comment by jbensabat** [comment] 2020-04-17 07:49
yes I have set to build ReLAPACK 
will try now 
best
jac

**Comment by preksha12** [comment] 2020-04-17 07:51
Hello ,
I am getting below problem in theano. I am working with python3.6 on CentOS in SSH.
<img width="578" alt="Screenshot 2020-04-16 at 10 08 43 PM" src="https://user-images.githubusercontent.com/9927293/79545466-58297c00-80ae-11ea-8d9c-b5b8dc69afa0.png">

**Comment by jbensabat** [comment] 2020-04-17 07:55
hi tried 
did not work

**Comment by jbensabat** [comment] 2020-04-17 07:59
actually it is working (after I deleted the content of the build directory
thanks
jac

**Comment by martin-frbg** [comment] 2020-04-17 08:01
@jbensabat what did you try? Building without ReLAPACK, or changing the line in CMakeLists.txt ?
@preksha12 please do not just dump totally unrelated questions into a random topic. All I can tell from that screenshot is that your theano installation cannot find a BLAS module, please review the installation instructions for theano and ask there.

**Comment by jbensabat** [comment] 2020-04-17 08:03
I tried without RELAPACK and after cleaning the build directory 
jac

**Closed as completed** 2020-04-21 18:26 UTC
