### ISSUE TITLE
releasing proper tarballs

### ISSUE THREAD

**Issue by dimpase** [xianyi/OpenBLAS#1891] opened 2018-11-29 19:31 UTC
The current automatically made by GitHub release tarballs are not stable; they actually change (a bit) with the changes in the repo. (and so md5 hashes change, breaking various systems that use such hashes for consistency checks). However, there is always a possibility to upload a custom made release tarball, which would be also properly named, so that `wget`ing it would not need subsequent renaming, one can get better compression (bz2/xz, etc).

It would be great to have them, it's only a minor hassle for the release manager (click on Edit release, upload the tarball).

**Comment by dimpase** [comment] 2018-11-29 19:34
E.g. the current release tarball has md5 `30e2f8d7317e84dde5a37152173848f1`, while it used to be `7688cfbf657b348d510d9b56137ace40`. Cf. 
https://trac.sagemath.org/ticket/26052#comment:10

**Comment by dimpase** [comment] 2018-11-29 19:37
That's how a releases page of a project with custom tarballs looks like:
https://github.com/ivmai/bdwgc/releases

**Comment by martin-frbg** [comment] 2018-11-29 20:40
From my (admittedly limited) understanding the hashes would only change when github applies some git patch that affects hash generation. (https://github.com/Homebrew/homebrew-core/issues/18044). (At least as far as I am aware there is nothing in OpenBLAS that actively modifies file content at or after release time to write e.g. a hash or date to one of the source files on the release branch). I am not aware that the OpenBLAS pages specify a particular hash for any version of the autogenerated tarballs either.
Having one custom and one automatic tarball with practically identical content but different hashes
on the release page does not look that good to me either (nor does any extra hassle and possibility for mistakes at release time, frankly).
Perhaps what you could do is download from the sourceforge archive that automagically receives a copy of both zip and tarball through some scripting beyond my control (I do not own the project), which I expect will not re-run whenever github changes anything in the background.

**Comment by dimpase** [comment] 2018-11-29 20:56
Certainly, as openblas is not autoconf-based, the urgency of having custom
tarballs (that run without autotools installed) is not there.

However, the GitHub tarball naming is not convenient for automation, as I
already said, and relying on sourceforge for tarballs does not seem like a
good idea (they want to show you ads, and make their URL atrocious...)

You might still consider generating a custom tarball which is compressed
with bzip2 or xz. Please...

**Comment by brada4** [comment] 2018-11-29 20:56
wget does not show ads

**Comment by dimpase** [comment] 2018-11-29 21:05
SF used to change URLs to prevent you from wgetting things

**Comment by brada4** [comment] 2018-11-29 21:27
[They claim not since 2011](https://sourceforge.net/p/forge/documentation/Downloading%20files%20via%20the%20command%20line/)
btw md5...40 file is still there. 
I know they at once threw ad-laden downloader in front of windows .exe installers, but you verify checksums against such outcome.

**Comment by dimpase** [comment] 2018-11-29 22:43
> btw md5...40 file is still there.

Great, and how on Earth  can one say it's not a hacked tarball, without actually untarring and diffing against your git repo, as it now has a different md5 from your supposedly canonical tarball? Do you see now why it's desirable to have a canonical tarball?

**Comment by martin-frbg** [comment] 2018-11-30 07:01
If you are going to be paranoid about archive integrity, perhaps you should look into distributing a "verified" copy of OpenBLAS with your project ? If you assume either the OpenBLAS project account or github itself could get hacked, I do not see how any checksum posted with an archive there could be expected to remain trustworthy.

**Comment by dimpase** [comment] 2018-11-30 08:17
We trust you with integrity of your repo and releases you make. But we need
means to check that tarballs you cut don't get corrupted in transmission
(or worse). And this does not work with the present scheme, as we have no
quick means to distinguish between the harmless github-induced changes of
hashes and ones we need to worry about.

**Comment by brada4** [comment] 2018-11-30 08:24
@dimpase you can use other checksum that is not suspectible to collision attack, which is not applicable to compresed files anyway, it is applicable to altering whitespace to compensate for changing some text. Indeed you are free to diff against source tree used.

It is not the first time github changes compression, since then all download links go to sf\.net to avoid scaring people.

If you have chance you can host distribution file properly with multiple checksums, re-compressed with zopfli (-10%) bzip2 (-50%) xz (-70% size) or .pax.Z (+80%) , we certainly do not modify those files after release.

**Comment by martin-frbg** [comment] 2018-11-30 09:42
@brada4 if you are alluding to #504 I think that may have been a different problem (though there is no way of knowing for sure). Interesting that there apparently has been no problem with the checksum of the OpenBLAS release tarballs for JuliaLang since then. @ararslan ?

**Comment by dimpase** [comment] 2018-11-30 10:18
> you can use other checksum

we are using a combination of md5, sha1, and a custom crc32-based checksum to ensure authenticity of tarballs (and we [mirror them](http://www.sagemath.org/download-packages.html) once a release is made). But we need to start somewhere, and a tarball that is changing over time is a non-starter. I reckon that out of dozens github-released packages we use, openblas is the only one that only does the default GitHub fluid tarballs as their releases. 

> download from the sourceforge archive that automagically receives a copy of both zip and tarball through some scripting beyond my control (I do not own the project)

You are sending me to a resource you don't control as the primary source for your releases. This looks quite fragile and potentially error-prone to me.

**Comment by brada4** [comment] 2018-11-30 12:32
sourceforge does not change file contents behind same names. 
I would suggest
1/ detect release in github
2/ verify that it is same on sf\.net and use that OR
3/ publish your re-compressed version thereof
If something fails in current distribution arrangement feel free to share, yes, you are sent to sf\.net for release files that do not nibble behind the scenes. 
If you have solution at zero budget, feel free to share.

**Comment by dimpase** [comment] 2018-11-30 12:49
> If you have solution at zero budget, feel free to share

uploading to github a custom tarball,in addition to making a github release, takes about 30 seconds of the
release manager time (and is free otherwise). It can also be scripted through a CI system, I gather.

**Comment by brada4** [comment] 2018-11-30 15:28
You will have to change download link to get stable file either way.

**Comment by dimpase** [comment] 2018-11-30 17:08
> You will have to change download link to get stable file either way.

Sorry, I don't follow you here. Open releases tab, select a release, click on Edit in the right top corner. You'll see a prompt saying "Attach binaries by dropping them there or selecting them". Upload the tarball you created, click "Update release", done. Now you have sane URL, wgettable etc., to use for the tarball, not messed up by GitHub.

**Comment by ararslan** [comment] 2018-11-30 21:10
> Interesting that there apparently has been no problem with the checksum of the OpenBLAS release tarballs for JuliaLang since then.

Yeah, we've gotten no reports of checksum mismatches for OpenBLAS. Though I should note that Julia source builds keep the OpenBLAS tarball in the build tree so it doesn't have to be re-downloaded and checksummed, so the only time someone could encounter a checksum mismatch is when doing a fully clean build, like from a fresh clone or after `git clean -fdx`. That said, I did that myself just yesterday and had no problems.

**Comment by dimpase** [comment] 2018-12-02 10:16
@ararslan - could be that Julia did the bump-up to the new openblas at the moment when the hash change has already happened (it's not very frequent)?

**Comment by ararslan** [comment] 2018-12-03 00:24
Apparently I raised the OpenBLAS version Julia uses on 30 October (https://github.com/JuliaLang/julia/pull/29845). I don't know when the hash changed, but the MD5 for the version used by is `7688cfbf657b348d510d9b56137ace40`, and I didn't encounter checksum mismatches when I last did a clean build. (I did another yesterday on a different system.)

**Comment by brada4** [comment] 2018-12-03 07:50
@ararslan the problem is that github sometimes changes compression trimming few bytes from resulting files (still 10% bigger than with zopfli), thats why release links go to sf.net (thats in bottom of notes) while the top 2 items above notes will nibble behind the interface.

**Comment by martin-frbg** [comment] 2020-12-12 22:50
closing as I remembered to upload md5sum'd copies for the last three releases now

**Closed as completed by martin-frbg** 2020-12-12 22:50 UTC
