### ISSUE TITLE
Fortran configuration incorrectly assumes "IBM" ident string means IBM XLF

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#917] opened 2016-06-27 16:48 UTC
In  f_check, OpenBlas executes
gfortran -O2 -S ftest.f > /dev/null 2>&1 && cat ftest.s && rm -f ftest.s

then uses the output and scrapes looking for keywords.   The output from that code on PPC64LE Ubuntu Linux contains 
"    .ident    "GCC: (Ubuntu/IBM 5.3.1-14ubuntu2.1) 5.3.1 20160413""

f_check then assumes that the fortran compiler is "IBM"  and applies the xlf flags q64 and -openmp instead of -m64 -fopenmp.

**Comment by edelsohn** [comment] 2016-06-27 17:51
The bug appears to be in cmake/fc.cmake.  It currently tests

if (${F_COMPILER} STREQUAL "IBM")

This probably should be changed to something like

if (${F_COMPILER} STREQUAL "IBM XL")

**Comment by dllehr81** [comment] 2016-07-02 16:02
i believe the fix suggested above will fix another issue where -lgfortran isn't included in the build command.  This is needed by frameworks using openBlas, such as caffee.

**Comment by brada4** [comment] 2016-07-03 22:10
The regression is introduced by adding trade name to unrelated compiler ID string
GCC: (Ubuntu/IBM 5.3.1-14ubuntu2.1) 5.3.1 20160413
It is a marketing plot (i.e addition to break other software on top of gcc.gnu.org) on par of ex-competing company  who once bought a virtualisation company and named the virtualized processor SPARC-X86.

**Comment by hartb** [comment] 2016-07-06 22:52
Howdy! I believe the .ident string is coming (at least in part) from the --with-pkgversion option used when the tool chain was built. The inclusion of "IBM" there may have been Canonical's choice (note the "Ubuntu" also in the string). IBM has a team that contributes to GCC, but they weren't aware of why that string was chosen. I've asked one of the IBM folks who works with Canonical. Will update when I hear back.

**Comment by leitao** [comment] 2016-07-07 13:12
You shouldn't rely on grepping IBM on the .ident field in order to check if it was compiled with IBM XL or GCC. If you want to do so, you can check first for 'gcc', and if it does not match anything, then you can proceed with it.

Anyway, Canonical uses that to match which gcc tree it is using, so, if they are using a standard gcc tree (as for GCC 6), they do not put the mark it as IBM branch. If they switch to the IBM branch, then they use the IBM mark in the ident field.

They are doing the same for ARM, but using the 'linaro' string.

They also did it further in 14.04 version, so, so, depending on the package version, you might have the same issue.

They are open to change that, since this is just a way to give credit to the IBM 'branch', but, I do not thing it makes sense, so, probably it is easier to fix in OpenBLAS.

**Comment by hartb** [comment] 2016-07-07 22:44
@leitao is the person I had asked; thank you!

**Comment by brada4** [comment] 2016-07-08 06:18
Somebody smarter should look into this. Maybe the solution would be making i386 build on amd64 a cross-cpmpilation and never set such flags relying on compiler producing native binary without extta flags.

**Comment by hartb** [comment] 2016-07-12 21:24
I hope this can be addressed with a small change to f_check; maybe tightening the IBM XL signature there similar to @edelsohn's suggestion, or distinguishing GCC/gfortran vs XL in the IBM vendor block.

**Comment by xianyi** [comment] 2016-07-14 20:10
Could you try the fix on Power + Ubuntu?

**Comment by hartb** [comment] 2016-07-15 23:17
Thank you! I'll ask @dllehr81 to test this change with gfortran, and will try to find someone to test with XL Fortran.

**Comment by hartb** [comment] 2016-07-18 22:00
@dllehr81 confirms that the change makes build with gfortran onUbuntu 16.04 (on POWER) work. Thank you!  Will update further when we hear from the XL folks, too.

**Comment by martin-frbg** [comment] 2016-12-23 12:08
May I ask if anything was ever heard from the XL folks (IOW, can this be closed ?)

**Comment by hartb** [comment] 2017-01-05 20:20
I apologize for the long delay. I never got a clear answer about XL. My suggestion would be to close this (the originally-reported problem is fixed) and address any problem with XL in a future issue.

**Comment by martin-frbg** [comment] 2017-01-05 21:25
Thank you. My objective for pestering you (and others) is just my worry that the sheer number of probably solved but still open issues makes it harder to assess both the maturity and any remaining limitations of OpenBLAS.

**Closed by martin-frbg** 2017-01-05 21:25 UTC
