### ISSUE TITLE
Can not found `sgetrf_single` when using OpenBLAS to build dlib

### ISSUE THREAD

**Issue by lhduc94** [xianyi/OpenBLAS#1167] opened 2017-04-25 06:35 UTC
Here is the dlib's make file (`dlib\cmake_utils\cmake_find_blas`) to find BLAS libraries
```
if (NOT blas_found)
    find_library(cblas_lib openblas PATHS ${extra_paths})
    if (cblas_lib)
        set(blas_libraries ${cblas_lib})
        set(blas_found 1)
        message(STATUS "Found OpenBLAS library")
        set(CMAKE_REQUIRED_LIBRARIES ${blas_libraries})
        # If you compiled OpenBLAS with LAPACK in it then it should have the
        # sgetrf_single function in it.  So if we find that function in
        # OpenBLAS then just use OpenBLAS's LAPACK. 
        CHECK_FUNCTION_EXISTS(sgetrf_single OPENBLAS_HAS_LAPACK)
        if (OPENBLAS_HAS_LAPACK)
            message(STATUS "Using OpenBLAS's built in LAPACK")
            # set(lapack_libraries gfortran) 
            set(lapack_found 1)
        endif()
    endif()
    mark_as_advanced( cblas_lib)
endif()
```

And here is the log:

```
...
Found OpenBLAS library
Looking for sgetrf_single
Looking for sgetrf_single - not found
...
```

**Comment by brada4** [comment] 2017-04-25 08:12
Probably you did not have fortran compiler available when compiling OpenBLAS, and lapack was not built.

**Comment by lhduc94** [comment] 2017-04-25 08:25
I don't think it's the problem because I used compiled version ([here](https://sourceforge.net/projects/openblas/files/v0.2.19/OpenBLAS-v0.2.19-Win64-int32.zip/download)). The doc said that lapack is built by default, therefore I don't think I need to build it again. But, maybe I'm wrong

**Comment by martin-frbg** [comment] 2017-04-25 08:45
Not sure what the usual equivalent for the Unix "nm" tool is on Windows, but using it on the dll contained in the zip from sourceforge shows sgetrf_single to be present. Could it be that you have more than one version of OpenBLAS on your system, and cmake picked up the wrong one ?

**Comment by brada4** [comment] 2017-04-25 13:52
nm = dependency walker aka depends.exe

**Comment by brada4** [comment] 2017-04-25 14:11
It exports `sgetrf SGETRF sgetrf_` ,
`sgetrf_single` looks to me like OSX
Can you inquire with dlib if anybody ever succeeded building it on Windows and how?

**Comment by martin-frbg** [comment] 2017-04-25 15:27
Seeing that the original snippet contained the "found OpenBLAS library" I guess the "UNIX or MINGW" branch of that cmakefile was executed...
Might be more interesting to see if the earlier version(s) of xianyi's windows binaries used to export sgetrf_single , if indeed the current one does not.

**Comment by brada4** [comment] 2017-04-25 16:23
sgetrf_single will be exported from OpenBLAS built using visual studio.
https://github.com/xianyi/OpenBLAS/common_lapack.h

You can campain dlib to check some useful/used function instead, and not something specific to sub-par build of OpenBLAS:
https://github.com/davisking/dlib/search?utf8=%E2%9C%93&q=sgetrf_single&type=

**Comment by martin-frbg** [comment] 2017-04-25 16:46
I may be missing something obvious here, but it is not clear to me why this would not be exported by gcc/mingw etc builds ? And I guess sgetrf_single was chosen specifically to identify OpenBLAS.

**Comment by brada4** [comment] 2017-04-25 17:31
OpenBLAS is sort of identified by file name 5 lines ago.... I think it is to distinguish NO_LAPACK build.
@lhduc94 i think you can safely remove that line and if() block borders that follow, dlib will call cblas functions, included in SF downloaded DLL, later according to this same cmake file.  @davisking

**Comment by davisking** [comment] 2017-04-25 19:43
That line is only there because I've encountered users with odd OpenBLAS
installs.  There are a lot of funny things like this in dlib's cmake files
that are there to work around the presence of broken library installs.  I'm
not in love with them.  But people will use systems with some badly
installed library (e.g. a busted install of openblas, libpng, whatever) and
then complain on the dlib forums about it.  The solution is obviously for
them to fix their systems.  But it's a lot easier for me and more user
friendly to users if the cmake scripts somehow work around these problems.

If someone wants to make a PR that fixes whatever is causing you trouble
then I'm fine with that, so long as it doesn't just disable this check
since that will cause some other users to complain.

**Comment by brada4** [comment] 2017-04-25 20:00
You could try openblas_get_corename() to identify OpenBLAS, or/and something like idamax() or idamax_ to see it is BLAS at all.

And plain sgetrf() or sgetrf_() to check presence of lapack? That should work on Linux and Windows both.

I think sgetrf_single is lost in history....

**Comment by davisking** [comment] 2017-04-25 20:53
Well, the problem was people installing OpenBLAS wrong.  So
openblas_get_corename() probably won't work.   Anyway, what's the problem
here?  That it's not enabling LAPACK?

**Comment by brada4** [comment] 2017-04-25 21:18
Apparently just that lapack is not detected/used where it could/should be (i.e good download of latest binary version).
In context of cmake - does it matter that openblas.dll is openblas at all? Maybe it is enough to check few symbols that it is blas and lapack enough to sustain rest of build?

**Comment by davisking** [comment] 2017-04-25 23:12
I suspect that any lapack symbol will work as the check.  I don't remember why I used `sgetrf_single`.  It might have been because that somehow worked around part of the problem or it might have been random.  It's been so long I don't remember.  Although the more I think about it the more I'm thinking it was due to people somehow getting an OpenBLAS install that had a broken/partial copy of LAPACK in it so some symbols might not work as the check.  But don't hold me to that.

**Comment by brada4** [comment] 2017-04-25 23:29
Seen on Linux:
/tmp/dlib/build/dlib/libdlib.so.19.4.99:
ibopenblas.so.0 => cblas_sgemm,cblas_sscal,cblas_saxpy,cblas_strsm,sgetrf_
I dont see windows often, but I would bet checking sgetrf_ presence is enough to distinguish NO_LAPACK variation.
You are not alone #1151 :)

**Comment by davisking** [comment] 2017-04-26 01:31
Yeah, cblas_sgemm is probably better.  @lhduc94 does changing it to check for `cblas_sgemm` fix your issue?

**Comment by brada4** [comment] 2017-05-31 22:49
@lhduc94 - did you check small change (replace sgetrf_single with sgetrf_ in cmake file) proposed on Windows? I can confirm it is perfectly present on Linux (as above)

**Comment by martin-frbg** [comment] 2017-06-29 18:07
@lhduc94 @davisking did you get this sorted in the meantime ? I am not sure this is something that could sensibly be addressed by OpenBLAS developers.

**Comment by davisking** [comment] 2017-06-29 19:56
I've never observed the error or whatever this is exactly.  So I haven't done anything.  It would be great if the users who report this replied though :/

**Comment by brada4** [comment] 2017-06-29 21:33
Would be great to have confirmation that least intrusive change solves problem.

**Comment by martin-frbg** [comment] 2017-09-11 16:08
Closing as not an OpenBLAS problem and no apparent activity from either the original poster or the dlib mainiainer.

**Closed by martin-frbg** 2017-09-11 16:08 UTC
