### ISSUE TITLE
GCC14 issues on loongarch64 and amd64

### ISSUE THREAD

**Issue by azuresky01** [xianyi/OpenBLAS#4805] opened 2024-07-17 11:05 UTC
Hello,

I just tested current develop version of OpenBLAS on Loongson-3A6000 (loongarch64 architecture) and found two issues. The first one also appears on AMD Zen4 7940HS with Debian 12.

 *** The first issue (loongarch64 & amd64):  

many tests in ctest fail for cmake build with GCC14 and setting  INTERFACE64=1:
```
OS:  Loong Arch Linux  or Debian GNU/Linux trixie/sid loongarch64                      
Host: Loongson-3A6000-HV-7A2000-1w-V0.1-EVB                               
Kernel: 6.8.6-2 or 6.9.7-loongarch-00002-gfbf7212b7ab3
gcc version 14.1.0 compiled from the source
cmake version: 3.28.2-1 or 3.30.0
```

compiling and test commands:

```
CC=gcc-14.1.0 FC=gfortran-14.1.0 cmake -B build64 -DBUILD_TESTING=OFF -DINTERFACE64=1
cmake --build build64
cd build64
ctest
```

ctest result:

```
Test project /home/loongson/test/cbuild64/build64
      Start  1: openblas_utest
 1/26 Test  #1: openblas_utest ...................***Exception: SegFault  0.01 sec
      Start  2: openblas_utest_ext
 2/26 Test  #2: openblas_utest_ext ...............***Exception: SegFault  0.01 sec
      Start  3: sblas1
 3/26 Test  #3: sblas1 ...........................Bus error***Exception:   0.03 sec
      Start  4: sblas2
 4/26 Test  #4: sblas2 ...........................   Passed    0.03 sec
      Start  5: sblas3
 5/26 Test  #5: sblas3 ...........................***Failed    0.02 sec
      Start  6: dblas1
 6/26 Test  #6: dblas1 ...........................Bus error***Exception:   0.03 sec
      Start  7: dblas2
 7/26 Test  #7: dblas2 ...........................   Passed    0.03 sec
      Start  8: dblas3
 8/26 Test  #8: dblas3 ...........................***Failed    0.02 sec
      Start  9: cblas1
 9/26 Test  #9: cblas1 ...........................Bus error***Exception:   0.03 sec
      Start 10: cblas2
10/26 Test #10: cblas2 ...........................   Passed    0.03 sec
      Start 11: cblas3
11/26 Test #11: cblas3 ...........................   Passed    0.02 sec
      Start 12: zblas1
12/26 Test #12: zblas1 ...........................Bus error***Exception:   0.03 sec
      Start 13: zblas2
13/26 Test #13: zblas2 ...........................   Passed    0.03 sec
      Start 14: zblas3
14/26 Test #14: zblas3 ...........................***Failed    0.00 sec
      Start 15: xscblat1
15/26 Test #15: xscblat1 .........................Bus error***Exception:   0.03 sec
      Start 16: xscblat2
16/26 Test #16: xscblat2 .........................***Failed    0.03 sec
      Start 17: xscblat3
17/26 Test #17: xscblat3 .........................***Failed    0.03 sec
      Start 18: xdcblat1
18/26 Test #18: xdcblat1 .........................Bus error***Exception:   0.03 sec
      Start 19: xdcblat2
19/26 Test #19: xdcblat2 .........................***Failed    0.03 sec
      Start 20: xdcblat3
20/26 Test #20: xdcblat3 .........................***Failed    0.02 sec
      Start 21: xccblat1
21/26 Test #21: xccblat1 .........................Bus error***Exception:   0.03 sec
      Start 22: xccblat2
22/26 Test #22: xccblat2 .........................***Failed    0.03 sec
      Start 23: xccblat3
23/26 Test #23: xccblat3 .........................***Failed    0.02 sec
      Start 24: xzcblat1
24/26 Test #24: xzcblat1 .........................Bus error***Exception:   0.03 sec
      Start 25: xzcblat2
25/26 Test #25: xzcblat2 .........................***Failed    0.03 sec
      Start 26: xzcblat3
26/26 Test #26: xzcblat3 .........................***Failed    0.03 sec

19% tests passed, 21 tests failed out of 26

Total Test time (real) =   0.65 sec

The following tests FAILED:
	  1 - openblas_utest (SEGFAULT)
	  2 - openblas_utest_ext (SEGFAULT)
	  3 - sblas1 (Bus error)
	  5 - sblas3 (Failed)
	  6 - dblas1 (Bus error)
	  8 - dblas3 (Failed)
	  9 - cblas1 (Bus error)
	 12 - zblas1 (Bus error)
	 14 - zblas3 (Failed)
	 15 - xscblat1 (Bus error)
	 16 - xscblat2 (Failed)
	 17 - xscblat3 (Failed)
	 18 - xdcblat1 (Bus error)
	 19 - xdcblat2 (Failed)
	 20 - xdcblat3 (Failed)
	 21 - xccblat1 (Bus error)
	 22 - xccblat2 (Failed)
	 23 - xccblat3 (Failed)
	 24 - xzcblat1 (Bus error)
	 25 - xzcblat2 (Failed)
	 26 - xzcblat3 (Failed)
```

The failed ctest results here are similar to failed ctest results on AOSC system appearing in issue "https://github.com/OpenMathLib/OpenBLAS/issues/4703". The fix "https://github.com/OpenMathLib/OpenBLAS/pull/4705" seems still working for GCC version before 14. I tested with gcc 13.3.0 & cmake & INTERFACE64=1, everything is fine.

I then tested an amd64 computer and got similar results. See below:

```
OS:  Debian GNU/Linux 12 (bookworm) x86_64
Host:  AMD Zen4 R9 7940HS                            
Kernel: 6.1.0-22-amd64
gcc version 14.1.0 compiled from the source
cmake version:  3.25.1
```
ctest result:

```
     Start  1: openblas_utest
 1/30 Test  #1: openblas_utest ...................***Exception: SegFault  0.01 sec
      Start  2: openblas_utest_ext
 2/30 Test  #2: openblas_utest_ext ...............***Exception: SegFault  0.00 sec
      Start  3: sblas1
 3/30 Test  #3: sblas1 ...........................***Exception: SegFault  0.08 sec
      Start  4: sblas2
 4/30 Test  #4: sblas2 ...........................   Passed    0.09 sec
      Start  5: sblas3
 5/30 Test  #5: sblas3 ...........................   Passed    0.09 sec
      Start  6: dblas1
 6/30 Test  #6: dblas1 ...........................***Exception: SegFault  0.06 sec
      Start  7: dblas2
 7/30 Test  #7: dblas2 ...........................   Passed    0.09 sec
      Start  8: dblas3
 8/30 Test  #8: dblas3 ...........................   Passed    0.09 sec
      Start  9: cblas1
 9/30 Test  #9: cblas1 ...........................***Exception: SegFault  0.08 sec
      Start 10: cblas2
10/30 Test #10: cblas2 ...........................   Passed    0.09 sec
      Start 11: cblas3
11/30 Test #11: cblas3 ...........................   Passed    0.07 sec
      Start 12: cblas3_3m
12/30 Test #12: cblas3_3m ........................***Failed    0.01 sec
      Start 13: zblas1
13/30 Test #13: zblas1 ...........................***Exception: SegFault  0.07 sec
      Start 14: zblas2
14/30 Test #14: zblas2 ...........................   Passed    0.09 sec
      Start 15: zblas3
15/30 Test #15: zblas3 ...........................***Failed    0.01 sec
      Start 16: zblas3_3m
16/30 Test #16: zblas3_3m ........................***Failed    0.01 sec
      Start 17: xscblat1
17/30 Test #17: xscblat1 .........................***Exception: SegFault  0.08 sec
      Start 18: xscblat2
18/30 Test #18: xscblat2 .........................   Passed    0.01 sec
      Start 19: xscblat3
19/30 Test #19: xscblat3 .........................   Passed    0.01 sec
      Start 20: xdcblat1
20/30 Test #20: xdcblat1 .........................***Exception: SegFault  0.06 sec
      Start 21: xdcblat2
21/30 Test #21: xdcblat2 .........................   Passed    0.01 sec
      Start 22: xdcblat3
22/30 Test #22: xdcblat3 .........................   Passed    0.01 sec
      Start 23: xccblat1
23/30 Test #23: xccblat1 .........................***Exception: SegFault  0.08 sec
      Start 24: xccblat2
24/30 Test #24: xccblat2 .........................   Passed    0.01 sec
      Start 25: xccblat3
25/30 Test #25: xccblat3 .........................   Passed    0.01 sec
      Start 26: xccblat3_3m
26/30 Test #26: xccblat3_3m ......................   Passed    0.01 sec
      Start 27: xzcblat1
27/30 Test #27: xzcblat1 .........................***Exception: SegFault  0.06 sec
      Start 28: xzcblat2
28/30 Test #28: xzcblat2 .........................   Passed    0.01 sec
      Start 29: xzcblat3
29/30 Test #29: xzcblat3 .........................   Passed    0.02 sec
      Start 30: xzcblat3_3m
30/30 Test #30: xzcblat3_3m ......................   Passed    0.01 sec

57% tests passed, 13 tests failed out of 30

Total Test time (real) =   1.30 sec

The following tests FAILED:
	  1 - openblas_utest (SEGFAULT)
	  2 - openblas_utest_ext (SEGFAULT)
	  3 - sblas1 (SEGFAULT)
	  6 - dblas1 (SEGFAULT)
	  9 - cblas1 (SEGFAULT)
	 12 - cblas3_3m (Failed)
	 13 - zblas1 (SEGFAULT)
	 15 - zblas3 (Failed)
	 16 - zblas3_3m (Failed)
	 17 - xscblat1 (SEGFAULT)
	 20 - xdcblat1 (SEGFAULT)
	 23 - xccblat1 (SEGFAULT)
	 27 - xzcblat1 (SEGFAULT)
```
Again, when I tested with gcc 12.2.0-14 & cmake & INTERFACE64=1, everything is fine. For some reason "INTERFACE64=1" setting does not work well for GCC14 and cmake combination. 

If I do not set "-DINTERFACE64=1" in cmake command, on both architectures with GCC14 and cmake combination I met no error.

%%%%%%%%%%%%%%%%%%%%%%%%%

*** the second issue (loongarch64 only):

One test in utest fails for GCC14 and make combinations:
compiling commands: `CC=gcc-14.1.0 FC=gfortran-14.1.0 make` or `CC=gcc-14.1.0 FC=gfortran-14.1.0 make INTERFACE64=1`

In both cases I got `openblas_utest` errors as below:
```
...
TEST 99/103 potrf:smoketest_trivial [FAIL]
  ERR: test_potrs.c:535  L s(0,0) difference: 1.19209e-07
TEST 100/103 potrf:bug_695 [OK]
TEST 101/103 kernel_regress:skx_avx [OK]
TEST 102/103 fork:safety [OK]
TEST 103/103 fork:safety_after_fork_in_parent [OK]
RESULTS: 103 tests (102 ok, 1 failed, 0 skipped) ran in 199 ms
```
 In the file test_potrs.c:534-535 the bound is 1e-5. But the test failed when err=1.19209e-07. This is reported in the issue "https://github.com/OpenMathLib/OpenBLAS/issues/4687" and then disappeared after some fixes. Now it appears again. 

If compiling with GCC before 14, e.g., gcc version 13.3.0, I met no error.

**Comment by azuresky01** [comment] 2024-07-18 04:24
I did some further test today. 

The first issue seems not related to GCC14. On both architectures with system default GCC14:
`Loongson-3A6000: Loong Arch Linux with gcc version 14.0.1 20240421 (experimental) (GCC) `
`AMD Zen4 R9 7940HS: Arch Linux x86_64 with gcc version 14.1.1 20240522 (GCC)`
 the compilation and ctest are OK  for cmake build with the setting INTERFACE64=1. The first issue appears when I use  GCC compiled from the source, not limited to GCC14. So it should not be OpenBLAS issue.

The second issue still hold for  loongarch64 system with the default GCC14.

**Comment by martin-frbg** [comment] 2024-07-18 08:17
I cannot reproduce your first issue here.
Regarding the second issue, I have come to the conclusion that the "failing" potrs utest needs to be rewritten - it combines tests for all four precision types in such a confusing way that a compiler will easily misoptimize it when more than one of BUILD_SINGLE, BUILD_DOUBLE, BUILD_COMPLEX and BUILD_COMPLEX16 is set at compile time (as it is by default)

**Comment by martin-frbg** [comment] 2024-07-18 15:24
Actually this _is_ a bug in gcc-14.1 - the code is a bit hard to read, but the calculation of the differences is straightforward (and the error remains even when I simplify it, have it print the value of "err" before the comparison, etc.). What does help
is putting `#pragma GCC optimize("no-gcse")` at the top of the file.  This bug is probably platform-specific as I have not seen it anywhere else, I have not checked if it is still present in the current tree for gcc15, and I have not reported it.

**Comment by azuresky01** [comment] 2024-07-19 06:28
I can confirm that putting `#pragma GCC optimize("no-gcse")` at the top of test_potrs.c can fix the second issue. 

> Actually this _is_ a bug in gcc-14.1 - the code is a bit hard to read, but the calculation of the differences is straightforward (and the error remains even when I simplify it, have it print the value of "err" before the comparison, etc.). What does help is putting `#pragma GCC optimize("no-gcse")` at the top of the file. This bug is probably platform-specific as I have not seen it anywhere else, I have not checked if it is still present in the current tree for gcc15, and I have not reported it.

**Comment by martin-frbg** [comment] 2024-07-22 21:33
This appears to be already fixed in gcc (i.e. not reproducible with a build of gcc from their current git source tree)

**Closed as completed** 2024-07-23 12:54 UTC
Labels: Bug in other software
