### ISSUE TITLE
dgetf2: fails to return singularity of singular matrix

### ISSUE THREAD

**Issue by kortschak** [xianyi/OpenBLAS#610] opened 2015-08-02 09:01 UTC
We have noticed a problem with the OpenBLAS dgetf2 routine in that it fails to identify a singular matrix as such (see comments in https://github.com/gonum/lapack/pull/22). We only see this in Travis CI builds (the failures don't show up in builds on our own machines, so up until now we have not filed an issue). I have below a minimal reproducer that has no Go dependency.

```
#include <stdio.h>
#include <lapacke.h>

int row_major = 101;

int main() {
    // row 3 = row1 + 2 * row2
    int m  = 3, n = 3, lda = 3;
    double a[9] = {
        1, 5, 7,
        2, 10, -3,
        5, 25, 1,
    };
    int ipiv[3];

    int info;

    info = LAPACKE_dgetf2(row_major, m, n, a, lda, ipiv);
    printf("dgetf2 info=%d\n", info);

    return info;
}
```

```
~/dgetf2 $ gcc dgetf2.c -o dgetf2 -lopenblas
~/dgetf2 $ ./dgetf2 
dgetf2 info=2
```

Compare the output above with a what octave thinks about the matrix above:

```
octave:1> a = [1 5 7; 2 10 -3; 5 25 1];
octave:2> inv(a)
warning: inverse: matrix singular to machine precision, rcond = 0
ans =

   Inf   Inf   Inf
   Inf   Inf   Inf
   Inf   Inf   Inf
```

The sha for OpenBLAS used here is 8e5a1083bbfca6d93e3d35c1490311cbda675761 (I can check this is also the case for the current develop tip, but am confident it is since we see the correct behaviour when called from Go).

Now compare with what we see on Travis. Relevant Travis CI output https://travis-ci.org/gonum/lapack/jobs/73760112:

```
Cloning into 'OpenBLAS'...
remote: Counting objects: 7581, done.
remote: Compressing objects: 100% (2844/2844), done.
remote: Total 7581 (delta 5022), reused 6786 (delta 4713), pack-reused 0
Receiving objects: 100% (7581/7581), 9.80 MiB | 13.36 MiB/s, done.
Resolving deltas: 100% (5022/5022), done.
Checking connectivity... done.
~/OpenBLAS ~ ~/gopath/src/github.com/gonum/lapack
OpenBLAS 3f1b57668e3d73944981d7bda194ca133f4660b7
```

snip

```
~/gopath/src/github.com/gonum/lapack/dgetf2 ~/gopath/src/github.com/gonum/lapack
dgetf2 info=0
~/gopath/src/github.com/gonum/lapack
```

Here we have info returning 0.

**Comment by kortschak** [comment] 2015-08-02 10:30
Error in original reproducer above. Fixed, now works locally, will create failure on Travis.

**Comment by kortschak** [comment] 2015-08-02 11:05
Relevant Travis CI output https://travis-ci.org/gonum/lapack/jobs/73760112:

```
Cloning into 'OpenBLAS'...
remote: Counting objects: 7581, done.
remote: Compressing objects: 100% (2844/2844), done.
remote: Total 7581 (delta 5022), reused 6786 (delta 4713), pack-reused 0
Receiving objects: 100% (7581/7581), 9.80 MiB | 13.36 MiB/s, done.
Resolving deltas: 100% (5022/5022), done.
Checking connectivity... done.
~/OpenBLAS ~ ~/gopath/src/github.com/gonum/lapack
OpenBLAS 3f1b57668e3d73944981d7bda194ca133f4660b7
```
snip
```
~/gopath/src/github.com/gonum/lapack/dgetf2 ~/gopath/src/github.com/gonum/lapack
dgetf2 info=0
~/gopath/src/github.com/gonum/lapack
```

So here we have info returning 0.

**Comment by hjbreg** [comment] 2015-08-03 01:37
@kortschak LAPACK only checks U(i,i) is exactly zero, you should not rely on the "info" value to test singularity. See http://icl.cs.utk.edu/lapack-forum/archives/lapack/msg00777.html

**Comment by kortschak** [comment] 2015-08-03 02:09
@hjbreg OK, thank you for that. Do you have any ideas about what might be causing the difference between the behaviour locally and on travis? This is purely out of curiosity; we will adjust our tests so that we are more tolerant of these conditions.

**Comment by xianyi** [comment] 2015-08-03 02:14
interesting. @kortschak , Is it relate to the different round-off error on Travis and local machine?

**Comment by kortschak** [comment] 2015-08-03 02:17
@xianyi I have no idea, that's why I'm here. I'm happy to instrument the failure I have on travis for you if that will be helpful though. In the meantime, I'm just going to log the unexpected, rather than fail it.

**Comment by kortschak** [comment] 2015-08-03 10:37
@xianyi [Here](https://travis-ci.org/gonum/lapack/jobs/73869174) is a test where I have asked for /proc/cpuinfo in case that is helpful for you.

**Comment by martin-frbg** [comment] 2018-05-10 21:30
Closing as I cannot reproduce this with current OpenBLAS develop tree and current travis setup.

**Closed by martin-frbg** 2018-05-10 21:30 UTC
