### ISSUE TITLE
[question] Why isn't cblas.h installed?

### ISSUE THREAD

**Issue by yurivict** [xianyi/OpenBLAS#2103] opened 2019-04-29 23:42 UTC
It is in the repository: https://github.com/xianyi/OpenBLAS/blob/v0.2.20/cblas.h but the FreeBSD port doesn't install it for some reason.

**Comment by martin-frbg** [comment] 2019-04-30 05:52
Which version of OpenBLAS ? I remember there were some issues about CMAKE builds not installing it but this should be fixed.

**Comment by yurivict** [comment] 2019-04-30 06:00
openblas-0.2.20_7,1 installs only:
```
	/usr/local/lib/libopenblas.a
	/usr/local/lib/libopenblas.so
	/usr/local/lib/libopenblas.so.0
	/usr/local/lib/libopenblasp.a
	/usr/local/lib/libopenblasp.so
	/usr/local/lib/libopenblasp.so.0
```
and no headers.
It uses gmake.

**Comment by martin-frbg** [comment] 2019-04-30 06:29
0.2.20 is two years old (i.e. seriously outdated), but even that should have installed at least some of the headers. (I do not know much about FreeBSD ports - does this build from source, or is it supposed to be a binary package ?)

**Comment by yurivict** [comment] 2019-04-30 06:51
It builds from source.

**Comment by martin-frbg** [comment] 2019-04-30 07:02
Do you get any warnings or errors from the `make install` step ? (And is there any reason why you would want to install 0.2.20 rather than 0.3.6 ?)

**Comment by yurivict** [comment] 2019-04-30 07:14
This port isn't updated.

**Comment by martin-frbg** [comment] 2019-04-30 07:23
Can you check with any of the people who maintain this port ? (I see somebody at least patched it to backport the cpu detection for AMD Ryzen, so it does not appear to be completely orphaned). As far as I can tell, nobody saw a need to patch Makefile.install for BSD, so perhaps your system is missing some essential tool like `sed` or `awk`, or your version of `install` shows some unexpected behaviour.

**Comment by yurivict** [comment] 2019-04-30 07:28
It doesn't have a strong maintainer. He would only approve things if patches are submitted.
The port is complex, there were some complications when I last tried to update it.

sed and awk are certainly always there.

**Comment by martin-frbg** [comment] 2019-04-30 08:05
So do you get any warnings or errors from `make install`, or do the headers perhaps get installed in some unexpected location ? (I do not see any problems in Makefile.install, so it would help to learn more then just "it does not work for me")

**Comment by brada4** [comment] 2019-04-30 18:05
@martin-frbg he is the person who tries updating from 0.2.20 which includes lots of cpuid stuff backported.

@yurivict probably you need to include cblas.h as it is, also there is pkgconfig file and cmake file to be included - `make install` just copies those, probably package build should do same, e.g. by adding them to package files list.

**Comment by martin-frbg** [comment] 2019-05-02 16:19
Not sure if I read the files in the pkg correctly, but if the "do-install" step of the pkg-provided Makefile is expected to do the entire "make install", it is clearly missing all headers that OpenBLAS' own Makefile.install would provide. (As of 0.3.6, this would be cblas.h  f77blas.h  lapacke.h  lapacke_config.h  lapacke_mangling.h  lapacke_utils.h  openblas_config.h).
I suspect the current pkg may have been intended to provide drop-in replacements for the netlib reference implementation of libblas and/or liblapack to augment some other precompiled code, but not as a full framework to compile own sources against ?
Note also that 0.2.20 is not going to compile (correctly) with gcc8 and above on x86 - there were many cases of undeclared reuse or overwriting of registers in the assembly kernels that would only
work with a suitably "dumb" compiler. There were similar issues with the PPC kernels (written by the same person), I am not sure if these could be expected to work reliably with _any_ compiler...

**Comment by dhomeier** [comment] 2019-05-04 17:33
Does this have no `-devel` split off? The [MacPorts one](https://www.macports.org/ports.php?by=category&substr=math&page=28&pagesize=10) has one, but I don't know how far this has moved from the FreeBSD ports system; also this is installing `cblas.h` as `cblas_openblas.h` to avoid name conflicts with ATLAS and other implementations.

**Comment by martin-frbg** [comment] 2019-05-04 17:43
I do not see any in the FreeBSD ports search engine - most likely this was originally intended to be installed on top of the reference implementations of (C)BLAS and continue using the header(s) from there.

**Comment by brada4** [comment] 2019-05-04 17:54
The clean headers are in cblas and atlas packages.
Actually they conflict.... Could be of use to allow cblas-develop and lapacke-devlop to have openblas as a backend...

**Closed as completed** 2019-05-16 13:23 UTC
