### ISSUE TITLE
Problem when building for Android x86

### ISSUE THREAD

**Issue by bubiche** [xianyi/OpenBLAS#906] opened 2016-06-06 02:22 UTC
Hi,

I'm trying to build OpenBLAS with `make TARGET=ATOM HOSTCC=gcc CC=i686-linux-android-gcc FC=i686-linux-android-gfortran` but I keep getting the error:

> fatal error: complex.h: No such file or directory
> `#include <complex.h>`

I created my standalone toolchain with --platform=android-18 and I know complex.h is only supported in after android-21 so that may be the problem. However, I can still compile with `make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc FC=arm-linux-androideabi-gfortran` with a toolchain with --platform=android-18. How can I fix this?

Thank you very much

**Comment by brada4** [comment] 2016-06-06 17:41
Could you tell in which file complex.h is included, it should be wrapped well in '#ifdef-s'

./common.h:
```
#ifdef OS_ANDROID
#define NO_SYSV_IPC
//Android NDK only supports complex.h since Android 5.0
#if __ANDROID_API__ < 21
#define FORCE_OPENBLAS_COMPLEX_STRUCT
#endif
#endif
```

**Comment by bubiche** [comment] 2016-06-07 01:42
It was included in /OpenBLAS/kernel/arm/zdot.c. I have also checked out that part in common.h and think it should work but I don't why I got that error.

**Comment by brada4** [comment] 2016-06-07 06:11
Easiest is to edit that file and replace
#ifdef _MSC_VER
 with
#ifdef FORCE_OPENBLAS_COMPLEX_STRUCT

**Comment by bubiche** [comment] 2016-06-07 06:24
Well that's kinda what I'm doing for now too but I don't know if it's the right way to solve this. Thanks mate.

**Comment by brada4** [comment] 2016-06-07 06:28
Is there any other file with same problem?

**Comment by bubiche** [comment] 2016-06-07 06:31
no, just that file as far as I know. After that small edit everything compiles fine.

**Comment by brada4** [comment] 2016-06-08 11:15
Can you try this (common.h includes complex.h xor complex struct via ifdef), i just removed surplus redefinitions.
https://github.com/brada4/OpenBLAS

**Comment by bubiche** [comment] 2016-06-09 04:45
Thanks! That compiles for me but I haven't tried to use the built library though.

**Comment by brada4** [comment] 2016-06-09 08:19
I deleted a line too much. Waitasecond I will make it right today.

**Comment by brada4** [comment] 2016-06-09 10:25
it should be correct now.

**Comment by bubiche** [comment] 2016-06-09 13:21
Yes it is, thank you very much

**Comment by martin-frbg** [comment] 2016-10-13 09:46
Looks like #960 was actually a duplicate of this, so should be fixed in the develop branch now.

**Closed** 2017-01-06 11:40 UTC
