### ISSUE TITLE
OpenBLAS doesn't compile with clang 3.9

### ISSUE THREAD

**Issue by maleadt** [xianyi/OpenBLAS#942] opened 2016-08-09 21:59 UTC
Compiling OpenBLAS with Clang/LLVM 3.9 (unreleased, from their SVN branch), I'm running into the following issue:

```
make[3]: Entering directory 'openblas-12ab1804b6ebcd38b26960d65d254314d8bc33d6/kernel'
clang-3.9 -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT  -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DASMNAME=dtrmm_kernel_LN_SANDYBRIDGE -DASMFNAME=dtrmm_kernel_LN_SANDYBRIDGE_ -DNAME=dtrmm_kernel_LN_SANDYBRIDGE_ -DCNAME=dtrmm_kernel_LN_SANDYBRIDGE -DCHAR_NAME=\"dtrmm_kernel_LN_SANDYBRIDGE_\" -DCHAR_CNAME=\"dtrmm_kernel_LN_SANDYBRIDGE\" -DNO_AFFINITY -DTS=_SANDYBRIDGE -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SANDYBRIDGE -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_LN_SANDYBRIDGE.o
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1849:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[3]: *** [Makefile.L3:667: dtrmm_kernel_LN_SANDYBRIDGE.o] Error 1
```

I reproduced this to the following test case:
```assembly
##
#ifndef TRMMKERNEL
vaddpd 4, %xmm9, %xmm9;
vaddpd 6, %xmm8, %xmm8;
vaddpd 0, %xmm15, %xmm15;
vaddpd 2, %xmm14, %xmm14;
vaddpd 4, %xmm13, %xmm13;
vaddpd 6, %xmm12, %xmm12;
#endif
##
```

```
$ clang --version
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
$ clang -DTRMMKERNEL -c kernel.S
$ echo $?
0
```

```
$ clang-3.9 --version
clang version 3.9.0 (http://llvm.org/git/clang.git fc87c4533072c50d1aaaa420d0da934d71e09fbf) (http://llvm.org/git/llvm.git 3d52d9dd5e1dd59f12830965e32cc631da1d726f)
Target: x86_64-unknown-linux-gnu
Thread model: posix
$ clang-3.9 -DTRMMKERNEL -c kernel.S
kernel.S:1:1: error: unexpected token at start of statement
##
^
```

**Comment by martin-frbg** [comment] 2016-08-10 07:15
So in other words clang's integrated assembler suddenly does not like hashes as comment characters anymore, or suddenly this integrated assembler is used on a platform that normally defaulted to using the os-supplied as ?  I suspect building with "clang -no-integrated-as" will still work, and if the behaviour with respect to comment characters is not documented somewhere in the changes file for 3.9.0 it should be reported to the clang folks as a bug. (I suspect it is just the double hash that causes the problem, or it would have come up earlier - but if "everything after the
hash character is treated as a comment and ignored", surely that should include more hash characters as well.)

**Comment by maleadt** [comment] 2016-08-10 11:51
It's more subtle than that: removing almost any line in the example (eg. the `#ifndef ... #end`, or any of the `vaddpd` instructions) makes the example work again, so it's definitely a bug. I've bisected it to llvm-project/llvm-project@c2d26fed5447c7367fb70335342cfdedf34fb25b so I should probably report this upstream.

**Comment by martin-frbg** [comment] 2016-08-10 12:35
So they broke their hash comment handling in an attempt to refactor their code. I see little point in having this here as an open bug ticket against OpenBLAS (although the information that current llvm svn has a serious issue with assembler may save others some trouble until they get around to fixing it).

**Comment by maleadt** [comment] 2016-08-10 12:38
Exactly that; even though it's an upstream bug, seeing how it breaks OpenBLAS it is valuable to have an open issue for it. Or else I would expect quite some new bugs to get files as soon as Arch/Fedora/... upgrade to LLVM 3.9 (which is due to be released in 2 weeks).

**Comment by maleadt** [comment] 2016-08-10 13:11
Reported upstream: https://llvm.org/bugs/show_bug.cgi?id=28921

**Comment by martin-frbg** [comment] 2016-08-20 09:15
Somewhat disconcerting to see that your bug report appears to be ignored by the clang team, I wonder if the subject title was too vague to catch their attention or if there are too few active developers to triage new bugs so close to a release. Surely OpenBLAS cannot be the only code that occasionally uses double hashes in assembler comments.

**Comment by maleadt** [comment] 2016-09-02 19:01
It seems to be more subtle than just using double hashes, but yeah too bad it didn't get fixed in time for 3.9 (which got released today); the issue is still there on the release tarballs. This probably will warrant some check in the OpenBLAS Makefiles?

**Comment by martin-frbg** [comment] 2016-09-02 19:19
If it is not just the double hash that triggers it, I guess it will be the combination with the #ifdef construct (or does it take the exact number of assembly statements as in your example above) ?
Not sure what the OpenBLAS build system could do about this except issue a warning when it encounters clang 3.9 (on some yet-to-be-defined range of architectures) ? Editing all the affected assembly files just to placate this one tool seems quite a chore as well (and generate unnecessary noise in the file history).

**Comment by maleadt** [comment] 2016-09-02 19:30
It does take exactly that number of statements, removing any one of them makes the example work. Although there probably exists another sequence triggering the issue, but I didn't look into that.

And why not conditionally add `-no-integrated-as` to `CCOMMON_OPT`?

**Comment by martin-frbg** [comment] 2016-09-02 21:28
That makes it look like some kind of memory access bug in clang, suggesting that it can probably be triggered by completely different code as well. (Maybe it's just me, but I think this is not apparent from your bug report?). Would probably require running clang under valgrind to track down the issue...

**Comment by martin-frbg** [comment] 2016-09-07 15:39
I could reproduce the spurious error with TARGET set to SANDYBRIDGE, but unfortunately valgrind did not flag any memory access violation that would point to an easily identifiable coding error rather than a logic flaw and I do not have the time (nor the experience probably) to debug further. What I can do is run build tests for at least the individual x86_64 targets, and so far it looks as if SANDYBRIDGE is actually the only one (currently) affected by this clang-as bug (at least among recent architectures - still need to test systems earlier than NEHALEM and BULLDOZER respectively).

**Comment by martin-frbg** [comment] 2016-10-06 11:09
Apparently a bugfix for the asm lexer has landed on the llvm trunk on Oct. 3 https://reviews.llvm.org/rL283111 Not sure how things usually progress from there, from their release history it looks as if it would be rolled into a 3.9.1 release in three to six months.
As far as I can tell, there is currently no attempt at determining the compiler _version_ in the OpenBLAS build system - wonder if anything of importance would be lost if the workaround suggested by maleadt above would be added conditional on C_COMPILER=="CLANG" only, just to fix that one version-specific issue ?

**Comment by maleadt** [comment] 2016-10-06 15:16
Fixes for 3.9.1 should be [specifically requested](https://llvm.org/bugs/show_bug.cgi?id=30261).

**Comment by martin-frbg** [comment] 2016-10-06 15:35
I'd have expected regression fixes to be automatically in. Any idea if there is/was any advantage in using its integrated assembler (other than not requiring the presence of a separate "as" binary, I guess) ?

**Comment by martin-frbg** [comment] 2016-10-06 19:29
Given that a single Sandybridge-specific assembler file appears to be affected out of all the x86_64 targets (unless I overlooked one in my build tests), and the bug will likely be limited to 3.9 and at most 3.9.1, how about just massaging dgemm_kernel_4x8_sandy.S so that it no longer triggers the clang bug ? (I suspect substituting c++ style double slashes for all the hash characters in comments, or even just the comments at the end of code lines, would suffice as the bug appears to be caused by overzealous read-ahead of hash characters ?)

**Closed** 2016-10-17 03:32 UTC
