### ISSUE TITLE
Calculation goes off the rails with AVX-512 kernels

### ISSUE THREAD

**Issue by jabl** [xianyi/OpenBLAS#2029] opened 2019-02-25 14:19 UTC
Hi,

I don't know if this issue belongs to https://github.com/cp2k/cp2k or here, but anyway, here goes:

I have built cp2k 6.1 using OpenBLAS 0.3.5 built with DYNAMIC_ARCH=1 (via spack), running on an avx-512 equipped skylake-x machine. For my testcase I'm using the "test A" from the PRACE benchmarking suite ( http://www.prace-ri.eu/UEABS/CP2K/CP2K_TestCaseA.tar.gz ). Unfortunately the result is that the calculation diverges almost immediately, the end of the output says

<pre><code>
SCF WAVEFUNCTION OPTIMIZATION

  ----------------------------------- OT ---------------------------------------
  Minimizer      : DIIS                : direct inversion
                                         in the iterative subspace
                                         using   7 DIIS vectors
                                         safer DIIS on
  Preconditioner : FULL_KINETIC        : inversion of T + eS
  Precond_solver : DEFAULT
  stepsize       :    0.15000000                  energy_gap     :    0.20000000
  eps_taylor     :   0.10000E-15                  max_taylor     :             4
  ----------------------------------- OT ---------------------------------------

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------
     1 OT DIIS     0.15E+00  167.7     0.00331514    -16961.8835192894 -1.70E+04
     2 OT SD       0.15E+00   49.1     7.4819E+14 ********************  7.72E+15
     3 OT SD       0.15E+00   47.9     1.2647E+97 ********************  2.07E+80

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                KS energy is an abnormal value (NaN/Inf).             *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                     qs_ks_methods.F:866 *
 *******************************************************************************

 ===== Routine Calling Stack ===== 

            7 qs_ks_build_kohn_sham_matrix
            6 rebuild_ks_matrix
            5 qs_ks_update_qs_env
            4 scf_env_do_scf_inner_loop
            3 scf_env_do_scf
            2 qs_energies
            1 CP2K
</code></pre>

Running on a non-AVX-512 machine all goes well, or by using OpenBLAS 0.2.20 from Ubuntu 18.04 package repos (without AVX-512 kernels).

**Comment by brada4** [comment] 2019-02-25 14:31
Does it fail with develop version? It adds some fixes that may or may not completely address your issue (some in avx-512 side, others in gcc9 side)

**Comment by martin-frbg** [comment] 2019-02-25 14:32
This seems to match the earlier report in #1955 (for which unfortunately no small self-contained reproducer has been found yet). I doubt CP2k fits the "small and self-contained" category either, but at least it appears to be fortran...

**Comment by martin-frbg** [comment] 2019-02-25 14:38
BTW as a (hopefully) short-term workaround you should be able to force the DYNAMIC_ARCH library to use the non-AVX512 Haswell kernels at runtime by `export OPENBLAS_CORETYPE=Haswell` rather than resorting to 0.2.20 (18+ months old and with a sizable number of known bugs including thread races).

**Comment by martin-frbg** [comment] 2019-02-25 14:51
@brada4 the only AVX512-related PR since release 0.3.5 affected autodetection of cpu capabilities only. The change implicated in #1955 happened after 0.3.3, but I do not think it advisable to prefer that version over a current 0.3.5 clamped to use Haswell kernels.

**Comment by jabl** [comment] 2019-02-25 15:59
Argh. I was just about to report success with the latest OpenBLAS git, but upon closer inspection it turned out that some change since 0.3.5 has caused it to add the NO_AVX512 preprocessor symbol, and thus no AVX512 kernels were actually built. Any idea how to get rid of that (might be because my build host does not have AVX-512, but with DYNAMIC_ARCH that shouldn't matter, right?)?

**Comment by martin-frbg** [comment] 2019-02-25 16:21
Maybe I introduced a logic flaw, but at least in theory the recent changes should affect only whether the host cpu is identified as SkylakeX (both cpu and os capable of AVX512) or Haswell. NO_AVX512 should only get set when your compiler actually fails to process a simple test case embedded in the c_check file (or fails to accept the -march=skylake-avx512 option).

**Comment by martin-frbg** [comment] 2019-02-25 16:50
Meh. That check must have been broken for quite some time - somehow I managed to drop the `-c` from
the compile line so the avx512 check always failed with "undefined reference to main" ??

**Comment by martin-frbg** [comment] 2019-02-25 17:00
Fixed on the develop branch now (added `-c` to compiler arguments on line 235 of c_check). With NO_AVX512 set, SKYLAKEX would not be on the default list of DYNAMIC_ARCH targets - I have yet to understand if/how builds on actual SkylakeX hardware would get around the bogus failure. :frowning_face:

**Comment by jabl** [comment] 2019-02-25 19:03
Thanks, that fix allowed me to produce a build of the develop branch with the AVX-512 kernels included. All our skylake-x nodes are fully booked at the moment, lets see by tomorrow if the develop version fares better with cp2k than 0.3.5, though based on your previous comment maybe I shouldn't be getting my hopes up.

**Comment by martin-frbg** [comment] 2019-02-25 19:13
Indeed I do not expect `develop` to be better in this regard - but building from source will allow you to apply the "fix" from #1955 to disable the avx512 DGEMM kernel. (Though given that AVX512 support in OpenBLAS is still pretty much limited to SGEMM and DGEMM that would not gain you much over a plain Haswell build). At least by now it is clear that the AVX512 issue is real and not just some coincidental bug or calling convention mismatch in Julia @fenrus75

**Comment by jabl** [comment] 2019-02-25 19:39
Oh, I got lucky and my job was already scheduled. Unfortunately, I now again got the same failure as I originally reported in this issue.

As mentioned, cp2k isn't really small nor self-contained, and furthermore the testcase I've been using requires about 100 GB RAM.

**Comment by brada4** [comment] 2019-02-25 20:11
it will help setting OPENBLAS_CORETYPE=HASWELL to "fix" DYNAMIC_ARCH build (or build with TARGET=HASWELL if on your own)

**Comment by fenrus75** [comment] 2019-02-25 20:13
still clamoring for ANY way that can repro this ...

**Comment by jabl** [comment] 2019-02-25 20:18
Well, for ANY way, with the disclaimer that cp2k is not anywhere near simple, and that the testcase requires about 100 GB RAM, see https://github.com/AaltoScienceIT/docker-fgci-benchmark

If following the instructions in the README, use the tag "v2.2" instead of "latest" to get the version using the OpenBLAS 0.3.6dev version.

**Comment by martin-frbg** [comment] 2019-02-25 20:36
I wonder if we might be able to get something similar with the more compact ELK code (broadly similar kind of computations, from elk.sourceforge.net). Still haven't got AVX512 hardware though

**Comment by brada4** [comment] 2019-02-25 20:43
Probably it is possible to subset inputs to make it viable on common hardware...

**Comment by fenrus75** [comment] 2019-02-25 21:07
Martin: Send me an email and we'll sort hardware out

**Comment by martin-frbg** [comment] 2019-03-06 18:50
Experimenting with Intel SDE in lieu of actual hardware, I now find that BLAS-Tester is actually unhappy about DSYMM:
```
./xdl3blastst -R symm 

-------------------------------- SYMM --------------------------------
TST# S U    M    N ALPHA  LDA  LDB  BETA  LDC   TIME MFLOP  SpUp  TEST
==== = = ==== ==== ===== ==== ==== ===== ==== ====== ===== ===== =====
ERROR:  resid=22184890850.394222, normD=114.531676, normA=27.442124, normB=29.226439, normC=28.989082, eps=2.220446e-15
   resid=22184890850.394222
   0 L L  100  100   1.0 1000 1000   1.0 1000   0.01 201.2  1.00 -----
   0 L L  100  100   1.0 1000 1000   1.0 1000   0.09  21.7  0.11 FAIL 
```
(etc.)

**Comment by fenrus75** [comment] 2019-03-06 20:18
ok that I can work with

**Comment by martin-frbg** [comment] 2019-03-06 21:18
..provided this can be reproduced on the actual hardware at all (?)

**Comment by martin-frbg** [comment] 2019-10-20 11:09
Fixed now by wjc404's new AVX512 DGEMM kernel from #2286

**Closed as completed by martin-frbg** 2019-10-20 11:09 UTC
