### ISSUE TITLE
How to define ARMV5,ARMV6,ARMV7

### ISSUE THREAD

**Issue by MaxEver13** [xianyi/OpenBLAS#1267] opened 2017-08-05 08:11 UTC
when I cross compiled the openblas, the error occured:
ji@ji-dell:~/tools/rk_ws/OpenBLAS$ make TARGET=ARMV7 CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran
Can't create Makefile.conf at ./c_check line 271.
make: *** [config.h] Error 13
make[1]: Entering directory `/home/ji/tools/rk_ws/OpenBLAS/interface'
arm-linux-gnueabihf-gcc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER= -mfpu=vfpv3 -march=armv7-a -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
In file included from ../common.h:416:0,
                 from axpy.c:40:
../common_arm.h:134:2: error: #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
 #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
  ^
make[1]: *** [saxpy.o] Error 1
make[1]: Leaving directory `/home/ji/tools/rk_ws/OpenBLAS/interface'
make: *** [libs] Error 1

any help? Thanks.

**Comment by martin-frbg** [comment] 2017-08-05 09:27
Strange error, it fails to create at least one of the configuration files and the "you must define" is just a consequence of that. Make sure that you have write permissions in rk_ws/OpenBLAS (e.g. the cause could be that you copied/unpacked the OpenBLAS source as a diferent user - possibly "root").

**Comment by MaxEver13** [comment] 2017-08-05 09:34
@martin-frbg 
yes, maybe the cross compile toolchain somehow wrong: 
as: unrecognized options '--64'
Makefile.system:171: Makefile.conf: No such file or directory.
any suggestion?

**Comment by MaxEver13** [comment] 2017-08-05 09:39
And I git clone the source code, so it should't be that problem.

**Comment by brada4** [comment] 2017-08-05 11:02
Ou must set 'HOSTCC' for cross-compilation (and run 'make clean' before next try)

**Comment by MaxEver13** [comment] 2017-08-07 02:34
OK.Thanks for your kind reply.I made it done by using "sudo make " and adding the "HOSTCC".

**Comment by brada4** [comment] 2017-08-07 06:35
You dont need sudo anywhere, better start with clean build tree (deleting old with sudo)

**Comment by brada4** [comment] 2017-08-07 10:53
May you close the issue as it is resolved?

**Closed as completed** 2017-08-10 08:11 UTC
