### ISSUE TITLE
Problems with installing git on windows 7

### ISSUE THREAD

**Issue by mareichhoff** [xianyi/OpenBLAS#1331] opened 2017-10-19 10:58 UTC
Hello,

this is my error output (last lines of the output in cygwin):

```
/usr/bin/ar: strmm_kernel_LN.obj: No such file or directory
make[1]: *** [../Makefile.tail:40: libs] Error 1
make[1]: Leaving directory '/c/Users/meichho/Documents/openBlas/kernel'
make: *** [Makefile:139: libs] Error 1

meichho@SC-R90FWVVK-1 /cygdrive/c/Users/meichho/Documents/openBlas
$ make install
/usr/bin/make -f Makefile.install install
make[1]: Entering directory '/c/Users/meichho/Documents/openBlas'
Makefile.install:21: *** OpenBLAS: Please run "make" firstly.  Stop.
make[1]: Leaving directory '/c/Users/meichho/Documents/openBlas'
make: *** [Makefile:322: install] Error 2
```
Then I tried "make install", but it didn't work. I don't understand the error message above.

Thank you very much for your help!

Best regards,
Markus

**Comment by martin-frbg** [comment] 2017-10-19 11:04
Could be that autodetection of your CPU failed for some reason, or your compiler version is too old to understand some of the assembly code used (e.g. AVX2 commands). Can you give more information about your system and compiler, and upload the full build log (or at least significantly more than you showed above) please ?

**Comment by mareichhoff** [comment] 2017-10-19 11:24
I installed cygwin some days ago. Everything is new. I try to paste the output here in some minutes. Thank you for your help!

**Comment by martin-frbg** [comment] 2017-10-19 11:32
I'll be offline now for an hour or two. In the meantime you could try building for a specific cpu - do a `make clean` first, and then do `make TARGET=NEHALEM` (should work on most older x86_64 targets) or `make TARGET=HASWELL` (should work on most any x86_64 "desktop category" cpu released in the last couple of years).

**Comment by brada4** [comment] 2017-10-19 13:38
Can you capture full long output with "script" command:
make clean
script
make
make install
exit
Now upload long typesript file.

**Comment by mareichhoff** [comment] 2017-10-19 14:06
Hello Martin, brada,

I looked in "system". My intel processor is "Haswell". So I tried "make clean" and then "make TARGET=HASWELL" without success. I can't upload the full output. These exceeds the space here. Or is it possible to mail it to you?

Best regards,
Markus

**Comment by mareichhoff** [comment] 2017-10-19 14:06
Intel Core i5-4210M CPU

**Comment by brada4** [comment] 2017-10-19 14:11
Should be detected fine as haswell correctly already few releases back.
You can attach output by renaming it to *.txt

**Comment by mareichhoff** [comment] 2017-10-19 14:12
Ah I see..... drag & drop... I will do it now. After this I will try it with sript in between an put the output here again. 
[make TARGET=HASWELL.txt](https://github.com/xianyi/OpenBLAS/files/1398709/make.TARGET.HASWELL.txt)

**Comment by brada4** [comment] 2017-10-19 14:19
I think you need to cross-compile if you want 32bit DLL (i.e i686-mingw-something-gcc etc)

```
gcc -O2 -DMS_ABI -mincoming-stack-boundary=2 -DMAX_STACK_ALLOC=2048 -Wall -m32 -DF_INTERFACE_GFORT -DNO_AVX -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=_strmm_kernel_LN -DASMFNAME=_strmm_kernel_LN_ -DNAME=strmm_kernel_LN_ -DCNAME=strmm_kernel_LN -DCHAR_NAME=\"strmm_kernel_LN_\" -DCHAR_CNAME=\"strmm_kernel_LN\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -UDOUBLE -UCOMPLEX -DLEFT -UTRANSA ../kernel/x86/ -o strmm_kernel_LN.obj
gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
```

**Comment by mareichhoff** [comment] 2017-10-19 14:23
O.k., thank you very much! I will try it.

**Comment by martin-frbg** [comment] 2017-10-19 16:43
I believe 32bit Haswell support is broken (or just not properly supported), `make TARGET=SANDYBRIDGE` would probably work

**Comment by brada4** [comment] 2017-10-23 12:43
It is replaced by westmere/nehalem in make files (though nice to have somebody to confirm it is still the case)

**Comment by martin-frbg** [comment] 2017-10-23 21:55
Trying to make a 32-bit "Haswell target" library on a 64-bit system automatically results in a Nehalem build, apparently by design. Trying to build a Haswell llibrary on a 32-bit system however leads to the error reported at the top of this thread. 
Apparently the kernel/x86/KERNEL.HASWELL file needs xTRMMKERNEL definitions added, but choosing either of the various trmmkernel_ implementations available in "generic" gives the dreaded LESS THAN HALF ACCURATE errors in all xTRMM tests. Seems the USE_TRMM=1 for HASWELL in kernel/Makefile.L3 needs an additional "ifeq($ARCH), X86_64)" qualifier to get around this, but I am not yet through with my tests.

**Comment by martin-frbg** [comment] 2017-10-24 09:30
Build issue fixed by #1333 now - note though that 32bit builds for Haswell and later will still be using only Penryn-level (SSE) optimizations internally.

**Comment by martin-frbg** [comment] 2017-10-26 08:50
@mareichhoff did you get a chance to try ?

**Comment by mareichhoff** [comment] 2017-10-26 09:21
Hello Martin,

I have been in the hospital from 20th - 22th October after writing my comments here. Nothing serious. Just now it is running. I updated the repository and try it again. Thank you very much! I hope that it is going to work now. 

But what I don't understand: You write something about "32bit builds". What do you mean? I have everything in 64 bit here: Windows 7 operating system is 64 bit, cygwin is also 64 bit terminal. What is 32 bit then? :-)

It sounds that it the openblas would have some restrictions then.... "using only Penryn-level optimizations internally".... 

Best regards,
Markus

**Comment by martin-frbg** [comment] 2017-10-26 09:39
The "-m32" among the compiler options in the log you uploaded suggests that you were trying to build a 32bit library, or happened to pick a 32bit version of the compiler. Also the error you posted "should not happen" on 64bit but is known from earlier issues with builds for 32bit platforms.

**Comment by mareichhoff** [comment] 2017-10-26 10:58
OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  ```
OS               ... WINNT
  Architecture     ... x86
  BINARY           ... 32bit
  C compiler       ... GCC  (command line : gcc)
  Fortran compiler ... GFORTRAN  (command line : gfortran)
  Library Name     ... libopenblas_haswellp-r0.3.0.dev.a (Multi threaded; Max num-threads is 4)

To install the library, you can run "make PREFIX=/path/to/your/installation install".
```

It worked at least. Great. BINARY 32 bit... So what should I do to have everything in 64 bit in your opinion? The compiler should be a 64 bit version and what else? Perhaps I should reinstall cygwin and then look in detail what to install (gcc etc.)?

**Comment by martin-frbg** [comment] 2017-10-26 11:06
Having a 64bit compiler should be sufficient, according to https://www.cygwin.com/install.html you probably just need to execute their setup-x86_64.exe not the setup-x86 one to get the 64bit version.

**Comment by mareichhoff** [comment] 2017-10-26 11:10
yes, but this I did before! I had already installed setup-x86_64. That is strange... I will try it again or look in detail which gcc is chosen.

**Comment by martin-frbg** [comment] 2017-10-26 11:13
As an alternative you could try the mingw-w64 from sourceforge.net

**Comment by mareichhoff** [comment] 2017-10-26 11:14
I think I installed both gcc's! That was the problem. I have cygwin64, but installed both gcc in 32 bit and 64. Now I deinstall 32 bit gcc and try itagain.

**Comment by mareichhoff** [comment] 2017-10-26 11:50
During the compilation the following warning message occured. Perhaps you know the reason. I just show it to you:

```
lapack/laswp.c: In function ‘slaswp_’:
lapack/laswp.c:100:8: warning: passing argument 12 of ‘blas_level1_thread’ from incompatible pointer type [-Wincompatible-pointer-types]
        laswp[flag], nthreads);
        ^~~~~
In file included from ../common.h:777:0,
                 from lapack/laswp.c:40:
../common_thread.h:177:5: note: expected ‘int (*)()’ but argument is of type ‘int (*)(BLASLONG,  BLASLONG,  BLASLONG,  float,  float *, BLASLONG,  float *, BLASLONG,  blasint *, BLASLONG) {aka int (*)(long long int,  long long int,  long long int,  float,  float *, long long int,  float *, long long int,  int *, long long int)}’
 int blas_level1_thread(int mode, BLASLONG m, BLASLONG n, BLASLONG k, void *alpha,
```

**Comment by martin-frbg** [comment] 2017-10-26 12:04
Guess the actual argument lacks an explicit cast to a void pointer to match the function prototype.
There are several such warnings during the build (including lots for unused or possibly uninitialized variables in the LAPACK code imported from netlb) that so far have been considered harmless.

**Comment by martin-frbg** [comment] 2017-10-26 13:07
I take it your installation was successful now ?

**Comment by mareichhoff** [comment] 2017-10-26 13:40
No... I used make target=HASWELL again as last time. Here is the output. It ended with an error. BUT: I updated cygwin, deleted the standard gcc 32 bit. Now I have -m64 everywhere. Here is the output as attachment.
[make target=HASWELL.txt](https://github.com/xianyi/OpenBLAS/files/1418567/make.target.HASWELL.txt)

**Comment by martin-frbg** [comment] 2017-10-26 13:54
`f951.exe: sorry, unimplemented: 64-bit mode not compiled in` suggests you still have the fortran compiler from the previous 32 bit installation in your path before (or instead of) the "correct" one ?

**Comment by martin-frbg** [comment] 2017-11-09 17:21
Markus, is this still an unresolved issue for you ? (And I hope you have not been hospitalized again)

**Closed as completed** 2017-12-01 22:15 UTC
