### ISSUE TITLE
segment fault on sgemm_kernel with version 0.2.14

### ISSUE THREAD

**Issue by leecy0405** [xianyi/OpenBLAS#770] opened 2016-02-01 01:06 UTC
Hello，
I meet a seg fault as follows and have tried many ways to debug，but it shows that before I call blas function or after， the code does not have any invalid operations，so could you please check whether my usage of openblas is correct，thank you

my seg fault info like this:
```
#0  0x00007fefcbb949e2 in sgemm_kernel () 
#1  0x0040010020004000 in ?? ()
#2  0x1000400100040010 in ?? ()
#3  0x0010004001000400 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x0000000000000000 in ?? ()
```

my code is：
```
void ComputeForwardByBlas(vector <vector<float> > &output, vector<vector<float> > &input) {
    uint32_t dataSize = input.size();
    output.clear();
    output.resize(dataSize);
    uint32_t len1 = mInSize * dataSize;
    assert(len1 > 0);
    uint32_t len2 = mOutSize * dataSize;
    assert(len2 > 0);
    float *inputVec = new float[mInSize * dataSize];
    float *outputVec = new float[mOutSize * dataSize];
    memset(inputVec, 0, sizeof(float) * mInSize * dataSize);
    memset(outputVec, 0, sizeof(float) * mOutSize * dataSize);
    for (uint32_t i = 0; i < dataSize; i++) {
        output[i].resize(mOutSize, 0);
        input[i].insert(input[i].begin(), 0);
        for (uint32_t j = 0; j < mInSize; j++) {
            uint32_t size = i +  dataSize * j;
            assert(size < len1);
            inputVec[size] = input[i][j];
        }
    }
    cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, mOutSize, dataSize, mInSize, 1.0, mWeight, mInSize, inputVec, dataSize, 0, outputVec, dataSize);                                                   
for (uint32_t i = 0; i < dataSize; i++) {                                                                                                                                                                     for (uint32_t j = 0; j < mOutSize; j++) {
            assert((i +  dataSize * j) < len2);                                                                                                                                                                       output[i][j] = outputVec[i +  dataSize * j];
            if (output[i][j] < 0) {
                output[i][j] = 0;
            }
        }
    }
    delete [] inputVec;
    inputVec = NULL;
    delete [] outputVec;
    outputVec = NULL;
}
```
In above code, inputVec is used for transform the vector to array, is there any problem when I frequently new or delete this ptr?
In addition, the seg fault is reproduced only in multi-thread version

Thanks a lot

**Comment by martin-frbg** [comment] 2016-02-01 16:04
Can you update to 0.2.15 (released last october) ? I recall there may have been problems with the initial code change to speed up gem by allocating workspace on the stack that went into 0.2.14. (if you absolutely must use 0.2.14, try disabling the MAXSTACKALLOC setting in Makefile.rule)

**Comment by brada4** [comment] 2016-02-01 18:53
can you produce fully working self-contained test case?
If you call your function with all parameters 0x0 it crashes already before reaching BLAS call.
Also more debug context is needed (compile your code with -O0 -g to get any debug simbols, blank call stack is completely useless):
Run test case in debugger:
Once it bails out:
gdb >thread apply all backtrace
gdb> quit

**Comment by brada4** [comment] 2016-02-01 21:05
#535 may be already fix for this issue...

**Comment by wlxiong** [comment] 2016-02-02 07:31
Yes, it's exactly the same problem as #535. After upgrading to 0.2.15, the problem is fixed.
We can close this issue @leecy0405

**Comment by xianyi** [comment] 2016-02-02 18:29
Just closed this issue. if you have any questions, please feel free to reopen it.

**Closed** 2016-02-02 18:28 UTC
