### ISSUE TITLE
regression in 

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#4988] opened 2024-11-24 08:57 UTC
I run weekly builds of HEAD building the scipy-openblas wheels. Starting 5 weeks ago between commit 624e9d110 and 3184b7f20 there is a [test failure](https://github.com/MacPython/openblas-libs/actions/runs/11992062604/job/33431446557#step:9:5772) on aarch64, I think it is in `cblas_ssyrk`, there are a number of failures in the CI run. I was waiting to see if the failure dissapeared but it seems to persist from that commit forward.

**Comment by martin-frbg** [comment] 2024-11-24 09:30
strange, there weren't that many PRs in that timeframe that could have affected ARMV8

**Comment by martin-frbg** [comment] 2024-11-24 12:40
Also not reproducible in my local arm64 builds (and CI is quiet too). What environment does your build test run in, is this some kind of emulation ?

**Comment by mattip** [comment] 2024-11-24 14:56
The `aarch64`, like all the linux builds, run inside a manylinux2104 docker image on x86_64. So the build adds the ability to use docker with qemu:
```
sudo apt-get -qq install -y qemu qemu-user-static
sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
```

**Comment by martin-frbg** [comment] 2024-11-24 16:46
Did anything change in your manylinux/docker/qemu framework lately ? This is almost certainly a fluke in your setup - I cannot reproduce it on (various) actual arm64 hardware, there have been no changes directly affecting SYRK drivers or kernels in many months, and I cannot think of any indirect changes that would manifest as SYRK breakage without general carnage in GEMM/TRMM

**Comment by martin-frbg** [comment] 2024-12-04 15:21
Closing for now as I cannot reproduce the issue on any Arm64 setup - if anything, this could be related to your docker environment or the specific libc builds used therein - I notice even your CI jobs pass with one particular flavor of musl.

**Closed as completed by martin-frbg** 2024-12-04 15:21 UTC

**Comment by mattip** [comment] 2024-12-04 17:02
OK, thanks for checking. Maybe someday github aarch64 native runners will be available.
