### ISSUE TITLE
undefined reference to `xerblassytrd_sb2st_'

### ISSUE THREAD

**Issue by jeffhammond** [xianyi/OpenBLAS#1069] opened 2017-01-18 22:57 UTC
# Command
```
make TARGET=HASWELL CC=gcc FC=ifort
```

# Error
```
make[1]: Entering directory `/home/jrhammo/OpenBLAS/git/exports'
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_INTEL -fPIC 
-DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=272 -DASMNAME= 
-DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" 
-DNO_AFFINITY -I..  -shared -o ../libopenblas_haswellp-r0.2.20.dev.so \
-Wl,--whole-archive ../libopenblas_haswellp-r0.2.20.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_INTEL -fPIC -DSMP_SERVER 
-DNO_WARMUP -DMAX_CPU_NUMBER=272 -DASMNAME= -DASMFNAME=_ -DNAME=_ 
-DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w 
-o linktest linktest.c ../libopenblas_haswellp-r0.2.20.dev.so 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/ipp/lib/intel64 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.7 
-L/home/projects/x86-64-knl/git/2.8.2/lib -L/home/projects/x86-64-knl/x11/libx11/1.5.0/lib 
-L/home/projects/x86-64-knl/x11/libxau/1.0.7/lib -L/home/projects/x86-64-knl/tcl/8.6.5/lib 
-L/home/projects/x86-64-knl/zlib/1.2.8/lib -L/home/projects/x86-64-knl/numa/2.0.10/lib 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin 
-L/home/jrhammo/GCC/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/ 
-L/home/jrhammo/GCC/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/../../../../lib64 
-L/home/jrhammo/GCC/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/../../../../lib64/ 
-L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64/ 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/ 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/ipp/lib/intel64/ 
-L/home/jrhammo/intel/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.7/ 
-L/home/projects/x86-64-knl/git/2.8.2/lib/ -L/home/projects/x86-64-knl/x11/libx11/1.5.0/lib/ 
-L/home/projects/x86-64-knl/x11/libxau/1.0.7/lib/ -L/home/projects/x86-64-knl/tcl/8.6.5/lib/ 
-L/home/projects/x86-64-knl/zlib/1.2.8/lib/ -L/home/projects/x86-64-knl/numa/2.0.10/lib/ 
-L/home/jrhammo/GCC/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/../../../ -L/lib64 -L/lib/ 
-L/usr/lib64 -L/usr/lib  -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lpthread 
-lsvml -lc -lirc_s -ldl -lc  -lgfortran && echo OK.
../libopenblas_haswellp-r0.2.20.dev.so: undefined reference to `xerblassytrd_sb2st_'
../libopenblas_haswellp-r0.2.20.dev.so: undefined reference to `zsteqrzhetrd_2stage_'
../libopenblas_haswellp-r0.2.20.dev.so: undefined reference to `zlatrszgemm_'
../libopenblas_haswellp-r0.2.20.dev.so: undefined reference to `csteqrchetrd_2stage_'
../libopenblas_haswellp-r0.2.20.dev.so: undefined reference to `xerbladsytrd_sb2st_'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_haswellp-r0.2.20.dev.so] Error 1
make[1]: Leaving directory `/home/jrhammo/OpenBLAS/git/exports'
make: *** [shared] Error 2
```

# Software
```
$ uname -srvmpio
Linux 3.10.0-327.el7.mpsp_1.3.0.66.x86_64 #1 SMP Thu Mar 3 09:15:44 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ ld -v
GNU ld version 2.23.52.0.1-55.el7 20130226
```
```
$ ifort --version
ifort (IFORT) 17.0.0 20160721
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
```
```
$ gcc --version
gcc (GCC) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/jrhammo/GCC/gcc-6.2.0/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/home/jrhammo/GCC/gcc-6.2.0 --enable-shared 
--enable-static --enable-threads=posix --enable-checking=release --with-system-zlib 
--enable-__cxa_atexit --enable-languages=c,c++,fortran --with-tune=native 
--enable-bootstrap --enable-lto --enable-gold=yes --enable-ld=yes --disable-multilib
Thread model: posix
gcc version 6.2.0 (GCC) 
```

# Hardware
This is KNL, but I'm treating it as Haswell.
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                272
On-line CPU(s) list:   0-271
Thread(s) per core:    4
Core(s) per socket:    68
Socket(s):             1
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 87
Model name:            Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz
Stepping:              1
CPU MHz:               1396.793
BogoMIPS:              2793.58
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
NUMA node0 CPU(s):     0-271
NUMA node1 CPU(s):     
```

**Comment by jeffhammond** [comment] 2017-01-18 23:01
This error does not occur with `FC=gfortran`, so it appears to be a defect in the Fortran interface definition.

**Comment by martin-frbg** [comment] 2017-01-18 23:23
Could be related to the fact that the build system simply invokes the CC for linking ... think there is/was an open issue for something like that but can't find it now. Incidentally is the "-lgfortran" on your link line right above the first error message expected for ifort ?

**Comment by martin-frbg** [comment] 2017-01-18 23:30
OTOH could also be just the "gensymbol" script acting up while creating the linktest.c file - though I do not see immediately where it would manage to create this peculiar combination of module names run together.

**Comment by martin-frbg** [comment] 2017-01-19 19:09
Could it be that ifort is pickier than gfortran - as far as I can tell the affected functions appear to be new additions in 3.7.0, and at least d/ssytrd_sb2st.F seem to lack the EXTERNAL declaration of the ubiquitous error handler xerbla. 
So could the "unknown symbol xerblassytrd_sb2st" be simply ifort complaining about "that unknown thing called xerbla that you used without declaration in ssytrd_sb2st.f" ?

**Comment by jeffhammond** [comment] 2017-01-19 19:44
@martin-frbg That's an interesting hypothesis.  I added `XERBLA` to the external list in two of the functions (https://github.com/jeffhammond/OpenBLAS/commit/c58a8469dbd36d11446b04cf2274103d3c887697) but I know get a different error, which doesn't make sense.

Also, I cannot see how this explains the error with `zlatrszgemm_` since `zlatrs` and `zgemm` do not appear to call each other.

**Comment by martin-frbg** [comment] 2017-01-19 20:04
> Also, I cannot see how this explains the error with zlatrszgemm_

Well I had to stop checking my hypothesis somewhere, didn't I ... what is the new error ? Unfortunately I do not have ifort to try the consequences of my ramblings on myself first.

**Comment by jeffhammond** [comment] 2017-01-19 20:07
@martin-frbg Are you eligible for any of the options listed on https://software.intel.com/en-us/qualify-for-free-software?

**Comment by martin-frbg** [comment] 2017-01-19 20:24
Good question, I have not bothered since the terms of the edu option were changed (or just clarified) to exclude grant-funded projects. In my incarnation as an open source developer it probably hinges on "qualified" (and I seem to remember reading in one of the other open issues that xianyi himself applied for such a license and nothing apparently became of that).
Back on topic the lack of "external xerbla" seems to be typical for files with capital F extension but I do not see if that has any significance (not really familiar with modern dialects of fortran).

**Comment by jeffhammond** [comment] 2017-01-19 20:53
@martin-frbg Since OpenBLAS is clearly open-source, you and @xianyi should pursue https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor.  Write me an email if you are not able to get it promptly, in which case I will address the situation another way.  Ensuring OpenBLAS can be compiled with the Intel Fortran compiler is a good thing.

**Comment by martin-frbg** [comment] 2017-02-16 11:59
No response in a bit over two weeks, not even an automated "we will process your request in due time". Either there is something non-obvious one has to do on that Intel website or it is just an address scraper. (Though I could understand not wanting to support a possible competitor to their MKL)
If you happen to have the build log and/or the unusable libopenblas.so from four weeks ago still lying around I could take a look in case I spot anything going wrong earlier.

**Comment by jeffhammond** [comment] 2017-02-20 19:05
@martin-frbg You submitted an Intel Premier Support ticket?  They recently changed the database back-end, so perhaps something went wrong with the submission.  If you tell me the ticket number, I can inquire internally.

In any case, I am confident that no one is sandbagging your support request because OpenBLAS competes with MKL.  The issue with OpenBLAS appears to be a Fortran compiler problem, and if it is a bug, it should be fixed regardless of what software discovered it.

Intel employees contribute to a wide range of open-source software that _complements_ our proprietary offerings, including GCC, Clang, BLIS, MPICH, and Open-MPI.

**Comment by martin-frbg** [comment] 2017-02-20 22:27
Actually I am no longer sure what if anything I submitted, maybe I failed an elementary intelligence test there - after entering my details I was taken to what looked to be an unrelated screen with an input field for a serial number (which I did not have as I expected to be provided with a serial key and/or download link after approval)

**Comment by martin-frbg** [comment] 2017-02-21 23:28
Grabbed a 30-day eval copy of Parallel Studio, problem is reproducible and appears to stem from missing comma characters on the end of the first line of an EXTERNAL statement that is continued by a fortran-standard continuation card, viz

>      EXTERNAL    SLASCL, SSCAL, SSTEQR, SSTERF, XERBLA
    $SSYTRD_SB2ST

in ssbev_2stage.f leading to xerblassytrd_sb2st as an external reference in ssbev_2stage.o and finally libopenblas.so. Will fix tomorrow - too tired to do it now.
(As an aside, trying with CC=icc landed me with #718/#962 for which PR#915 exists but appears to have been ignored by those in the know. Given #1078 I suspect there may be reason for concern here)

**Closed** 2017-02-22 09:31 UTC

**Comment by neveroldmilk** [comment] 2017-02-22 13:11
I also encountered this problem, and there are about 7 linking errors caused by the fortran part of lapacak 3.7.0 (sorry for part of this log is in Chinese, but I still believe you can understand what it means):

zdrvst2stg.obj : error LNK2001: 无法解析的外部符号(unresolved external symbol) ZHETRD_SY2SB
zerrst.obj : error LNK2001: 无法解析的外部符号 ZHETRD_SY2SB
zdrvst2stg.obj : error LNK2001: 无法解析的外部符号 ZHETRD_SB2ST
zerrst.obj : error LNK2001: 无法解析的外部符号 ZHETRD_SB2ST
zchkhb2stg.obj : error LNK2001: 无法解析的外部符号 ZHBTRD_HB2ST
lapack.lib(zhbev_2stage.obj) : error LNK2001: 无法解析的外部符号 ZSTEQRZHETRD_2STAGE
lapack.lib(ztrevc3.obj) : error LNK2001: 无法解析的外部符号 ZLATRSZGEMM
D:\Code\lapack-3.7.0\build\bin\Release\xeigtstz.exe : fatal error LNK1120: 5 个无法解析的外部命令

I use msvc compiler and intel fortran compiler to build this project, and received above errors. After I carefully study your discussions, I also believe this is a calling issue for the fortran API.

**Comment by martin-frbg** [comment] 2017-02-22 13:44
The zhvbev_2stage.obj and ztrevc3.obj are what should be fixed by my patch. The others appear to be declared as "EXTERNAL" functions by the files zdrvst2stg.f, zerrst.f etc  in the TESTING/EIG folder but never actually used by them (which is just as well, as they do not exist :-) )

**Comment by martin-frbg** [comment] 2017-02-22 14:17
Correction: the "ZHBTRD_HB2ST" in the EXTERNAL statement of TESTING/EIG/zchkhb2stg.f appears to be a typo, it should read ZHETRD_HB2ST - but the ZHETRD_SY2SB and ZHETRD_SB2ST mentioned in the EXTERNAL declarations in zdrvst2stg.f and zerrst.f can simply be removed.
 
As these functions appear to be used only for some regression tests that come with lapack, I think these errors should not prevent building the library. So you will probably only need to add the missing commas from my patch (click on the "1104" in the "Closed" message above and then click on the "Files changed"
to see where the commas need to be added if you do not want to checkout a development version from github)
