### ISSUE TITLE
Dead-lock on 0.3.26 on Windows in OpenBLAS multi-threading nested within OpenMP multi-threading

### ISSUE THREAD

**Issue by lesteve** [xianyi/OpenBLAS#4582] opened 2024-03-26 15:01 UTC
Snippet that reproduces the issue: 
```c
#include<stdio.h>
#include<stdlib.h>
#include "cblas.h"

int main(){

int n = 14000;
int incx = 1;
double *x, ddt;

x = (double*)malloc(n*sizeof(double));

for (int i=0; i<n; i++){
     x[i] = 1.0;
}


#pragma omp parallel
{
#pragma omp parallel for
for (int i=0; i<10; i++){
   ddt = cblas_ddot(n, x, incx, x, incx);
}
}
printf("dot(x, x) = %f", ddt);
free(x);
}
```

The dead-lock is due to: https://github.com/OpenMathLib/OpenBLAS/pull/4359:
- the dead-lock does happen on https://github.com/OpenMathLib/OpenBLAS/commit/e60fb0f39731ae9c21c5fd74d432f03b83d2a7d5 (merge commit for https://github.com/OpenMathLib/OpenBLAS/pull/4359)
- there is not dead-lock in the previous merge commit in the develop branch https://github.com/OpenMathLib/OpenBLAS/commit/5b09833b1c877ad1d395ee38791521ccd32386be

Context:
- discussion and debugging in https://github.com/scipy/scipy/issues/20294
- originally report in https://github.com/scikit-learn/scikit-learn/issues/28625

**Comment by martin-frbg** [comment] 2024-03-26 15:18
Thanks for all the work on getting the reproducer - holding off on a revert though in case a better fix is found quickly enough

**Comment by mseminatore** [comment] 2024-03-28 20:05
@martin-frbg @lesteve I may have found the issue and am working on a fix. Interestingly, in reviewing the Linux code l found the following code at blas_server.c:896 within `exec_blas()`:

```
#ifdef __ELF__
  if (omp_in_parallel && (num > 1)) {
    if (omp_in_parallel() > 0) {
      fprintf(stderr,
	      "OpenBLAS Warning : Detect OpenMP Loop and this application may hang. "
	      "Please rebuild the library with USE_OPENMP=1 option.\n");
    }
  }
#endif
```
Which strongly suggests that even the Linux version does not expect or support the scenario this bug represents. That code traces back 14 years to GotoBLAS2. Maybe this is legacy code that is no longer relevant? 

If it is still relevant, then a separate fix may also be required for the Linux thread server if this is intended to be safely supported.

**Comment by mattip** [comment] 2024-03-28 21:32
If there was a problem on linux with the code pattern used in the issue, I would have expected this warning or a crash to have shown up in testing. I wonder why the warning is not hit as expected, maybe there is something else going on.

**Comment by mseminatore** [comment] 2024-03-28 21:52
Agreed. I am guessing something else is going on. For example, is __ELF__ not defined for the build? Also, I notice the missing parens around **omp_in_parallel** in the first if statement. That is an OMP function name - if the OpenBlas isn't built/linked with OMP shouldn't there be an undefined symbol? Maybe that symbol is stubbed in as a nullptr for non-OMP builds? I don't have time to investigate the Linux side until I fix the Windows side.

**Comment by mseminatore** [comment] 2024-03-28 22:32
PR #4587 sent.

**Comment by rgommers** [comment] 2024-03-31 18:23
Looks like we're almost there:
- @mseminatore's PR was merged
- A new `openblas-libs` build was done: https://github.com/MacPython/openblas-libs/pull/149
- Incorporating that new build for SciPy 1.13.0 is in progress: https://github.com/scipy/scipy/pull/20362

It seems this issue can be closed when it's confirmed that the fix works for the original scikit-learn issue.

**Comment by martin-frbg** [comment] 2024-03-31 18:38
There's also the side issue whether to add the reproducer to the "utest" set, which is why I haven't closed the issue here yet. Plan to sort this tonight or tomorrow with the impending release

**Comment by mseminatore** [comment] 2024-04-02 19:01
It looks like several of the upstream bugs have now been closed. Is this confirmation that the fix has addressed the issue?

@martin-frbg let me know if I can help with the utest.

**Comment by martin-frbg** [comment] 2024-04-02 20:58
I _think_ the closing happened automatically as a (normally desired) side effect of merging the respective fix, I am not entirely sure if anybody has ran scikit-learn with the new packages yet. (Though I'm confident that you fixed the underlying issue)

**Comment by tylerjereddy** [comment] 2024-04-02 21:31
That's right, we somewhat-urgently needed to release new SciPy to support NumPy 2.0.0, so the closing of the issue basically represents that we pulled in your patch and we're hoping for the best, and I'm not sure I've seen something more robust testing-wise yet, but I imagine we'll get some noise if the problem still persists when `1.13.0` is out soon.

**Comment by lesteve** [comment] 2024-04-03 06:35
I tested quickly with scipy 1.13 on Windows, which has the OpenBLAS fix from https://github.com/OpenMathLib/OpenBLAS/pull/4587. I can confirm the original scikit-learn does not happen anymore, so thanks everyone for this!

**Closed as completed** 2024-04-03 06:50 UTC
