### ISSUE TITLE
NPROCESS_ONLN or NPROCESS_CONF

### ISSUE THREAD

**Issue by howard0su** [xianyi/OpenBLAS#978] opened 2016-10-09 07:46 UTC
In my arm board (JETSON TK1), CONF is always 4. ONLN is 1 when the system is idle. ONLN become 4 when there are multi tasks are running. So this board has truly 4 CPUs.

In current code, ncpu is fetched from ONLN which doesn't make sense for my scenario. I would like to get feedback on how to fix this? I don't know what's the original thinking when adding this code in.

**Comment by martin-frbg** [comment] 2016-10-09 10:57
Looks like a duplicate of #782 (there it was claimed that multiprocessing worked as expected when the library was statically linked, which would seem to suggest a problem with the build environment rather than OpenBLAS itself)

**Comment by howard0su** [comment] 2016-10-12 12:47
I think this is a different issue. this issue is not common in desktop platform. However in ARM platform, this is common that ONLN != CONF and ONLN will dynamic adjusted when load increasing.

**Comment by martin-frbg** [comment] 2016-10-12 14:24
Right, sorry for the noise.

**Comment by xianyi** [comment] 2016-10-13 02:56
Looks like I need use CONF instead of ONLN.

**Comment by howard0su** [comment] 2016-10-13 03:28
This is what I suggested. do you want me to submit a pull request as I already had it locally and tested in Jetson TK1 platform.

**Comment by martin-frbg** [comment] 2016-10-17 12:44
I see xianyi committed your PR #981 earlier today.

**Closed** 2016-10-17 14:16 UTC
